export const COUNTRY_OPTIONS = [
  "Afganistan",
  "Akrotiri (terytorium zamorskie Wielkiej Brytanii)",
  "Albania",
  "Algieria",
  "Andora",
  "Angola",
  "Anguilla (terytorium zamorskie Wielkiej Brytanii)",
  "Antarktyda",
  "Antigua i Barbuda",
  "Arabia Saudyjska",
  "Argentyna",
  "Armenia",
  "Aruba (terytorium zamorskie Niderlandów)",
  "Australia",
  "Australijskie Terytorium Antarktyczne",
  "Austria",
  "Azerbejdżan",
  "Bahamy",
  "Bahrajn",
  "Bangladesz",
  "Barbados",
  "Belgia",
  "Belize",
  "Benin",
  "Bermudy (terytorium zamorskie Wielkiej Brytanii)",
  "Bhutan",
  "Białoruś",
  "Boliwia",
  "Bonaire (terytorium zamorskie Niderlandów)",
  "Bośnia i Hercegowina",
  "Botswana",
  "Brazylia",
  "Brunei (Państwo Brunei Darussalam)",
  "Brytyjskie Terytorium Antarktyczne (terytorium zamorskie Wielkiej Brytanii)",
  "Brytyjskie Terytorium Oceanu Indyjskiego (terytorium zamorskie Wielkiej Brytanii)",
  "Brytyjskie Wyspy Dziewicze (terytorium zamorskie Wielkiej Brytanii)",
  "Bułgaria",
  "Burkina Faso",
  "Burundi",
  "Ceuta (terytorium zamorskie Hiszpanii)",
  "Chile",
  "Chiny",
  "Chorwacja",
  "Curaçao (terytorium zamorskie Niderlandów)",
  "Cypr",
  "Czad",
  "Czarnogóra",
  "Czechy",
  "Dania (z wyłączeniem Grenlandii)",
  "Demokratyczna Republika Konga",
  "Dependencja Rossa",
  "Dhekelia (terytorium zamorskie Wielkiej Brytanii)",
  "Dominika",
  "Dominikana",
  "Dżibuti",
  "Egipt",
  "Ekwador",
  "Erytrea",
  "Estonia",
  "Eswatini",
  "Etiopia",
  "Falklandy (terytorium zamorskie Wielkiej Brytanii)",
  "Fidżi (Republika Fidżi)",
  "Filipiny",
  "Finlandia (wraz z Wyspami Alandzkimi)",
  "Francja (z wyłączeniem terytoriów zamorskich)",
  "Francuskie Terytoria Południowe i Antarktyczne (terytorium zamorskie Francji)",
  "Gabon",
  "Gambia",
  "Georgia Południowa i Sandwich Południowy (terytorium zamorskie Wielkiej Brytanii)",
  "Ghana",
  "Gibraltar",
  "Grecja",
  "Grenada",
  "Grenlandia (terytorium autonomiczne Danii)",
  "Gruzja",
  "Guam",
  "Gujana",
  "Gujana Francuska (terytorium zamorskie Francji)",
  "Gwadelupa (terytorium zamorskie Francji)",
  "Gwatemala",
  "Gwinea",
  "Gwinea Bissau",
  "Gwinea Równikowa",
  "Haiti",
  "Hiszpania (z wyłączeniem Wysp Kanaryjskich, Ceuty i Melilli)",
  "Honduras",
  "Hongkong",
  "Indie",
  "Indonezja",
  "Irak",
  "Iran",
  "Irlandia",
  "Islandia",
  "Izrael",
  "Jamajka",
  "Jan Mayen (terytorium zależne Norwegii)",
  "Japonia",
  "Jemen",
  "Jordania",
  "Kajmany (terytorium zamorskie Wielkiej Brytanii)",
  "Kambodża",
  "Kamerun",
  "Kanada",
  "Katar",
  "Kazachstan",
  "Kenia",
  "Kirgistan",
  "Kiribati",
  "Kolumbia",
  "Komory",
  "Kongo",
  "Korea Południowa (Republika Korei)",
  "Korea Północna (Koreańska Republika Ludowo-Demokratyczna)",
  "Kosowo",
  "Kostaryka",
  "Kuba",
  "Kuwejt",
  "Laos",
  "Lesotho",
  "Liban",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Litwa",
  "Luksemburg",
  "Łotwa",
  "Macedonia Północna",
  "Madagaskar",
  "Majotta (terytorium zamorskie Francji)",
  "Makau",
  "Malawi",
  "Malediwy",
  "Malezja",
  "Mali",
  "Malta",
  "Małe Oddalone Wyspy Stanów Zjednoczonych",
  "Mariany Północne",
  "Maroko",
  "Martynika (terytorium zamorskie Francji)",
  "Mauretania",
  "Mauritius",
  "Meksyk",
  "Melilla (terytorium zamorskie Hiszpanii)",
  "Mikronezja",
  "Mjanma (Myanmar)",
  "Mołdawia",
  "Monako",
  "Mongolia",
  "Montserrat (terytorium zamorskie Wielkiej Brytanii)",
  "Mozambik",
  "Namibia",
  "Nauru",
  "Nepal",
  "Niderlandy (z wyłączeniem terytoriów zamorskich)",
  "Niemcy",
  "Niger",
  "Nigeria",
  "Nikaragua",
  "Niue",
  "Norfolk",
  "Norwegia (z wyłączeniem wysp Svalbard i Jan Mayen)",
  "Nowa Kaledonia (terytorium zamorskie Francji)",
  "Nowa Zelandia",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestyna",
  "Panama",
  "Papua Nowa Gwinea",
  "Paragwaj",
  "Peru",
  "Pitcairn (terytorium zamorskie Wielkiej Brytanii)",
  "Polinezja Francuska (terytorium zamorskie Francji)",
  "Polska",
  "Południowa Afryka (Republika Południowej Afryki, RPA)",
  "Portoryko",
  "Portugalia",
  "Republika Środkowoafryańska",
  "Republika Zielonego Przylądka",
  "Reunion (terytorium zamorskie Francji)",
  "Rosja (część azjatycka)",
  "Rosja (część europejska bez obwodu kaliningradzkiego)",
  "Rosja (obwód kaliningradzki)",
  "Rumunia",
  "Rwanda",
  "Saba (terytorium zamorskie Niderlandów)",
  "Sahara Zachodnia",
  "Saint Barthelemy (terytorium zamorskie Francji)",
  "Saint Kitts i Nevis",
  "Saint Lucia",
  "Saint Vincent i Grenadyny",
  "Saint-Martin (terytorium zamorskie Francji)",
  "Saint-Pierre i Miquelon (terytorium zamorskie Francji)",
  "Salwador",
  "Samoa",
  "Samoa Amerykańskie",
  "San Marino",
  "Senegal",
  "Serbia",
  "Seszele",
  "Sierra Leone",
  "Singapur",
  "Sint Eustatius (terytorium zamorskie Niderlandów)",
  "Sint Maarten (terytorium zamorskie Niderlandów)",
  "Słowacja",
  "Słowenia",
  "Somalia",
  "Sri Lanka",
  "Stany Zjednoczone Ameryki (USA)",
  "Sudan",
  "Sudan Południowy",
  "Surinam",
  "Svalbard (terytorium zależne Norwegii)",
  "Syria",
  "Szwajcaria",
  "Szwecja",
  "Tadżykistan",
  "Tajlandia",
  "Tajwan",
  "Tanzania",
  "Timor Wschodni",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trynidad i Tobago",
  "Tunezja",
  "Turcja (część leżąca na wschód od cieśnin Dardanele i Bosfor)",
  "Turcja (część leżąca na zachód od cieśnin Dardanele i Bosfor)",
  "Turkmenistan",
  "Turks i Caicos (terytorium zamorskie Wielkiej Brytanii)",
  "Tuvalu",
  "Uganda",
  "Ukraina",
  "Urugwaj",
  "Uzbekistan",
  "Vanuatu",
  "Wallis i Futuna (terytorium zamorskie Francji)",
  "Watykan",
  "Wenezuela",
  "Węgry",
  "Wielka Brytania (wraz z Irlandią Północną, wyspą Man i Wyspami Normandzkimi, ale z wyłączeniem terytoriów zamorskich)",
  "Wietnam",
  "Włochy",
  "Wybrzeże Kości Słoniowej",
  "Wyspa Bouveta (terytorium zależne Norwegii)",
  "Wyspa Bożego Narodzenia",
  "Wyspa Clippertona (terytorium zamorskie Francji)",
  "Wyspa Piotra I (terytorium zależne Norwegii)",
  "Wyspa Świętej Heleny (terytorium zamorskie Wielkiej Brytanii)",
  "Wyspy Ashmore i Cartiera",
  "Wyspy Cooka",
  "Wyspy Dziewicze Stanów Zjednoczonych",
  "Wyspy Heard i McDonalda",
  "Wyspy Kanaryjskie (terytorium zamorskie Hiszpanii)",
  "Wyspy Kokosowe (Keelinga)",
  "Wyspy Marshalla",
  "Wyspy Morza Koralowego",
  "Wyspy Owcze",
  "Wyspy Salomona",
  "Wyspy Świętego Tomasza i Książęca",
  "Zambia",
  "Ziemia Królowej Maud (terytorium zależne Norwegii)",
  "Zimbabwe",
  "Zjednoczone Emiraty Arabskie",
] as const

export function normalizeCountrySearch(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
}

export function filterCountries(query: string): string[] {
  const normalizedQuery = normalizeCountrySearch(query.trim())
  if (!normalizedQuery) return [...COUNTRY_OPTIONS]
  return COUNTRY_OPTIONS.filter((country) =>
    normalizeCountrySearch(country).includes(normalizedQuery)
  )
}
