-- airports seed batch 10/11
INSERT INTO public.airports (code, name) VALUES
('ZSJD', 'Jingdezhen Luojia Airport - Jingdezhen (ZSJD)'),
('ZSJG', 'Jining Da''an Airport - Jining (ZSJG)'),
('ZSJJ', 'Jiujiang Lushan Airport - Jiujiang (ZSJJ)'),
('ZSJN', 'Jinan Yaoqiang International Airport - Jinan (Licheng) (ZSJN)'),
('ZSJU', 'Quzhou Airport - Quzhou (Kezheng) (ZSJU)'),
('ZSLG', 'Lianyungang Huaguoshan International Airport - Lianyungang (ZSLG)'),
('ZSLO', 'Liancheng Guanzhishan Airport - Longyan (Liancheng) (ZSLO)'),
('ZSLQ', 'Taizhou Luqiao Airport - Taizhou (Luqiao) (ZSLQ)'),
('ZSLY', 'Linyi Qiyang Airport - Linyi (Hedong) (ZSLY)'),
('ZSNB', 'Ningbo Lishe International Airport - Ningbo (ZSNB)'),
('ZSNJ', 'Nanjing Lukou International Airport - Nanjing (ZSNJ)'),
('ZSNT', 'Nantong Xingdong International Airport - Nantong (Tongzhou) (ZSNT)'),
('ZSOF', 'Hefei Xinqiao International Airport - Hefei (ZSOF)'),
('ZSPD', 'Shanghai Pudong International Airport - Shanghai (Pudong) (ZSPD)'),
('ZSQD', 'Qingdao Jiaodong International Airport - Qingdao (Jiaozhou) (ZSQD)'),
('ZSQZ', 'Quanzhou Jinjiang International Airport - Quanzhou (ZSQZ)'),
('ZSRZ', 'Rizhao Shanzihe Airport - Rizhao (Donggang) (ZSRZ)'),
('ZSSH', 'Huai''an Lianshui International Airport - Huai''an (ZSSH)'),
('ZSSM', 'Sanming Shaxian Airport - Sanming (Sha) (ZSSM)'),
('ZSSR', 'Shangrao Sanqingshan Airport - Shangrao (Hengfeng) (ZSSR)'),
('ZSSS', 'Shanghai Hongqiao International Airport - Shanghai (Minhang) (ZSSS)'),
('ZSTX', 'Tunxi International Airport - Huangshan (ZSTX)'),
('ZSWA', 'Wuhu Xuanzhou Airport - Wuhu (ZSWA)'),
('ZSWF', 'Weifang Nanyuan Airport - Weifang (Kuiwen) (ZSWF)'),
('ZSWH', 'Weihai Dashuibo Airport - Weihai (ZSWH)'),
('ZSWX', 'Sunan Shuofang International Airport - Wuxi (ZSWX)'),
('ZSWY', 'Nanping Wuyishan Airport - Wuyishan (ZSWY)'),
('ZSWZ', 'Wenzhou Longwan International Airport - Wenzhou (Longwan) (ZSWZ)'),
('ZSXZ', 'Xuzhou Guanyin International Airport - Xuzhou (ZSXZ)'),
('ZSYA', 'Yangzhou Taizhou Airport - Yangzhou (ZSYA)'),
('ZSYC', 'Yichun Mingyueshan Airport - Yichun (ZSYC)'),
('ZSYN', 'Yancheng Nanyang International Airport - Yancheng (Tinghu) (ZSYN)'),
('ZSYT', 'Yantai Penglai International Airport - Yantai (ZSYT)'),
('ZSYW', 'Yiwu Airport - Jinhua (Yiwu) (ZSYW)'),
('ZSZS', 'Zhoushan Putuoshan Airport - Zhoushan (ZSZS)'),
('ZUAL', 'Ngari Gunsa Airport - Shiquanhe (ZUAL)'),
('ZUAS', 'Anshun Huangguoshu Airport - Anshun (Xixiu) (ZUAS)'),
('ZUBD', 'Qamdo Bangda Airport - Bangda (ZUBD)'),
('ZUBJ', 'Bijie Feixiong Airport - Bijie (ZUBJ)'),
('ZUCK', 'Chongqing Jiangbei International Airport - Chongqing (ZUCK)'),
('ZUDA', 'Dazhou Jinya Airport - Dazhou (Dachuan) (ZUDA)'),
('ZUDC', 'Daocheng Yading Airport - Garze (Daocheng) (ZUDC)'),
('ZUDX', 'Dachuan Airport - Dazhou (Daxian) (ZUDX)'),
('ZUGU', 'Guangyuan Panlong Airport - Guangyuan (Lizhou) (ZUGU)'),
('ZUGY', 'Guiyang Longdongbao International Airport - Guiyang (Nanming) (ZUGY)'),
('ZUGZ', 'Garze Gesar Airport - Garze (Garze) (ZUGZ)'),
('ZUJZ', 'Jiuzhai Huanglong Airport - Ngawa (Songpan) (ZUJZ)'),
('ZUKD', 'Kangding Airport - Garze (Kangding) (ZUKD)'),
('ZUKJ', 'Kaili Huangping Airport - Kaili  (Huangping) (ZUKJ)'),
('ZULB', 'Libo Airport - Qiannan (Libo) (ZULB)'),
('ZULS', 'Lhasa Gonggar Airport - Shannan (Gonggar) (ZULS)'),
('ZULZ', 'Luzhou Yunlong Airport - Luzhou (Yunlong) (ZULZ)'),
('ZUMT', 'Zunyi Maotai Airport - Zunyi (ZUMT)'),
('ZUMY', 'Mianyang Nanjiao Airport - Mianyang (Fucheng) (ZUMY)'),
('ZUNC', 'Nanchong Gaoping Airport - Nanchong (Gaoping) (ZUNC)'),
('ZUNP', 'Liping Airport - Liping (ZUNP)'),
('ZUNZ', 'Nyingchi Mainling Airport - Nyingchi (Mainling) (ZUNZ)'),
('ZUPS', 'Liupanshui Yuezhao Airport - Liupanshui (Zhongshan) (ZUPS)'),
('ZUQJ', 'Qianjiang Wulingshan Airport - Qianjiang (ZUQJ)'),
('ZURK', 'Xigaze Peace Airport / Shigatse Air Base - Xigaze  (Samzhubze) (ZURK)'),
('ZUSH', 'Shannan Longzi Airport - Shannan (ZUSH)'),
('ZUTC', 'Tengchong Tuofeng Airport - Baoshan (Tengchong) (ZUTC)'),
('ZUTF', 'Chengdu Tianfu International Airport - Chengdu (Jianyang) (ZUTF)'),
('ZUTR', 'Tongren Fenghuang Airport - Tongren (Daxing) (ZUTR)'),
('ZUUU', 'Chengdu Shuangliu International Airport - Chengdu (Shuangliu) (ZUUU)'),
('ZUWL', 'Chongqing Xiannüshan Airport - Wulong (ZUWL)'),
('ZUWS', 'Chongqing Wushan Airport - Wushan (ZUWS)'),
('ZUWX', 'Wanzhou Wuqiao Airport - Wanzhou (ZUWX)'),
('ZUXC', 'Xichang Qingshan Airport - Liangshan (Xichang) (ZUXC)'),
('ZUYB', 'Yibin Wuliangye Airport - Yibin (Cuiping) (ZUYB)'),
('ZUYI', 'Xingyi Wanfenglin Airport - Xingyi (ZUYI)'),
('ZUZH', 'Panzhihua Bao''anying Airport - Panzhihua (Renhe) (ZUZH)'),
('ZUZY', 'Zunyi Xinzhou Airport - Zunyi (ZUZY)'),
('ZWAK', 'Aksu Hongqipo Airport - Aksu (Onsu) (ZWAK)'),
('ZWAL', 'Aral Tarim Airport - Aral (ZWAL)'),
('ZWAT', 'Altay Xuedu Airport - Altay (ZWAT)'),
('ZWBL', 'Bole Alashankou Airport - Bole (ZWBL)'),
('ZWCM', 'Qiemo Yudu Airport - Qiemo (ZWCM)'),
('ZWFY', 'Fuyun Koktokay Airport - Fuyun (ZWFY)'),
('ZWHM', 'Hami Airport - Hami (ZWHM)'),
('ZWHZ', 'Shihezi Huayuan Airport - Shihezi (ZWHZ)'),
('ZWKC', 'Kuqa Qiuci Airport - Kuqa (ZWKC)'),
('ZWKL', 'Korla Licheng Airport - Korla (ZWKL)'),
('ZWKM', 'Karamay Airport - Karamay (ZWKM)'),
('ZWKN', 'Burqin Kanas Airport - Burqin (ZWKN)'),
('ZWNL', 'Xinyuan Nalati Airport - Xinyuan (ZWNL)'),
('ZWRQ', 'Ruoqiang Loulan Airport - Ruoqiang Town (ZWRQ)'),
('ZWSC', 'Shache Airport - Shache (ZWSC)'),
('ZWSH', 'Kashgar Laining International Airport - Kashgar (ZWSH)'),
('ZWTC', 'Tacheng Qianquan Airport - Tacheng (ZWTC)'),
('ZWTL', 'Turpan Jiaohe Airport - Turpan (ZWTL)'),
('ZWTN', 'Hotan Airport - Hotan (ZWTN)'),
('ZWWW', 'Ürümqi Tianshan International Airport - Ürümqi (ZWWW)'),
('ZWYN', 'Yining Airport - Ili (Yining / Ghulja) (ZWYN)'),
('ZWYT', 'Yutian Wanfang Airport - Hotan (Yutian) (ZWYT)'),
('ZYAS', 'Anshan Teng''ao Airport / Anshan Air Base - Anshan (ZYAS)'),
('ZYBA', 'Baicheng Chang''an Airport - Baicheng (ZYBA)'),
('ZYBS', 'Changbaishan Airport - Baishan (ZYBS)'),
('ZYCC', 'Changchun Longjia International Airport - Changchun (ZYCC)'),
('ZYCH', 'Changhai Airport - Dalian (Changhai) (ZYCH)'),
('ZYCY', 'Chaoyang Airport - Shuangta, Chaoyang (ZYCY)'),
('ZYDD', 'Dandong Langtou Airport - Dandong (Zhenxing) (ZYDD)'),
('ZYDQ', 'Daqing Sartu Airport - Daqing (ZYDQ)'),
('ZYDU', 'Wudalianchi Dedu Airport - Heihe (ZYDU)'),
('ZYFY', 'Fuyuan Dongji Airport - Fuyuan (ZYFY)'),
('ZYHB', 'Harbin Taiping International Airport - Harbin (ZYHB)'),
('ZYHE', 'Heihe Aihui Airport - Heihe (ZYHE)'),
('ZYJD', 'Daxing''anling Elunchun Airport - Jiagedaqi (ZYJD)'),
('ZYJM', 'Jiamusi Dongjiao Airport - Jiamusi (ZYJM)'),
('ZYJS', 'Jiansanjiang Shidi Airport - Jiansanjiang (ZYJS)'),
('ZYJX', 'Jixi Xingkaihu Airport - Jixi (ZYJX)'),
('ZYJZ', 'Jinzhou Bay Airport - Jinzhou (Linghai) (ZYJZ)'),
('ZYLD', 'Yichun Lindu Airport - Yichun (ZYLD)'),
('ZYMD', 'Mudanjiang Hailang International Airport - Mudanjiang (ZYMD)'),
('ZYMH', 'Mohe Gulian Airport - Mohe (ZYMH)'),
('ZYQQ', 'Qiqihar Sanjiazi Airport - Qiqihar (ZYQQ)'),
('ZYSQ', 'Songyuan Chaganhu Airport - Qian Gorlos Mongol Autonomous County (ZYSQ)'),
('ZYTL', 'Dalian Zhoushuizi International Airport - Dalian (Ganjingzi) (ZYTL)'),
('ZYTN', 'Tonghua Sanyuanpu Airport - Tonghua (ZYTN)'),
('ZYTX', 'Shenyang Taoxian International Airport - Hunnan, Shenyang (ZYTX)'),
('ZYYJ', 'Yanji Chaoyangchuan Airport - Yanji (ZYYJ)'),
('ZYYK', 'Yingkou Lanqi Airport - Yingkou (Laobian) (ZYYK)'),
('SKAR', 'El Eden Airport - Armenia (SKAR)'),
('SKAS', 'Tres De Mayo Airport - Puerto Asís (SKAS)'),
('SKBG', 'Palonegro Airport - Bucaramanga (SKBG)'),
('SKBO', 'El Dorado International Airport - Bogota (SKBO)'),
('SKBQ', 'Ernesto Cortissoz International Airport - Barranquilla (SKBQ)'),
('SKBS', 'José Celestino Mutis Airport - Bahía Solano (SKBS)'),
('SKBU', 'Gerardo Tobar López Airport - Buenaventura (SKBU)'),
('SKCC', 'Camilo Daza International Airport - Cúcuta (SKCC)'),
('SKCG', 'Rafael Nunez International Airport - Cartagena (SKCG)'),
('SKCL', 'Alfonso Bonilla Aragon International Airport - Cali (SKCL)'),
('SKCO', 'La Florida Airport - Tumaco (SKCO)'),
('SKCZ', 'Las Brujas Airport - Corozal (SKCZ)'),
('SKEJ', 'Yariguíes Airport - Barrancabermeja (SKEJ)'),
('SKFL', 'Gustavo Artunduaga Paredes Airport - Florencia (SKFL)'),
('SKGP', 'Juan Casiano Airport - Guapi (SKGP)'),
('SKGZ', 'La Jagua Airport - Garzón (SKGZ)'),
('SKIB', 'Perales Airport - Ibagué (SKIB)'),
('SKIP', 'San Luis Airport - Ipiales (SKIP)'),
('SKLC', 'Antonio Roldán Betancur Airport - Carepa (SKLC)'),
('SKLG', 'Caucaya Airport - Puerto Leguízamo (SKLG)'),
('SKLP', 'La Pedrera Airport - La Pedrera (SKLP)'),
('SKLT', 'Alfredo Vásquez Cobo International Airport - Leticia (SKLT)'),
('SKMD', 'Enrique Olaya Herrera Airport - Medellín (SKMD)'),
('SKMR', 'Los Garzones Airport - Montería (SKMR)'),
('SKMU', 'Fabio Alberto Leon Bentley Airport - Mitú (SKMU)'),
('SKMZ', 'La Nubia Airport - Manizales (SKMZ)'),
('SKNA', 'La Macarena Airport - La Macarena (SKNA)'),
('SKNQ', 'Reyes Murillo Airport - Nuquí (SKNQ)'),
('SKNV', 'Benito Salas Airport - Neiva (SKNV)'),
('SKPC', 'German Olano Airport - Puerto Carreno (SKPC)'),
('SKPD', 'Obando Cesar Gaviria Trujillo Airport - Puerto Inírida (SKPD)'),
('SKPE', 'Matecana International Airport - Pereira (SKPE)'),
('SKPP', 'Guillermo León Valencia Airport - Popayán (SKPP)'),
('SKPS', 'Antonio Narino Airport - Chachagüí (SKPS)'),
('SKPV', 'El Embrujo Airport - Providencia (SKPV)'),
('SKRA', 'Tarapacá Airport - Tarapacá (SKRA)'),
('SKRG', 'Jose Maria Córdova International Airport - Medellín (SKRG)'),
('SKRH', 'Almirante Padilla Airport - Riohacha (SKRH)'),
('SKSA', 'Los Colonizadores Airport - Saravena (SKSA)'),
('SKSJ', 'Jorge E. Gonzalez Torres Airport - San José Del Guaviare (SKSJ)'),
('SKSM', 'Simón Bolívar International Airport - Santa Marta (SKSM)'),
('SKSP', 'Gustavo Rojas Pinilla International Airport - San Andrés (SKSP)'),
('SKSV', 'Eduardo Falla Solano Airport - San Vicente Del Caguán (SKSV)'),
('SKTL', 'Golfo de Morrosquillo Airport - Santiago de Tolú (SKTL)'),
('SKTM', 'Gustavo Vargas Airport - Tame (SKTM)'),
('SKUC', 'Santiago Perez Airport - Arauca (SKUC)'),
('SKUI', 'El Carano Airport - Quibdó (SKUI)'),
('SKVP', 'Alfonso López Pumarejo Airport - Valledupar (SKVP)'),
('SKVV', 'Vanguardia Airport - Villavicencio (SKVV)'),
('SKYP', 'El Alcaravan - Yopal Airport - Yopal (SKYP)'),
('MRAO', 'Aerotortuguero Airport - Roxana (MRAO)'),
('MRGF', 'Golfito Airport - Golfito (MRGF)'),
('MRLB', 'Guanacaste Airport - Liberia (MRLB)'),
('MRLM', 'Limon International Airport - Puerto Limon (MRLM)'),
('MRNS', 'Nosara Airport - Nicoya (MRNS)'),
('MROC', 'Juan Santamaría International Airport - San José (Alajuela) (MROC)'),
('MRPJ', 'Puerto Jimenez Airport - Puerto Jimenez (MRPJ)'),
('MRPV', 'Tobías Bolanos International Airport - San Jose (MRPV)'),
('MRQP', 'Quepos Managua Airport - Quepos (MRQP)'),
('MUBA', 'Gustavo Rizo Airport - Baracoa (MUBA)'),
('MUBY', 'Carlos Manuel de Cespedes Airport - Bayamo (MUBY)'),
('MUCC', 'Jardines Del Rey Airport - Cayo Coco (MUCC)'),
('MUCF', 'Jaime Gonzalez Airport - Cienfuegos (MUCF)'),
('MUCL', 'Vilo Acuna International Airport - Cayo Largo del Sur (MUCL)'),
('MUCM', 'Ignacio Agramonte International Airport - Camaguey (MUCM)'),
('MUCU', 'Antonio Maceo International Airport - Santiago (MUCU)'),
('MUHA', 'José Martí International Airport - Havana (MUHA)'),
('MUHG', 'Frank Pais International Airport - Holguin (MUHG)'),
('MUMZ', 'Sierra Maestra International Airport - Manzanillo (MUMZ)'),
('MUNG', 'Rafael Cabrera Airport - Nueva Gerona (MUNG)'),
('MUSC', 'Abel Santamaria Airport - Santa Clara (MUSC)'),
('MUTD', 'Alberto Delgado Airport - Trinidad (MUTD)'),
('MUVR', 'Juan Gualberto Gomez International Airport - Matanzas (MUVR)'),
('MUVT', 'Hermanos Ameijeiras Airport - Las Tunas (MUVT)'),
('GVAC', 'Amílcar Cabral International Airport - Espargos (GVAC)'),
('GVBA', 'Rabil Airport - Rabil (GVBA)'),
('GVMA', 'Maio Airport - Vila do Maio (GVMA)'),
('GVNP', 'Nelson Mandela International Airport - Praia (GVNP)'),
('GVSF', 'Sao Felipe Airport - Sao Felipe (GVSF)'),
('GVSN', 'Preguiça Airport - Preguiça (GVSN)'),
('GVSV', 'Sao Pedro Airport - Sao Pedro (GVSV)'),
('TNCC', 'Hato International Airport - Willemstad (TNCC)'),
('YPXM', 'Christmas Island Airport - Flying Fish Cove (YPXM)'),
('LCEN', 'Nicosia (Lefkoşa) Ercan International Airport - Tymbou (Kirklar) (LCEN)'),
('LCGK', 'Lefkoniko Airport / Geçitkale Air Base - Lefkoniko (Geçitkale) (LCGK)'),
('LCLK', 'Larnaca International Airport - Larnaca (LCLK)'),
('LCPH', 'Paphos International Airport - Paphos (LCPH)'),
('LKKV', 'Karlovy Vary Airport - Karlovy Vary (LKKV)'),
('LKMT', 'Ostrava Leos Janáček Airport - Mošnov (LKMT)'),
('LKPD', 'Pardubice Airport - Pardubice (LKPD)'),
('LKPR', 'Václav Havel Airport Prague - Prague (LKPR)'),
('LKTB', 'Brno-Tuřany Airport - Brno (LKTB)'),
('EDAH', 'Heringsdorf Airport - Zirchow (EDAH)'),
('EDDB', 'Berlin Brandenburg Airport - Berlin (EDDB)'),
('EDDC', 'Dresden Airport - Dresden (EDDC)'),
('EDDE', 'Erfurt-Weimar Airport - Erfurt (EDDE)'),
('EDDF', 'Frankfurt Airport - Frankfurt am Main (EDDF)'),
('EDDG', 'Münster Osnabrück Airport - Greven (EDDG)'),
('EDDH', 'Hamburg Helmut Schmidt Airport - Hamburg (EDDH)'),
('EDDK', 'Cologne Bonn Airport - Köln (Cologne) (EDDK)'),
('EDDL', 'Düsseldorf Airport - Düsseldorf (EDDL)'),
('EDDM', 'Munich Airport - Munich (EDDM)'),
('EDDN', 'Nuremberg Airport - Nuremberg (EDDN)'),
('EDDP', 'Leipzig/Halle Airport - Schkeuditz (EDDP)'),
('EDDR', 'Saarbrücken Airport - Saarbrücken (EDDR)'),
('EDDS', 'Stuttgart Airport - Stuttgart (EDDS)'),
('EDDV', 'Hannover Airport - Hannover (EDDV)'),
('EDDW', 'Bremen Airport - Bremen (EDDW)'),
('EDFH', 'Frankfurt-Hahn Airport - Frankfurt am Main (Lautzenhausen) (EDFH)'),
('EDFM', 'Mannheim-City Airport - Mannheim (EDFM)'),
('EDHE', 'Uetersen-Heist Airfield - Heist (EDHE)'),
('EDHL', 'Lübeck Blankensee Airport - Lübeck (EDHL)'),
('EDJA', 'Memmingen Allgau Airport - Memmingen (EDJA)'),
('EDLP', 'Paderborn Lippstadt Airport - Büren (EDLP)'),
('EDLV', 'Weeze Airport - Weeze (EDLV)'),
('EDLW', 'Dortmund Airport - Dortmund (EDLW)'),
('EDNY', 'Friedrichshafen Airport - Friedrichshafen (EDNY)'),
('EDSB', 'Karlsruhe Baden-Baden Airport - Rheinmünster (EDSB)'),
('EDVK', 'Kassel Airport - Calden (EDVK)'),
('EDWE', 'Emden Airport - Emden (EDWE)'),
('EDWG', 'Wangerooge Airport - Wangerooge (EDWG)'),
('EDWJ', 'Juist Airport - Juist (EDWJ)'),
('EDWR', 'Borkum Airport - Borkum (EDWR)'),
('EDWS', 'Norden-Norddeich Airport - Norddeich (EDWS)'),
('EDWY', 'Norderney Airport - Norderney (EDWY)'),
('EDWZ', 'Baltrum Airport - Baltrum (EDWZ)'),
('EDXB', 'Heide-Büsum Airport - Oesterdeichstrich (EDXB)'),
('EDXH', 'Helgoland-Düne Airport - Helgoland (EDXH)'),
('EDXP', 'Harlesiel Airfield - Harlesiel (EDXP)'),
('EDXW', 'Westerland Sylt Airport - Sylt (EDXW)'),
('ETMN', 'Sea-Airport Cuxhaven/Nordholz / Nordholz Naval Airbase - Wurster Nordseeküste (ETMN)'),
('ETNL', 'Rostock-Laage Airport - Laage (ETNL)'),
('HDAM', 'Djibouti-Ambouli Airport - Djibouti City (HDAM)'),
('EKAH', 'Aarhus Airport - Aarhus (EKAH)'),
('EKAT', 'Anholt Airfield - Anholt (EKAT)'),
('EKBI', 'Billund Airport - Billund (EKBI)'),
('EKCH', 'Copenhagen Kastrup Airport - Copenhagen (EKCH)'),
('EKEB', 'Esbjerg Airport - Esbjerg (EKEB)'),
('EKKA', 'Midtjyllands Airport / Air Base Karup - Karup (EKKA)'),
('EKLS', 'Laeso Airport - Laeso (EKLS)'),
('EKOD', 'Odense Hans Christian Andersen Airport - Odense (EKOD)'),
('EKRK', 'Copenhagen Roskilde Airport - Roskilde (EKRK)'),
('EKRN', 'Bornholm Airport - Ronne (EKRN)'),
('EKRS', 'Ringsted Airfield - Ringsted (EKRS)'),
('EKSB', 'Sonderborg Airport - Sonderborg (EKSB)'),
('EKST', 'Sydfyn (Tasinge) Airfield - Svendborg (EKST)'),
('EKYT', 'Aalborg Airport - Aalborg (EKYT)'),
('TDCF', 'Canefield Airport - Canefield (TDCF)'),
('TDPD', 'Douglas-Charles Airport - Marigot (TDPD)'),
('MDBH', 'Maria Montez International Airport - Barahona (MDBH)'),
('MDCY', 'Samaná El Catey International Airport - Samana (MDCY)'),
('MDJB', 'La Isabela International Airport - La Isabela (MDJB)'),
('MDLL', 'Los Llanos de Sabanatosa Airport -  San Pedro de Macorís (MDLL)'),
('MDLR', 'Casa De Campo International Airport - La Romana (MDLR)'),
('MDPC', 'Punta Cana International Airport - Punta Cana (MDPC)'),
('MDPP', 'Gregorio Luperon International Airport - Puerto Plata (MDPP)'),
('MDSD', 'Las Américas International Airport - Santo Domingo (MDSD)'),
('MDST', 'Cibao International Airport - Santiago (MDST)'),
('DAAE', 'Soummam–Abane Ramdane Airport - Bidżaja (DAAE)'),
('DAAG', 'Houari Boumediene Airport - Algiers (DAAG)'),
('DAAJ', 'Djanet Inedbirene Airport - Djanet (DAAJ)'),
('DAAP', 'Illizi Takhamalt Airport - Illizi (DAAP)'),
('DAAS', 'Ain Arnat Airport - Sétif (DAAS)'),
('DAAT', 'Aguenar – Hadj Bey Akhamok Airport - Tamanrasset (DAAT)'),
('DAAV', 'Jijel Ferhat Abbas Airport - Tahir (DAAV)'),
('DABB', 'Annaba Rabah Bitat Airport - Annaba (DABB)'),
('DABC', 'Mohamed Boudiaf International Airport - Constantine (DABC)'),
('DABS', 'Cheikh Larbi Tébessi Airport - Tébessi (DABS)'),
('DABT', 'Batna Mostefa Ben Boulaid Airport - Batna (DABT)'),
('DAOF', 'Tindouf Airport - Tindouf (DAOF)'),
('DAOI', 'Chlef Aboubakr Belkaid International Airport - Chlef (DAOI)'),
('DAON', 'Zenata – Messali El Hadj Airport - Zenata (DAON)'),
('DAOO', 'Oran Es-Sénia (Ahmed Ben Bella) International Airport - Es-Sénia (DAOO)'),
('DAOR', 'Béchar Boudghene Ben Ali Lotfi Airport - Béchar (DAOR)'),
('DATM', 'Bordj Badji Mokhtar Airport - Bordj Badji Mokhtar (DATM)'),
('DAUA', 'Touat Cheikh Sidi Mohamed Belkebir Airport - Adrar (DAUA)'),
('DAUB', 'Biskra - Mohamed Khider Airport - Biskra (DAUB)'),
('DAUE', 'El Golea Airport - El Menia (DAUE)'),
('DAUG', 'Noumérat - Moufdi Zakaria Airport - El Atteuf (DAUG)'),
('DAUH', 'Hassi Messaoud-Oued Irara Krim Belkacem Airport - Hassi Messaoud (DAUH)'),
('DAUI', 'In Salah Airport - In Salah (DAUI)'),
('DAUK', 'Touggourt Sidi Madhi Airport - Touggourt (DAUK)'),
('DAUO', 'Guemar Airport - Guemar (DAUO)'),
('DAUT', 'Timimoun Airport - Timimoun (DAUT)'),
('DAUU', 'Ain Beida Airport - Ouargla (DAUU)'),
('DAUZ', 'Zarzaitine - In Aménas Airport - In Aménas (DAUZ)'),
('SECO', 'Francisco De Orellana Airport - Coca (SECO)'),
('SECU', 'Mariscal Lamar Airport - Cuenca (SECU)'),
('SEGS', 'Seymour Galapagos Ecological Airport - Isla Baltra (SEGS)'),
('SEGU', 'José Joaquín de Olmedo International Airport - Guayaquil (SEGU)'),
('SEII', 'General Villamil Airport - Puerto Villamil (SEII)'),
('SELT', 'Cotopaxi International Airport - Latacunga (SELT)'),
('SEMC', 'Coronel E Carvajal Airport - Macas (SEMC)'),
('SEMT', 'Eloy Alfaro International Airport - Manta (SEMT)'),
('SEQM', 'Mariscal Sucre International Airport - Quito (SEQM)'),
('SERO', 'Santa Rosa - Artillery Colonel Victor Larrea International Airport - Santa Rosa (SERO)'),
('SEST', 'San Cristóbal Airport - Puerto Baquerizo Moreno (SEST)'),
('SECA', 'Ciudad de Catamayo Airport - La Toma (Catamayo) (SECA)'),
('SETN', 'Carlos Concha Torres International Airport - Tachina (SETN)'),
('SETU', 'Lieutenant Colonel Luis A. Mantilla International Airport - Tulcán (SETU)'),
('EEKA', 'Kärdla Airport - Kärdla (EEKA)'),
('EEKE', 'Kuressaare Airport - Kuressaare (EEKE)'),
('EEPU', 'Pärnu Airport - Pärnu (EEPU)'),
('EERU', 'Ruhnu Airfield - Ringsu (EERU)'),
('EETN', 'Lennart Meri Tallinn Airport - Tallinn (EETN)'),
('EETU', 'Tartu Airport - Reola (EETU)'),
('HEAL', 'El Alamein International Airport - El Alamein (HEAL)'),
('HEAR', 'El Arish International Airport - El Arish (HEAR)'),
('HEAT', 'Asyut International Airport - Asyut (HEAT)'),
('HEBA', 'Borj El Arab International Airport - Alexandria (HEBA)'),
('HEBL', 'Abu Simbel Airport - Abu Simbel (HEBL)'),
('HECA', 'Cairo International Airport - Cairo (HECA)'),
('HEGN', 'Hurghada International Airport - Hurghada (HEGN)'),
('HELX', 'Luxor International Airport - Luxor (HELX)'),
('HEMA', 'Marsa Alam International Airport - Marsa Alam (HEMA)'),
('HEMM', 'Marsa Matruh International Airport - Marsa Matruh (HEMM)'),
('HESG', 'Suhaj Mubarak International Airport - Suhaj (HESG)'),
('HESH', 'Sharm El Sheikh International Airport - Sharm El Sheikh (HESH)'),
('HESN', 'Aswan International Airport - Aswan (HESN)'),
('HESW', 'Siwa Oasis North Airport - Siwa Oasis (HESW)'),
('HESX', 'Sphinx International Airport - Al Jiza (HESX)'),
('HETB', 'Taba International Airport - Taba (HETB)'),
('GMMH', 'Dakhla Airport - Dakhla (GMMH)'),
('GMML', 'Hassan I Airport - El Aaiún (GMML)'),
('HHAS', 'Asmara International Airport - Asmara (HHAS)'),
('HHSB', 'Assab International Airport - Assab (HHSB)'),
('GCFV', 'Fuerteventura Airport - El Matorral (GCFV)'),
('GCGM', 'La Gomera Airport - Alajero, La Gomera Island (GCGM)'),
('GCHI', 'El Hierro Airport - El Hierro Island (GCHI)'),
('GCLA', 'La Palma Airport - Sta Cruz de la Palma, La Palma Island (GCLA)'),
('GCLP', 'Gran Canaria Airport - Gran Canaria Island (GCLP)'),
('GCRR', 'César Manrique-Lanzarote Airport - San Bartolomé (GCRR)'),
('GCTS', 'Tenerife Sur Airport - Tenerife (GCTS)'),
('GCXO', 'Tenerife Norte-Ciudad de La Laguna Airport - Tenerife (GCXO)'),
('GEML', 'Melilla Airport - Melilla (GEML)'),
('LEAL', 'Alicante-Elche Miguel Hernández Airport - Alicante (LEAL)'),
('LEAM', 'Almería Airport - Almería (LEAM)'),
('LEAS', 'Asturias Airport - Ranón (LEAS)'),
('LEBB', 'Bilbao Airport - Bilbao (LEBB)'),
('LEBL', 'Josep Tarradellas Barcelona-El Prat Airport - Barcelona (LEBL)'),
('LEBZ', 'Badajoz Airport - Badajoz (LEBZ)'),
('LECH', 'Castellón-Costa Azahar Airport - Castellón de la Plana (LECH)'),
('LECO', 'A Coruna Airport - Culleredo (LECO)'),
('LEDA', 'Lleida-Alguaire Airport - Lleida (LEDA)'),
('LEGE', 'Girona-Costa Brava Airport - Girona (LEGE)'),
('LEGR', 'F.G.L. Airport Granada-Jaén Airport - Granada (LEGR)'),
('LEIB', 'Ibiza Airport - Ibiza (Eivissa) (LEIB)'),
('LEJR', 'Jerez Airport - Jerez de la Frontera (LEJR)'),
('LELN', 'León Int''l Airport - La Virgen Del Camino (LELN)'),
('LEMD', 'Adolfo Suárez Madrid–Barajas Airport - Madrid (LEMD)'),
('LEMG', 'Málaga-Costa del Sol Airport - Málaga (LEMG)'),
('LEMH', 'Menorca Airport - Mahón (Maó) (LEMH)'),
('LEMI', 'Región de Murcia International Airport - Corvera (LEMI)'),
('LEPA', 'Palma de Mallorca Airport - Palma de Mallorca (LEPA)'),
('LEPP', 'Pamplona Airport - Pamplona (LEPP)'),
('LERS', 'Reus Airport - Reus (LERS)'),
('LESA', 'Salamanca Airport - Salamanca (LESA)'),
('LESO', 'San Sebastián Airport - Hondarribia (LESO)'),
('LEST', 'Santiago-Rosalía de Castro Airport - Santiago de Compostela (LEST)'),
('LESU', 'Pirineus - la Seu d''Urgel Airport - La Seu d''Urgell Pyrenees and Andorra (LESU)'),
('LETF', 'Tomás Fernández Espada Airfield - Villamartin (LETF)'),
('LEVC', 'Valencia Airport - Valencia (LEVC)'),
('LEVD', 'Valladolid Airport - Valladolid (LEVD)'),
('LEVT', 'Vitoria Airport - Alava (LEVT)'),
('LEVX', 'Vigo Airport - Vigo (LEVX)'),
('LEXJ', 'Seve Ballesteros-Santander Airport - Santander (LEXJ)'),
('LEZG', 'Zaragoza Airport - Zaragoza (LEZG)'),
('LEZL', 'Sevilla Airport - Sevilla (LEZL)'),
('HASR', 'Shire Inda Selassie Airport - Shire Inda Selassie (HASR)'),
('HAAB', 'Addis Ababa Bole International Airport - Addis Ababa (HAAB)'),
('HAAM', 'Arba Minch Airport - Arba Minch (HAAM)'),
('HAAX', 'Axum Airport - Axum (HAAX)'),
('HABD', 'Bahir Dar Airport - Bahir Dar (HABD)'),
('HADC', 'Kombolcha Airport - Dessie (HADC)'),
('HADD', 'Dembidollo Airport - Dembidollo (HADD)'),
('HADR', 'Aba Tenna Dejazmach Yilma International Airport - Dire Dawa (HADR)'),
('HAGM', 'Gambela Airport - Gambela (HAGM)'),
('HAGN', 'Gondar Airport - Azezo (HAGN)')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
