-- airports seed batch 1/11
INSERT INTO public.airports (code, name) VALUES
('VVDN', 'Da Nang International Airport - Da Nang (VVDN)'),
('VVNB', 'Noi Bai International Airport - Hanoi (Soc Son) (VVNB)'),
('VVPB', 'Phu Bai International Airport - Hue (VVPB)'),
('VVPC', 'Phu Cat Airport - Quy Nohn (VVPC)'),
('VVPK', 'Pleiku Airport - Pleiku (VVPK)'),
('VVPQ', 'Phu Quoc International Airport - Phu Quoc Island (VVPQ)'),
('VVRG', 'Rach Gia Airport - Rach Gia (VVRG)'),
('VVTH', 'Dong Tac Airport - Tuy Hoa (VVTH)'),
('VVTS', 'Tan Son Nhat International Airport - Ho Chi Minh City (VVTS)'),
('VVTX', 'Tho Xuan Airport - Thanh Hóa (VVTX)'),
('VVVD', 'Van Don International Airport - Van Don (VVVD)'),
('VVVH', 'Vinh Airport - Vinh (VVVH)'),
('NVSC', 'Sola Airport - Sola (NVSC)'),
('NVSF', 'Craig Cove Airport - Craig Cove (NVSF)'),
('NVSG', 'Longana Airport - Longana (NVSG)'),
('NVSH', 'Sara Airport - Pentecost Island (NVSH)'),
('NVSI', 'Tavie Airport - Paama Island (NVSI)'),
('NVSL', 'Lamap Airport - Lamap (NVSL)'),
('NVSM', 'Lamen Bay Airport - Lamen Bay (NVSM)'),
('NVSO', 'Lonorore Airport - Lonorore (NVSO)'),
('NVSP', 'Norsup Airport - Norsup (NVSP)'),
('NVSS', 'Santo Pekoa International Airport - Luganville (NVSS)'),
('NVST', 'Tongoa Airport - Tongoa Island (NVST)'),
('NVSV', 'Valesdir Airport - Epi Island (NVSV)'),
('NVSW', 'Walaha Airport - Walaha (NVSW)'),
('NVSZ', 'North West Santo Airport - Olpoi (NVSZ)'),
('NVVF', 'Futuna Airport - Futuna Island (NVVF)'),
('NVVV', 'Bauerfield International Airport - Port Vila (NVVV)'),
('NVVW', 'Tanna Airport - Ho Chi Minh (NVVW)'),
('NLWF', 'Pointe Vele Airport - Futuna Island (NLWF)'),
('NLWW', 'Hihifo Airport - Wallis Island (NLWW)'),
('NSFA', 'Faleolo International Airport - Apia (NSFA)'),
('BKPR', 'Priština Adem Jashari International Airport - Prishtina (BKPR)'),
('ZJYX', 'Yongxing Dao (Woody Island) Air Base - Woody Island (ZJYX)'),
('FAPP', 'Polokwane International Airport - Polokwane (FAPP)'),
('FARB', 'Richards Bay Airport - Richards Bay (FARB)'),
('FASS', 'Sishen Airport - Sishen (FASS)'),
('FAUP', 'Pierre Van Ryneveld Airport - Upington (FAUP)'),
('FAUT', 'K. D. Matanzima Airport - Mthatha (FAUT)'),
('FLKS', 'Kasama Airport - Kasama (FLKS)'),
('FLHN', 'Harry Mwanga Nkumbula International Airport - Livingstone (FLHN)'),
('FLKK', 'Kenneth Kaunda International Airport - Lusaka (FLKK)'),
('FLMF', 'Mfuwe Airport - Mfuwe (FLMF)'),
('FLND', 'Peter Zuze Air Force Base - Ndola (FLND)'),
('FLSK', 'Simon Mwansa Kapwepwe International Airport - Ndola (FLSK)'),
('FLSW', 'Solwesi Airport - Solwesi (FLSW)'),
('FVJN', 'Joshua Mqabuko Nkomo International Airport - Bulawayo (FVJN)'),
('FVFA', 'Victoria Falls International Airport - Victoria Falls (FVFA)'),
('FVRG', 'Robert Gabriel Mugabe International Airport - Harare (FVRG)'),
('OYAA', 'Aden International Airport - Aden (OYAA)'),
('OYGD', 'Al Ghaydah International Airport - Al Ghaydah (OYGD)'),
('OYRN', 'Riyan Mukalla International Airport - Riyan (OYRN)'),
('OYSN', 'Sanaa International Airport - Sanaa (OYSN)'),
('OYSQ', 'Socotra International Airport - Mori (OYSQ)'),
('OYSY', 'Seiyun Hadhramaut International Airport - Seiyun (OYSY)'),
('OYTZ', 'Ta''izz International Airport - Ta''izz (OYTZ)'),
('FMCZ', 'Dzaoudzi Pamandzi International Airport - Dzaoudzi (FMCZ)'),
('FABL', 'Bram Fischer International Airport - Bloemfontain (FABL)'),
('FACT', 'Cape Town International Airport - Cape Town (FACT)'),
('FAEL', 'King Phalo Airport - East London (FAEL)'),
('FAGG', 'George Airport - George (FAGG)'),
('FAHS', 'Hoedspruit Air Force Base Airport - Hoedspruit (FAHS)'),
('FAKM', 'Kimberley Airport - Kimberley (FAKM)'),
('FAKN', 'Kruger Mpumalanga International Airport - Mpumalanga (FAKN)'),
('FALA', 'Lanseria International Airport - Johannesburg (FALA)'),
('FALE', 'King Shaka International Airport - Durban (FALE)'),
('FAMG', 'Margate Airport - Margate (FAMG)'),
('FAMM', 'Mmabatho International Airport - Mafeking (FAMM)'),
('FAOR', 'O.R. Tambo International Airport - Johannesburg (FAOR)'),
('FAPE', 'Chief Dawid Stuurman International Airport - Gqeberha (Port Elizabeth) (FAPE)'),
('FAPH', 'Hendrik Van Eck Airport - Phalaborwa (FAPH)'),
('FAPI', 'Pietersburg Municipal Airport - Polokwane (FAPI)'),
('FAPM', 'Pietermaritzburg Airport - Pietermaritzburg (FAPM)'),
('KLWB', 'Greenbrier Valley Airport - Lewisburg (KLWB)'),
('KLWS', 'Lewiston Nez Perce County Airport - Lewiston (KLWS)'),
('KLYH', 'Lynchburg Regional Airport - Preston Glenn Field - Lynchburg (KLYH)'),
('KMAF', 'Midland International Air and Space Port - Midland (KMAF)'),
('KMBL', 'Manistee County Blacker Airport - Manistee (KMBL)'),
('KMBS', 'MBS International Airport - Freeland (KMBS)'),
('KMCE', 'Merced Regional Macready Field - Merced (KMCE)'),
('KMCI', 'Kansas City International Airport - Kansas City (KMCI)'),
('KMCK', 'McCook Ben Nelson Regional Airport - McCook (KMCK)'),
('KMCN', 'Middle Georgia Regional Airport - Macon (KMCN)'),
('KMCO', 'Orlando International Airport - Orlando (KMCO)'),
('KMCW', 'Mason City Municipal Airport - Mason City (KMCW)'),
('KMDT', 'Harrisburg International Airport - Harrisburg (KMDT)'),
('KMDW', 'Chicago Midway International Airport - Chicago (KMDW)'),
('KMEI', 'Key Field / Meridian Regional Airport - Meridian (KMEI)'),
('KMEM', 'Memphis International Airport - Memphis (KMEM)'),
('KMFE', 'McAllen Miller International Airport - McAllen (KMFE)'),
('KMFR', 'Rogue Valley International Medford Airport - Medford (KMFR)'),
('KMGM', 'Montgomery Regional (Dannelly Field) Airport - Montgomery (KMGM)'),
('KMGW', 'Morgantown Municipal Airport Walter L. (Bill) Hart Field - Morgantown (KMGW)'),
('KMHK', 'Manhattan Regional Airport - Manhattan (KMHK)'),
('KMHT', 'Manchester-Boston Regional Airport - Manchester (KMHT)'),
('KMIA', 'Miami International Airport - Miami (KMIA)'),
('KMKE', 'General Mitchell International Airport - Milwaukee (KMKE)'),
('KMKG', 'Muskegon County Airport - Muskegon (KMKG)'),
('KMKL', 'McKellar-Sipes Regional Airport - Jackson (KMKL)'),
('KMLB', 'Melbourne Orlando International Airport - Melbourne (KMLB)'),
('KMLI', 'Quad City International Airport - Moline (KMLI)'),
('KMLU', 'Monroe Regional Airport - Monroe (KMLU)'),
('KMMH', 'Mammoth Yosemite Airport - Mammoth Lakes (KMMH)'),
('KMOB', 'Mobile Regional Airport - Mobile (KMOB)'),
('KMOT', 'Minot International Airport - Minot (KMOT)'),
('KMRY', 'Monterey Peninsula Airport - Monterey (KMRY)'),
('KMSL', 'Northwest Alabama Regional Airport - Muscle Shoals (KMSL)'),
('KMSN', 'Dane County Regional Truax Field - Madison (KMSN)'),
('KMSO', 'Missoula International Airport - Missoula (KMSO)'),
('KMSP', 'Minneapolis–Saint Paul International Airport / Wold–Chamberlain Field - Minneapolis (KMSP)'),
('KMSS', 'Massena International Airport Richards Field - Massena (KMSS)'),
('KMSY', 'Louis Armstrong New Orleans International Airport - New Orleans (KMSY)'),
('KMTJ', 'Montrose Regional Airport - Montrose (KMTJ)'),
('KMTP', 'Montauk Airport - Montauk (KMTP)'),
('KMVY', 'Martha''s Vineyard Airport - Martha''s Vineyard (KMVY)'),
('KMWA', 'Veterans Airport of Southern Illinois - Marion (KMWA)'),
('KMYL', 'McCall Municipal Airport - McCall (KMYL)'),
('KMYR', 'Myrtle Beach International Airport - Myrtle Beach (KMYR)'),
('KNYL', 'Yuma International Airport / Marine Corps Air Station Yuma - Yuma (KNYL)'),
('KOAJ', 'Albert J Ellis Airport - Richlands (KOAJ)'),
('KOAK', 'San Francisco Bay Oakland International Airport - Oakland (KOAK)'),
('KOGD', 'Ogden Hinckley Airport - Ogden (KOGD)'),
('KOGS', 'Ogdensburg International Airport - Ogdensburg (KOGS)'),
('KOKC', 'Will Rogers World Airport - Oklahoma City (KOKC)'),
('KOLF', 'L M Clayton Airport - Wolf Point (KOLF)'),
('KOLM', 'Olympia Regional Airport - Olympia (KOLM)'),
('KOMA', 'Eppley Airfield - Omaha (KOMA)'),
('KONT', 'Ontario International Airport - Ontario (KONT)'),
('KOPF', 'Miami-Opa Locka Executive Airport - Miami (KOPF)'),
('KORD', 'Chicago O''Hare International Airport - Chicago (KORD)'),
('KORF', 'Norfolk International Airport - Norfolk (KORF)'),
('KORH', 'Worcester Regional Airport - Worcester (KORH)'),
('KORS', 'Orcas Island Airport - Eastsound (KORS)'),
('KOTH', 'Southwest Oregon Regional Airport - North Bend (KOTH)'),
('KOWB', 'Owensboro Daviess County Airport - Owensboro (KOWB)'),
('KPAE', 'Seattle Paine Field International Airport - Everett (KPAE)'),
('KPAH', 'Barkley Regional Airport - Paducah (KPAH)'),
('KPBG', 'Plattsburgh International Airport - Plattsburgh (KPBG)'),
('KPBI', 'Palm Beach International Airport - West Palm Beach (KPBI)'),
('KPCW', 'Carl R Keller Field - Port Clinton (KPCW)'),
('KPDK', 'DeKalb Peachtree Airport - Atlanta (KPDK)'),
('KPDT', 'Eastern Oregon Regional Airport at Pendleton - Pendleton (KPDT)'),
('KPDX', 'Portland International Airport - Portland (KPDX)'),
('KPGA', 'Page Municipal Airport - Page (KPGA)'),
('KPGD', 'Punta Gorda Airport - Punta Gorda (KPGD)'),
('KPGV', 'Pitt-Greenville Airport - Greenville (KPGV)'),
('KPHF', 'Newport News Williamsburg International Airport - Newport News (KPHF)'),
('KPHL', 'Philadelphia International Airport - Philadelphia (KPHL)'),
('KPHX', 'Phoenix Sky Harbor International Airport - Phoenix (KPHX)'),
('KPIA', 'General Wayne A. Downing Peoria International Airport - Peoria (KPIA)'),
('KPIB', 'Hattiesburg Laurel Regional Airport - Moselle (KPIB)'),
('KPIE', 'St. Petersburg Clearwater International Airport - Pinellas Park (KPIE)'),
('KPIH', 'Pocatello Regional Airport - Pocatello (KPIH)'),
('KPIR', 'Pierre Regional Airport - Pierre (KPIR)'),
('KPIT', 'Pittsburgh International Airport - Pittsburgh (KPIT)'),
('KPKB', 'Mid Ohio Valley Regional Airport - Parkersburg (Williamstown) (KPKB)'),
('KPLN', 'Pellston Regional Airport of Emmet County Airport - Pellston (KPLN)'),
('KPNS', 'Pensacola International Airport - Pensacola (KPNS)'),
('KPQI', 'Presque Isle International Airport - Presque Isle (KPQI)'),
('KPRC', 'Prescott International Airport - Ernest A. Love Field - Prescott (KPRC)'),
('KPSC', 'Tri Cities Airport - Pasco (KPSC)'),
('KPSM', 'Portsmouth International at Pease Airport - Portsmouth (KPSM)'),
('KPSP', 'Palm Springs International Airport - Palm Springs (KPSP)'),
('KPUB', 'Pueblo Memorial Airport - Pueblo (KPUB)'),
('KPUW', 'Pullman-Moscow Regional Airport - Pullman (KPUW)'),
('KPVD', 'Theodore Francis Green State Airport - Warwick (KPVD)'),
('KPVU', 'Provo-Utah Lake International Airport - Provo (KPVU)'),
('KPWM', 'Portland International Jetport - Portland (KPWM)'),
('KRAP', 'Rapid City Regional Airport - Rapid City (KRAP)'),
('KRDD', 'Redding Municipal Airport - Redding (KRDD)'),
('KRDM', 'Roberts Field - Redmond (KRDM)'),
('KRDU', 'Raleigh Durham International Airport - Raleigh/Durham (KRDU)'),
('KRFD', 'Chicago Rockford International Airport - Chicago/Rockford (KRFD)'),
('KRHI', 'Rhinelander Oneida County Airport - Rhinelander (KRHI)'),
('KRIC', 'Richmond International Airport - Richmond (KRIC)'),
('KRIW', 'Central Wyoming Regional Airport - Riverton (KRIW)'),
('KRKD', 'Knox County Regional Airport - Rockland (KRKD)'),
('KRKS', 'Southwest Wyoming Regional Airport - Rock Springs (KRKS)'),
('KRNO', 'Reno Tahoe International Airport - Reno (KRNO)'),
('KROA', 'Roanoke–Blacksburg Regional Airport - Roanoke (KROA)'),
('KROC', 'Frederick Douglass Greater Rochester International Airport - Rochester (KROC)'),
('KROW', 'Roswell Air Center Airport - Roswell (KROW)'),
('KRST', 'Rochester International Airport - Rochester (KRST)'),
('KRSW', 'Southwest Florida International Airport - Fort Myers (KRSW)'),
('KRUT', 'Rutland - Southern Vermont Regional Airport - Rutland (KRUT)'),
('KSAF', 'Santa Fe Municipal Airport - Santa Fe (KSAF)'),
('KSAN', 'San Diego International Airport - San Diego (KSAN)'),
('KSAT', 'San Antonio International Airport - San Antonio (KSAT)'),
('KSAV', 'Savannah Hilton Head International Airport - Savannah (KSAV)'),
('KSAW', 'Marquette/Sawyer International Airport - Gwinn (KSAW)'),
('KSBA', 'Santa Barbara Municipal Airport - Santa Barbara (KSBA)'),
('KSBD', 'San Bernardino International Airport - San Bernardino (KSBD)'),
('KSBN', 'South Bend Regional Airport - South Bend (KSBN)'),
('KSBP', 'San Luis County Regional Airport - San Luis Obispo (KSBP)'),
('KSBY', 'Salisbury Ocean City Wicomico Regional Airport - Salisbury (KSBY)'),
('KSCK', 'Stockton Metropolitan Airport - Stockton (KSCK)'),
('KSDF', 'Louisville Muhammad Ali International Airport - Louisville (KSDF)'),
('KSDY', 'Sidney - Richland Regional Airport - Sidney (KSDY)'),
('KSEA', 'Seattle–Tacoma International Airport - Seattle (KSEA)'),
('KSFB', 'Orlando Sanford International Airport - Orlando (KSFB)'),
('KSFO', 'San Francisco International Airport - San Francisco (KSFO)'),
('KSGF', 'Springfield Branson National Airport - Springfield (KSGF)'),
('KSGJ', 'Northeast Florida Regional Airport - St Augustine (KSGJ)'),
('KSGU', 'St George Regional Airport - St George (KSGU)'),
('KSHD', 'Shenandoah Valley Regional Airport - Weyers Cave (KSHD)'),
('KSHR', 'Sheridan County Airport - Sheridan (KSHR)'),
('KSHV', 'Shreveport Regional Airport - Shreveport (KSHV)'),
('PACE', 'Central Airport - Central (PACE)'),
('PACI', 'Chalkyitsik Airport - Chalkyitsik (PACI)'),
('PACK', 'Chefornak Airport - Chefornak (PACK)'),
('PACM', 'Scammon Bay Airport - Scammon Bay (PACM)'),
('PACR', 'Circle City (New) Airport - Circle (PACR)'),
('PACV', 'Merle K (Mudhole) Smith Airport - Cordova (PACV)'),
('PACY', 'Yakataga Airport - Yakataga (PACY)'),
('PADE', 'Deering Airport - Deering (PADE)'),
('PADK', 'Adak Airport - Adak (PADK)'),
('PADL', 'Dillingham Airport - Dillingham (PADL)'),
('PADM', 'Marshall Don Hunter Sr Airport - Marshall (PADM)'),
('PADQ', 'Kodiak Airport - Kodiak (PADQ)'),
('PADU', 'Tom Madsen (Dutch Harbor) Airport - Unalaska (PADU)'),
('PADY', 'Kongiganak Airport - Kongiganak (PADY)'),
('PAEE', 'Eek Airport - Eek (PAEE)'),
('PAEG', 'Eagle Airport - Eagle (PAEG)'),
('PAEM', 'Emmonak Airport - Emmonak (PAEM)'),
('PAEN', 'Kenai Municipal Airport - Kenai (PAEN)'),
('PAEW', 'Mertarvik Airport - Mertarvik (PAEW)'),
('PAFA', 'Fairbanks International Airport - Fairbanks (PAFA)'),
('PAFM', 'Ambler Airport - Ambler (PAFM)'),
('PAFS', 'Nikolai Airport - Nikolai (PAFS)'),
('PAGA', 'Edward G. Pitka Sr Airport - Galena (PAGA)'),
('PAGG', 'Kwigillingok Airport - Kwigillingok (PAGG)'),
('PAGH', 'Shungnak Airport - Shungnak (PAGH)'),
('PAGK', 'Gulkana Airport - Gulkana (PAGK)'),
('PAGL', 'Golovin Airport - Golovin (PAGL)'),
('PAGM', 'Gambell Airport - Gambell (PAGM)'),
('PAGS', 'Gustavus Airport - Gustavus (PAGS)'),
('PAGT', 'Nightmute Airport - Nightmute (PAGT)'),
('PAGY', 'Skagway Airport - Skagway (PAGY)'),
('PAHC', 'Holy Cross Airport - Holy Cross (PAHC)'),
('PAHL', 'Huslia Airport - Huslia (PAHL)'),
('PAHN', 'Haines Airport - Haines (PAHN)'),
('PAHO', 'Homer Airport - Homer (PAHO)'),
('PAHP', 'Hooper Bay Airport - Hooper Bay (PAHP)'),
('PAHU', 'Hughes Airport - Hughes (PAHU)'),
('PAHV', 'Healy River Airport - Healy (PAHV)'),
('PAIG', 'Igiugig Airport - Igiugig (PAIG)'),
('PAII', 'Egegik Airport - Egegik (PAII)'),
('PAIK', 'Bob Baker Memorial Airport - Kiana (PAIK)'),
('PAIL', 'Iliamna Airport - Iliamna (PAIL)'),
('PAIM', 'Indian Mountain LRRS Airport - Utopia Creek (PAIM)'),
('PAIW', 'Wales Airport - Wales (PAIW)'),
('PAJN', 'Juneau International Airport - Juneau (PAJN)'),
('PAJZ', 'Koliganek Airport - Koliganek (PAJZ)'),
('PAKF', 'False Pass Airport - False Pass (PAKF)'),
('PAKH', 'Akhiok Airport - Akhiok (PAKH)'),
('PAKI', 'Kipnuk Airport - Kipnuk (PAKI)'),
('PAKK', 'Koyuk Alfred Adams Airport - Koyuk (PAKK)'),
('PAKN', 'King Salmon Airport - King Salmon (PAKN)'),
('PAKO', 'Nikolski Air Station - Nikolski (PAKO)'),
('PAKP', 'Anaktuvuk Pass Airport - Anaktuvuk Pass (PAKP)'),
('PAKT', 'Ketchikan International Airport - Ketchikan (PAKT)'),
('PAKV', 'Kaltag Airport - Kaltag (PAKV)'),
('PAKW', 'Klawock Airport - Klawock (PAKW)'),
('PAKY', 'Karluk Airport - Karluk (PAKY)'),
('PALB', 'Larsen Bay Airport - Larsen Bay (PALB)'),
('PALG', 'Kalskag Airport - Kalskag (PALG)'),
('PALJ', 'Port Alsworth Airport - Port Alsworth (PALJ)'),
('PALU', 'Cape Lisburne LRRS Airport - Cape Lisburne (PALU)'),
('PAMB', 'Manokotak Airport - Manokotak (PAMB)'),
('PAMC', 'McGrath Airport - McGrath (PAMC)'),
('PAMH', 'Minchumina Airport - Minchumina (PAMH)'),
('PAMK', 'St Michael Airport - St Michael (PAMK)'),
('PAML', 'Manley Hot Springs Airport - Manley Hot Springs (PAML)'),
('PAMO', 'Mountain Village Airport - Mountain Village (PAMO)'),
('PAMR', 'Merrill Field - Anchorage (PAMR)'),
('PAMY', 'Mekoryuk Airport - Mekoryuk (PAMY)'),
('PANA', 'Napakiak Airport - Napakiak (PANA)'),
('PANC', 'Ted Stevens Anchorage International Airport - Anchorage (PANC)'),
('PANI', 'Aniak Airport - Aniak (PANI)'),
('PANU', 'Nulato Airport - Nulato (PANU)'),
('PANV', 'Anvik Airport - Anvik (PANV)'),
('PANW', 'New Stuyahok Airport - New Stuyahok (PANW)'),
('PAOB', 'Kobuk Airport - Kobuk (PAOB)'),
('PAOH', 'Hoonah Airport - Hoonah (PAOH)'),
('PAOM', 'Nome Airport - Nome (PAOM)'),
('PAOO', 'Toksook Bay Airport - Toksook Bay (PAOO)'),
('PAOR', 'Northway Airport - Northway (PAOR)'),
('PAOT', 'Ralph Wien Memorial Airport - Kotzebue (PAOT)'),
('PAOU', 'Nelson Lagoon Airport - Nelson Lagoon (PAOU)'),
('PAPB', 'St George Airport - St George (PAPB)'),
('PAPE', 'Perryville Airport - Perryville (PAPE)'),
('PAPG', 'Petersburg James A Johnson Airport - Petersburg (PAPG)'),
('PAPH', 'Port Heiden Airport - Port Heiden (PAPH)'),
('PAPK', 'Napaskiak Airport - Napaskiak (PAPK)'),
('PAPM', 'Platinum Airport - Platinum (PAPM)'),
('PAPN', 'Pilot Point Airport - Pilot Point (PAPN)'),
('PAPO', 'Point Hope Airport - Point Hope (PAPO)'),
('PAQH', 'Quinhagak Airport - Quinhagak (PAQH)'),
('PAQT', 'Nuiqsut Airport - Nuiqsut (PAQT)'),
('PARC', 'Arctic Village Airport - Arctic Village (PARC)'),
('PARS', 'Russian Mission Airport - Russian Mission (PARS)'),
('PARY', 'Ruby Airport - Ruby (PARY)'),
('PASA', 'Savoonga Airport - Savoonga (PASA)'),
('PASC', 'Deadhorse Airport - Deadhorse (PASC)'),
('PASD', 'Sand Point Airport - Sand Point (PASD)'),
('PASH', 'Shishmaref Airport - Shishmaref (PASH)'),
('PASI', 'Sitka Rocky Gutierrez Airport - Sitka (PASI)'),
('PASK', 'Selawik Airport - Selawik (PASK)'),
('PASL', 'Sleetmute Airport - Sleetmute (PASL)'),
('PASM', 'St Mary''s Airport - St Mary''s (PASM)'),
('PASN', 'St Paul Island Airport - St Paul Island (PASN)'),
('PASO', 'Seldovia Airport - Seldovia (PASO)'),
('PATA', 'Ralph M Calhoun Memorial Airport - Tanana (PATA)'),
('PATC', 'Tin City Long Range Radar Station Airport - Tin City (PATC)'),
('PATE', 'Teller Airport - Teller (PATE)'),
('PATG', 'Togiak Airport - Togiak Village (PATG)'),
('PATQ', 'Atqasuk Edward Burnell Sr Memorial Airport - Atqasuk (PATQ)'),
('PAUK', 'Alakanuk Airport - Alakanuk (PAUK)'),
('PAUN', 'Unalakleet Airport - Unalakleet (PAUN)'),
('PAUT', 'Akutan Airport - Akutan (PAUT)'),
('PAVA', 'Chevak Airport - Chevak (PAVA)'),
('PAVC', 'King Cove Airport - King Cove (PAVC)'),
('PAVD', 'Valdez Pioneer Field - Valdez (PAVD)'),
('PAVE', 'Venetie Airport - Venetie (PAVE)'),
('PAVL', 'Kivalina Airport - Kivalina (PAVL)'),
('PAWB', 'Beaver Airport - Beaver (PAWB)'),
('PAWG', 'Wrangell Airport - Wrangell (PAWG)'),
('PAWI', 'Wainwright Airport - Wainwright (PAWI)'),
('PAWM', 'White Mountain Airport - White Mountain (PAWM)'),
('PAWN', 'Noatak Airport - Noatak (PAWN)'),
('PAYA', 'Yakutat Airport - Yakutat (PAYA)'),
('PFAK', 'Akiak Airport - Akiak (PFAK)'),
('PFAL', 'Allakaket Airport - Allakaket (PFAL)'),
('PFCB', 'Chenega Bay Airport - Chenega (PFCB)'),
('PFCL', 'Clarks Point Airport - Clarks Point (PFCL)'),
('PFEL', 'Elim Airport - Elim (PFEL)'),
('PFKA', 'Kasigluk Airport - Kasigluk (PFKA)'),
('PFKK', 'Kokhanok Airport - Kokhanok (PFKK)'),
('PFKO', 'Kotlik Airport - Kotlik (PFKO)'),
('PFKT', 'Brevig Mission Airport - Brevig Mission (PFKT)'),
('PFKU', 'Koyukuk Airport - Koyukuk (PFKU)'),
('PFKW', 'Kwethluk Airport - Kwethluk (PFKW)'),
('PFNO', 'Robert (Bob) Curtis Memorial Airport - Noorvik (PFNO)'),
('PFSH', 'Shaktoolik Airport - Shaktoolik (PFSH)'),
('PFTO', 'Tok Junction Airport - Tok (PFTO)'),
('PFWS', 'South Naknek Number 2 Airport - South Naknek (PFWS)'),
('PFYU', 'Fort Yukon Airport - Fort Yukon (PFYU)'),
('KPGM', 'Port Graham Airport - Port Graham (KPGM)'),
('PHHN', 'Hana Airport - Hana (PHHN)'),
('PHJH', 'Kapalua Airport - Lahaina (PHJH)'),
('PHKO', 'Ellison Onizuka Kona International Airport at Keahole - Kailua-Kona (PHKO)'),
('PHLI', 'Lihue Airport - Lihue (PHLI)'),
('PHLU', 'Kalaupapa Airport - Kalaupapa (PHLU)'),
('PHMK', 'Molokai Airport - Kaunakakai (PHMK)'),
('PHMU', 'Waimea Kohala Airport - Waimea (Kamuela) (PHMU)'),
('PHNL', 'Daniel K Inouye International Airport - Honolulu, Oahu (PHNL)'),
('PHNY', 'Lanai Airport - Lanai City (PHNY)'),
('PHOG', 'Kahului International Airport - Kahului (PHOG)'),
('PHTO', 'Hilo International Airport - Hilo (PHTO)'),
('PPIZ', 'Point Lay LRRS Airport - Point Lay (PPIZ)'),
('KRDV', 'Red Devil Airport - Red Devil (KRDV)'),
('PFMP', 'Rampart Airport - Rampart (PFMP)'),
('S31', 'Lopez Island Airport - Lopez (S31)'),
('KSRV', 'Stony River 2 Airport - Stony River (KSRV)'),
('PFSV', 'Stevens Village Airport - Stevens Village (PFSV)'),
('KSXP', 'Nunam Iqua Airport - Nunam Iqua (KSXP)'),
('PPCT', 'Takotna Airport - Takotna (PPCT)'),
('PALT', 'Tuluksak Airport - Tuluksak (PALT)'),
('WA09', 'Roche Harbor Airport - Roche Harbor (WA09)'),
('WN07', 'Decatur Shores Airport - Decatur (WN07)'),
('PFZK', 'Akiachak Airport - Akiachak (PFZK)'),
('KZ91', 'Birch Creek Airport - Birch Creek (KZ91)'),
('SULS', 'Capitan Corbeta CA Curbelo International Airport - Punta del Este (SULS)'),
('SUMU', 'Carrasco General Cesáreo L. Berisso International Airport - Ciudad de la Costa (SUMU)'),
('SUPE', 'El Jagüel / Punta del Este Airport - Maldonado (SUPE)'),
('UTFN', 'Namangan Airport - Namangan (UTFN)'),
('UTKA', 'Andizhan Airport - Andizhan (UTKA)'),
('UTFF', 'Fergana International Airport - Fergana (UTFF)'),
('UTNN', 'Nukus Airport - Nukus (UTNN)'),
('UTNU', 'Urgench Airport - Urgench (UTNU)'),
('UTSA', 'Navoi Airport - Navoi (UTSA)'),
('UTSB', 'Bukhara International Airport - Bukhara (UTSB)'),
('UTSK', 'Karshi Airport - Karshi (UTSK)'),
('UTSN', 'Sugraly Airport - Zarafshan (UTSN)'),
('UTSS', 'Samarkand Airport - Samarkand (UTSS)'),
('UTST', 'Termez Airport - Termez (UTST)'),
('UTTP', 'Tashkent East Airport - Tashkent (UTTP)'),
('UTTT', 'Tashkent International Airport - Tashkent (UTTT)'),
('TVSA', 'Argyle International Airport - Kingstown (TVSA)'),
('TVSB', 'J F Mitchell Airport - Bequia (TVSB)'),
('TVSC', 'Canouan Airport - Canouan (TVSC)'),
('TVSM', 'Mustique Airport - Lovell (TVSM)'),
('TVSU', 'Union Island International Airport - Union Island (TVSU)'),
('SVBC', 'General José Antonio Anzoategui International Airport - Barcelona (SVBC)'),
('SVBI', 'Barinas Airport - Barinas (SVBI)'),
('SVBM', 'Barquisimeto International Airport - Barquisimeto (SVBM)'),
('SVCN', 'Canaima Airport - Canaima (SVCN)'),
('SVCP', 'General Francisco Bermúdez Airport - Carúpano (SVCP)'),
('SVCR', 'José Leonardo Chirinos Airport - Coro (SVCR)'),
('SVCU', 'Cumaná (Antonio José de Sucre) Airport - Cumaná (SVCU)')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
