-- airports seed batch 7/11
INSERT INTO public.airports (code, name) VALUES
('CYPM', 'Pikangikum Airport - Pikangikum (CYPM)'),
('CYPN', 'Port-Menier Airport - Port-Menier (CYPN)'),
('CYPO', 'Peawanuck Airport - Peawanuck (CYPO)'),
('CYPR', 'Prince Rupert Airport - Prince Rupert (CYPR)'),
('CYPT', 'Pelee Island Airport - Pelee Island (CYPT)'),
('CYPW', 'Powell River Airport - Powell River (CYPW)'),
('CYPX', 'Puvirnituq Airport - Puvirnituq (CYPX)'),
('CYPY', 'Fort Chipewyan Airport - Fort Chipewyan (CYPY)'),
('CYPZ', 'Burns Lake Airport - Burns Lake (CYPZ)'),
('CYQA', 'Muskoka Airport - Gravenhurst (CYQA)'),
('CYQB', 'Quebec Jean Lesage International Airport - Quebec (CYQB)'),
('CYQD', 'The Pas Airport - The Pas (CYQD)'),
('CYQG', 'Windsor Airport - Windsor (CYQG)'),
('CYQH', 'Watson Lake Airport - Watson Lake (CYQH)'),
('CYQK', 'Kenora Airport - Kenora (CYQK)'),
('CYQL', 'Lethbridge County Airport - Lethbridge (CYQL)'),
('CYQM', 'Greater Moncton Roméo LeBlanc International Airport - Moncton (CYQM)'),
('CYQN', 'Nakina Airport - Nakina (CYQN)'),
('CYQQ', 'Comox Valley Airport / CFB Comox - Comox (CYQQ)'),
('CYQR', 'Regina International Airport - Regina (CYQR)'),
('CYQT', 'Thunder Bay Airport - Thunder Bay (CYQT)'),
('CYQU', 'Grande Prairie Airport - Grande Prairie (CYQU)'),
('CYQX', 'Gander International Airport / CFB Gander - Gander (CYQX)'),
('CYQY', 'Sydney / J.A. Douglas McCurdy Airport - Sydney (CYQY)'),
('CYQZ', 'Quesnel Airport - Quesnel (CYQZ)'),
('CYRA', 'Rae Lakes Airport - Gameti (CYRA)'),
('CYRB', 'Resolute Bay Airport - Resolute Bay (CYRB)'),
('CYRJ', 'Roberval Airport - Roberval (CYRJ)'),
('CYRL', 'Red Lake Airport - Red Lake (CYRL)'),
('CYRS', 'Red Sucker Lake Airport - Red Sucker Lake (CYRS)'),
('CYRT', 'Rankin Inlet Airport - Rankin Inlet (CYRT)'),
('CYSB', 'Sudbury Airport - Sudbury (CYSB)'),
('CYSF', 'Stony Rapids Airport - Stony Rapids (CYSF)'),
('CYSJ', 'Saint John Airport - Saint John (CYSJ)'),
('CYSK', 'Sanikiluaq Airport - Sanikiluaq (CYSK)'),
('CYSM', 'Fort Smith Airport - Fort Smith (CYSM)'),
('CYSN', 'Niagara District Airport - Niagara-on-the-Lake (CYSN)'),
('CYSQ', 'Atlin Airport - Atlin (CYSQ)'),
('CYST', 'St. Theresa Point Airport - St. Theresa Point (CYST)'),
('CYSY', 'Sachs Harbour (David Nasogaluak Jr. Saaryuaq) Airport - Sachs Harbour (CYSY)'),
('CYTE', 'Cape Dorset Airport - Kinngait (CYTE)'),
('CYTH', 'Thompson Airport - Thompson (CYTH)'),
('CYTL', 'Big Trout Lake Airport - Big Trout Lake (CYTL)'),
('CYTQ', 'Tasiujaq Airport - Tasiujaq (CYTQ)'),
('CYTS', 'Timmins/Victor M. Power - Timmins (CYTS)'),
('CYTZ', 'Billy Bishop Toronto City Centre Airport - Toronto (CYTZ)'),
('CYUL', 'Montreal / Pierre Elliott Trudeau International Airport - Montréal (CYUL)'),
('CYUT', 'Naujaat Airport - Repulse Bay (CYUT)'),
('CYUX', 'Hall Beach Airport - Sanirajak (CYUX)'),
('CYUY', 'Rouyn Noranda Airport - Rouyn-Noranda (CYUY)'),
('CYVB', 'Bonaventure Airport - Bonaventure (CYVB)'),
('CYVC', 'La Ronge Airport - La Ronge (CYVC)'),
('CYVL', 'Tommy Kochon Airport - Colville Lake (CYVL)'),
('CYVM', 'Qikiqtarjuaq Airport - Qikiqtarjuaq (CYVM)'),
('CYVO', 'Val-d''Or Airport - Val-d''Or (CYVO)'),
('CYVP', 'Kuujjuaq Airport - Kuujjuaq (CYVP)'),
('CYVQ', 'Norman Wells Airport - Norman Wells (CYVQ)'),
('CYVR', 'Vancouver International Airport - Vancouver (CYVR)'),
('CYVV', 'Wiarton Airport - Wiarton (CYVV)'),
('CYVZ', 'Deer Lake Airport - Deer Lake (CYVZ)'),
('CYWE', 'Wekweeti Airport  - Wekweeti (CYWE)'),
('CYWG', 'Winnipeg / James Armstrong Richardson International Airport - Winnipeg (CYWG)'),
('CYWJ', 'Déline Airport - Déline (CYWJ)'),
('CYWK', 'Wabush Airport - Wabush (CYWK)'),
('CYWL', 'Williams Lake Airport - Williams Lake (CYWL)'),
('CYWP', 'Webequie Airport - Webequie (CYWP)'),
('CYXC', 'Cranbrook/Canadian Rockies International Airport - Cranbrook (CYXC)'),
('CYXE', 'Saskatoon John G. Diefenbaker International Airport - Saskatoon (CYXE)'),
('CYXH', 'Medicine Hat Regional Airport - Medicine Hat (CYXH)'),
('CYXJ', 'Fort St John / North Peace Regional Airport - Fort Saint John (CYXJ)'),
('CYXK', 'Rimouski Airport - Rimouski (CYXK)'),
('CYXL', 'Sioux Lookout Airport - Sioux Lookout (CYXL)'),
('CYXN', 'Whale Cove Airport - Whale Cove (CYXN)'),
('CYXP', 'Pangnirtung Airport - Pangnirtung (CYXP)'),
('CYXS', 'Prince George Airport - Prince George (CYXS)'),
('CYXT', 'Northwest Regional Airport Terrace-Kitimat - Terrace (CYXT)'),
('CYXU', 'London Airport - London (CYXU)'),
('CYXX', 'Abbotsford International Airport - Abbotsford (CYXX)'),
('CYXY', 'Whitehorse / Erik Nielsen International Airport - Whitehorse (CYXY)'),
('CYYB', 'North Bay Jack Garland Airport - North Bay (CYYB)'),
('CYYC', 'Calgary International Airport - Calgary (CYYC)'),
('CYYD', 'Smithers Airport - Smithers (CYYD)'),
('CYYE', 'Fort Nelson Airport - Fort Nelson (CYYE)'),
('CYYF', 'Penticton Airport - Penticton (CYYF)'),
('CYYG', 'Charlottetown Airport - Charlottetown (CYYG)'),
('CYYH', 'Taloyoak Airport - Taloyoak (CYYH)'),
('CYYJ', 'Victoria International Airport - Victoria (CYYJ)'),
('CYYL', 'Lynn Lake Airport - Lynn Lake (CYYL)'),
('CYYQ', 'Churchill Airport - Churchill (CYYQ)'),
('CYYR', 'Goose Bay Airport - Goose Bay (CYYR)'),
('CYYT', 'St. John''s International Airport - St. John''s (CYYT)'),
('CYYY', 'Mont Joli Airport - Mont-Joli (CYYY)'),
('CYYZ', 'Toronto Lester B. Pearson International Airport - Toronto (CYYZ)'),
('CYZF', 'Yellowknife International Airport - Yellowknife (CYZF)'),
('CYZG', 'Salluit Airport - Salluit (CYZG)'),
('CYZP', 'Sandspit Airport - Sandspit (CYZP)'),
('CYZS', 'Coral Harbour Airport - Coral Harbour (CYZS)'),
('CYZT', 'Port Hardy Airport - Port Hardy (CYZT)'),
('CYZU', 'Whitecourt Airport - Whitecourt (CYZU)'),
('CYZV', 'Sept-Îles Airport - Sept-Îles (CYZV)'),
('CYZY', 'Mackenzie Airport - Mackenzie (CYZY)'),
('CZBD', 'Ilford Airport - Ilford (CZBD)'),
('CZBF', 'Bathurst Airport - South Tetagouche (CZBF)'),
('CZEM', 'Eastmain River Airport - Eastmain River (CZEM)'),
('CZFD', 'Fond-du-Lac Airport - Fond-du-Lac (CZFD)'),
('CZFG', 'Pukatawagan Airport - Pukatawagan (CZFG)'),
('CZFM', 'Fort Mcpherson Airport - Fort Mcpherson (CZFM)'),
('CZFN', 'Tulita Airport - Tulita (CZFN)'),
('CZGI', 'Gods River Airport - Gods River (CZGI)'),
('CZKE', 'Kashechewan Airport - Kashechewan (CZKE)'),
('CZMD', 'Muskrat Dam Airport - Muskrat Dam (CZMD)'),
('CZMT', 'Masset Airport - Masset (CZMT)'),
('CZPB', 'Sachigo Lake Airport - Sachigo Lake (CZPB)'),
('CZRJ', 'Round Lake (Weagamow Lake) Airport - Round Lake (CZRJ)'),
('CZSJ', 'Sandy Lake Airport - Sandy Lake (CZSJ)'),
('CZSN', 'South Indian Lake Airport - South Indian Lake (CZSN)'),
('CZTA', 'Bloodvein River Airport - Bloodvein River (CZTA)'),
('CZTM', 'Shamattawa Airport - Shamattawa (CZTM)'),
('CZUM', 'Churchill Falls Airport - Churchill Falls (CZUM)'),
('CZWH', 'Lac Brochet Airport - Lac Brochet (CZWH)'),
('CZWL', 'Wollaston Lake Airport - Wollaston Lake (CZWL)'),
('YPCC', 'Cocos (Keeling) Islands Airport - West Island (YPCC)'),
('FZAA', 'Ndjili International Airport - Kinshasa (FZAA)'),
('FZBA', 'Inongo Airport - Inongo (FZBA)'),
('FZBO', 'Bandundu Airport - Bandundu (FZBO)'),
('FZCA', 'Kikwit Airport - Kikwit (FZCA)'),
('FZEA', 'Mbandaka Airport - Mbandaka (FZEA)'),
('FZFD', 'Gbadolite Airport - Gbadolite (FZFD)'),
('FZFK', 'Gemena Airport - Gemena (FZFK)'),
('FZGN', 'Boende Airport - Boende (FZGN)'),
('FZIC', 'Bangoka International Airport - Kisangani (FZIC)'),
('FZJH', 'Matari Airport - Isiro (FZJH)'),
('FZKA', 'Bunia Airport - Bunia (FZKA)'),
('FZNA', 'Goma International Airport - Goma (FZNA)'),
('FZOA', 'Kindu Airport - Kindu (FZOA)'),
('FZQA', 'Lubumbashi International Airport - Lubumbashi (FZQA)'),
('FZQM', 'Kolwezi Airport - Kolwezi (FZQM)'),
('FZRF', 'Kalemie Airport - Kalemie (FZRF)'),
('FZSB', 'Kamina City Airport - Kamina (FZSB)'),
('FZUA', 'Kananga Airport - Kananga (FZUA)'),
('FZVJ', 'Tshumbe Airport - Tshumbe (FZVJ)'),
('FZVS', 'Ilebo Airport - Ilebo (FZVS)'),
('FZWA', 'Mbuji Mayi Airport - Mbuji Mayi (FZWA)'),
('FEFF', 'Bangui M''Poko International Airport - Bangui (FEFF)'),
('FCBB', 'Maya-Maya Airport - Brazzaville (FCBB)'),
('FCPP', 'Antonio Agostinho-Neto International Airport - Pointe Noire (FCPP)'),
('LSGG', 'Geneva Cointrin International Airport - Geneva (LSGG)'),
('LSZA', 'Lugano Airport - Agno (LSZA)'),
('LSZB', 'Bern Airport - Bern (LSZB)'),
('LSZH', 'Zürich Airport - Zurich (LSZH)'),
('LSZR', 'Sankt Gallen Altenrhein Airport - St. Gallen (LSZR)'),
('DIAP', 'Félix-Houphouët-Boigny International Airport - Abidjan (DIAP)'),
('DIBK', 'Bouaké Airport - Bouaké (DIBK)'),
('DIKO', 'Korhogo Airport - Korhogo (DIKO)'),
('DISP', 'San Pedro Airport - San Pedro (DISP)'),
('NCAI', 'Aitutaki Airport - Aitutaki (NCAI)'),
('NCAT', 'Enua Airport - Atiu Island (NCAT)'),
('NCMH', 'Manihiki Island Airport - Manihiki Island (NCMH)'),
('NCMK', 'Mauke Airport - Mauke Island (NCMK)'),
('NCMR', 'Mitiaro Island Airport - Mitiaro Island (NCMR)'),
('NCRG', 'Rarotonga International Airport - Avarua (NCRG)'),
('SCAR', 'Chacalluta Airport - Arica (SCAR)'),
('SCAT', 'Desierto de Atacama Airport - Copiapo (SCAT)'),
('SCBA', 'Balmaceda Airport - Balmaceda (SCBA)'),
('SCCF', 'El Loa Airport - Calama (SCCF)'),
('SCCI', 'President Carlos Ibanez del Campo International Airport - Punta Arenas (SCCI)'),
('SCDA', 'Diego Aracena Airport - Iquique (SCDA)'),
('SCEL', 'Comodoro Arturo Merino Benítez International Airport - Santiago (SCEL)'),
('SCES', 'Ricardo García Posada Airport - El Salvador (SCES)'),
('SCFA', 'Andrés Sabella Gálvez International Airport - Antofagasta (SCFA)'),
('SCIE', 'Carriel Sur Airport - Concepcion (SCIE)'),
('SCIP', 'Mataveri Airport - Isla De Pascua (SCIP)'),
('SCJO', 'Canal Bajo Carlos Hott Siebert Airport - Osorno (SCJO)'),
('SCNT', 'Lieutenant Julio Gallardo Airport - Puerto Natales (SCNT)'),
('SCPC', 'Pucón Airport - Pucon (SCPC)'),
('SCPQ', 'Mocopulli Airport - Dalcahue (SCPQ)'),
('SCQP', 'La Araucanía Airport - Temuco (SCQP)'),
('SCSE', 'La Florida Airport - La Serena-Coquimbo (SCSE)'),
('CTU5', 'La Tabatière Airport - La Tabatière (CTU5)'),
('CYAB', 'Arctic Bay Airport - Arctic Bay (CYAB)'),
('CYAC', 'Cat Lake Airport - Cat Lake (CYAC)'),
('CYAG', 'Fort Frances Municipal Airport - Fort Frances (CYAG)'),
('CYAL', 'Alert Bay Airport - Alert Bay (CYAL)'),
('CYAM', 'Sault Ste Marie Airport - Sault Ste Marie (CYAM)'),
('CYAQ', 'Kasabonika Airport - Kasabonika (CYAQ)'),
('CYAS', 'Kangirsuk Airport - Kangirsuk (CYAS)'),
('CYAT', 'Attawapiskat Airport - Attawapiskat (CYAT)'),
('CYAV', 'Winnipeg / St. Andrews Airport - Winnipeg/Saint Andrews (CYAV)'),
('CYAX', 'Lac Du Bonnet Airport - Lac Du Bonnet (CYAX)'),
('CYAY', 'St. Anthony Airport - St. Anthony (CYAY)'),
('CYAZ', 'Tofino / Long Beach Airport - Tofino (CYAZ)'),
('CYBB', 'Kugaaruk Airport - Kugaaruk (CYBB)'),
('CYBC', 'Baie-Comeau Airport - Baie-Comeau (CYBC)'),
('CYBD', 'Bella Coola Airport - Bella Coola (CYBD)'),
('CYBE', 'Uranium City Airport - Uranium City (CYBE)'),
('CYBF', 'Bonnyville Airport - Bonnyville (CYBF)'),
('CYBG', 'CFB Bagotville / Saguenay-Bagotville Airport - La Baie (CYBG)'),
('CYBK', 'Baker Lake Airport - Baker Lake (CYBK)'),
('CYBL', 'Campbell River Airport - Campbell River (CYBL)'),
('CYBQ', 'Tadoule Lake Airport - Tadoule Lake (CYBQ)'),
('CYBR', 'Brandon Municipal Airport - Brandon (CYBR)'),
('CYBT', 'Brochet Airport - Brochet (CYBT)'),
('CYBV', 'Berens River Airport - Berens River (CYBV)'),
('CYBX', 'Lourdes-de-Blanc-Sablon Airport - Blanc-Sablon (CYBX)'),
('CYCA', 'Cartwright Airport - Cartwright (CYCA)'),
('CYCB', 'Cambridge Bay Airport - Cambridge Bay (CYCB)'),
('CYCD', 'Nanaimo Airport - Nanaimo (CYCD)'),
('CYCG', 'Castlegar/West Kootenay Regional Airport - Castlegar (CYCG)'),
('CYCL', 'Charlo Airport - Charlo (CYCL)'),
('CYCO', 'Kugluktuk Airport - Kugluktuk (CYCO)'),
('CYCR', 'Cross Lake (Charlie Sinclair Memorial) Airport - Cross Lake (CYCR)'),
('CYCS', 'Chesterfield Inlet Airport - Chesterfield Inlet (CYCS)'),
('CYCY', 'Clyde River Airport - Clyde River (CYCY)'),
('CYDA', 'Dawson City Airport - Dawson City (CYDA)'),
('CYDF', 'Deer Lake Airport - Deer Lake (CYDF)'),
('CYDL', 'Dease Lake Airport - Dease Lake (CYDL)'),
('CYDN', 'Dauphin Barker Airport - Dauphin (CYDN)'),
('CYDP', 'Nain Airport - Nain (CYDP)'),
('CYEG', 'Edmonton International Airport - Edmonton (CYEG)'),
('CYEK', 'Arviat Airport - Arviat (CYEK)'),
('CYER', 'Fort Severn Airport - Fort Severn (CYER)'),
('CYEV', 'Inuvik Mike Zubko Airport - Inuvik (CYEV)'),
('CYFA', 'Fort Albany Airport - Fort Albany (CYFA)'),
('CYFB', 'Iqaluit Airport - Iqaluit (CYFB)'),
('CYFC', 'Fredericton Airport - Fredericton (CYFC)'),
('CYFH', 'Fort Hope Airport - Fort Hope (CYFH)'),
('CYFO', 'Flin Flon Airport - Flin Flon (CYFO)'),
('CYFS', 'Fort Simpson Airport - Fort Simpson (CYFS)'),
('CYFT', 'Makkovik Airport - Makkovik (CYFT)'),
('CYGH', 'Fort Good Hope Airport - Fort Good Hope (CYGH)'),
('CYGL', 'La Grande Riviere Airport - La Grande Riviere (CYGL)'),
('CYGO', 'Gods Lake Narrows Airport - Gods Lake Narrows (CYGO)'),
('CYGP', 'Michel-Pouliot Gaspé Airport - Gaspé (CYGP)'),
('CYGR', 'Îles-de-la-Madeleine Airport - Les Îles-de-la-Madeleine (CYGR)'),
('CYGT', 'Igloolik Airport - Igloolik (CYGT)'),
('CYGV', 'Havre-Saint-Pierre Airport - Havre-Saint-Pierre (CYGV)'),
('CYGW', 'Kuujjuarapik Airport - Kuujjuarapik (CYGW)'),
('CYGX', 'Gillam Airport - Gillam (CYGX)'),
('CYGZ', 'Grise Fiord Airport - Grise Fiord (CYGZ)'),
('CYHA', 'Quaqtaq Airport - Quaqtaq (CYHA)'),
('CYHH', 'Nemiscau Airport - Nemiscau (CYHH)'),
('CYHI', 'Ulukhaktok Holman Airport - Ulukhaktok (CYHI)'),
('CYHK', 'Gjoa Haven Airport - Gjoa Haven (CYHK)'),
('CYHM', 'John C. Munro Hamilton International Airport - Hamilton (CYHM)'),
('CYHO', 'Hopedale Airport - Hopedale (CYHO)'),
('CYHP', 'Poplar Hill Airport - Poplar Hill (CYHP)'),
('CYHR', 'Chevery Airport - Chevery (CYHR)'),
('CYHU', 'Montréal / Saint-Hubert Metropolitan Airport - Montréal (CYHU)'),
('CYHY', 'Hay River / Merlyn Carter Airport - Hay River (CYHY)'),
('CYHZ', 'Halifax / Stanfield International Airport - Halifax (CYHZ)'),
('CYIF', 'St Augustin Airport - St-Augustin (CYIF)'),
('OMAA', 'Zayed International Airport - Abu Dhabi (OMAA)'),
('OMAL', 'Al Ain International Airport - Al Ain (OMAL)'),
('OMDB', 'Dubai International Airport - Dubai (OMDB)'),
('OMDL', 'Delma Airport - Delma Island (OMDL)'),
('OMDW', 'Al Maktoum International Airport - Jebel Ali (OMDW)'),
('OMFJ', 'Fujairah International Airport - Fujairah (OMFJ)'),
('OMRK', 'Ras Al Khaimah International Airport - Ras Al Khaimah (OMRK)'),
('OMSJ', 'Sharjah International Airport - Sharjah (OMSJ)'),
('OAFZ', 'Fayzabad Airport - Fayzabad (OAFZ)'),
('OAHR', 'Herat - Khwaja Abdullah Ansari International Airport - Guzara (OAHR)'),
('OAKB', 'Kabul International Airport - Kabul (OAKB)'),
('OAKN', 'Ahmad Shah Baba International Airport / Kandahar Airfield - Khvoshab (OAKN)'),
('OAMN', 'Maymana Zahiraddin Faryabi Airport - Maymana (OAMN)'),
('OAMS', 'Mazar-i-Sharif International Airport - Mazar-i-Sharif (OAMS)'),
('TAPA', 'V C Bird International Airport - Osbourn (TAPA)'),
('TAPH', 'Codrington Airport - Codrington (TAPH)'),
('TQPF', 'Clayton J Lloyd International Airport - The Valley (TQPF)'),
('LATI', 'Tirana International Airport Mother Teresa - Rinas (LATI)'),
('UDSG', 'Shirak International Airport - Gyumri (UDSG)'),
('UDYZ', 'Zvartnots International Airport - Yerevan (UDYZ)'),
('FNBC', 'Mbanza Congo Airport - Mbanza Congo (FNBC)'),
('FNCA', 'Cabinda Airport - Cabinda (FNCA)'),
('FNCT', 'Catumbela Airport - Catumbela (FNCT)'),
('FNDU', 'Dundo Airport - Chitato (FNDU)'),
('FNGI', 'Ngjiva Pereira Airport - Ngiva (FNGI)'),
('FNHU', 'Nova Lisboa Airport - Huambo (FNHU)'),
('FNLU', 'Quatro de Fevereiro International Airport - Luanda (FNLU)'),
('FNMA', 'Malanje Airport - Malanje (FNMA)'),
('FNME', 'Menongue Airport - Menongue (FNME)'),
('FNMO', 'Welwitschia Mirabilis International Airport - Moçâmedes (FNMO)'),
('FNNG', 'Negage Airport - Negage (FNNG)'),
('FNSO', 'Soyo Airport - Soyo (FNSO)'),
('FNUB', 'Lubango Airport - Lubango (FNUB)'),
('SCRM', 'Teniente Rodolfo Marsh Martin Airport - Villa Las Estrellas (SCRM)'),
('NZOU', 'Aeroestación Yabotí - El Soberbio (NZOU)'),
('SA10', 'Aeródromo Estancia Don Panos - Presidencia Roca (SA10)'),
('SAAP', 'General Urquiza Airport - Parana (SAAP)'),
('SAAR', 'Rosario Islas Malvinas International Airport - Rosario (SAAR)'),
('SAAV', 'Sauce Viejo Airport - Santa Fe (SAAV)'),
('SABE', 'Jorge Newbery Airpark - Buenos Aires (SABE)'),
('SACO', 'Ingeniero Ambrosio Taravella Airport - Cordoba (SACO)'),
('SAEZ', 'Minister Pistarini International Airport - Buenos Aires (Ezeiza) (SAEZ)'),
('SAME', 'El Plumerillo Airport - Mendoza (SAME)'),
('SAMR', 'Suboficial Ay Santiago Germano Airport - San Rafael (SAMR)'),
('SANC', 'Coronel Felipe Varela International Airport - Catamarca (SANC)'),
('SANE', 'Vicecomodoro Angel D. La Paz Aragonés Airport - Santiago del Estero (SANE)'),
('SANL', 'Capitan V A Almonacid Airport - La Rioja (SANL)'),
('SANR', 'Termas de Río Hondo international Airport - Termas de Río Hondo (SANR)'),
('SANT', 'Teniente Benjamin Matienzo Airport - San Miguel de Tucumán (SANT)'),
('SANU', 'Domingo Faustino Sarmiento Airport - San Juan (SANU)'),
('SAOU', 'Brigadier Mayor D Cesar Raul Ojeda Airport - San Luis (SAOU)'),
('SAOV', 'Presidente Néstor Kirchner Regional Airport - Villa Maria (SAOV)'),
('SARC', 'Corrientes Airport - Corrientes (SARC)'),
('SARE', 'Resistencia International Airport - Resistencia (SARE)'),
('SARF', 'Formosa National Airport - Formosa (SARF)'),
('SARI', 'Cataratas Del Iguazú International Airport - Puerto Iguazu (SARI)'),
('SARP', 'Libertador Gral D Jose De San Martin Airport - Posadas (SARP)'),
('SASA', 'Martin Miguel De Guemes International Airport - Salta (SASA)'),
('SASJ', 'Gobernador Horacio Guzman International Airport - San Salvador de Jujuy (SASJ)'),
('SAVC', 'General E. Mosconi Airport - Comodoro Rivadavia (SAVC)'),
('SAVE', 'Esquel Brigadier Antonio Parodi International Airport - Esquel (SAVE)'),
('SAVH', 'Las Heras Airport - Las Heras (SAVH)'),
('SAVN', 'Antoine de Saint Exupéry Airport - San Antonio Oeste (SAVN)'),
('SAVT', 'Almirante Marco Andres Zar Airport - Rawson (SAVT)'),
('SAVV', 'Gobernador Castello Airport - Viedma / Carmen de Patagones (SAVV)'),
('SAVY', 'El Tehuelche Airport - Puerto Madryn (SAVY)'),
('SAWC', 'El Calafate - Commander Armando Tola International Airport - El Calafate (SAWC)'),
('SAWD', 'Puerto Deseado Airport - Puerto Deseado (SAWD)'),
('SAWE', 'Gobernador Ramón Trejo Noel International Airport - Rio Grande (SAWE)'),
('SAWG', 'Piloto Civil N. Fernández Airport - Rio Gallegos (SAWG)'),
('SAWH', 'Ushuaia - Malvinas Argentinas International Airport - Ushuaia (SAWH)'),
('SAWP', 'Perito Moreno Jalil Hamer Airport - Perito Moreno (SAWP)'),
('SAWR', 'Gobernador Gregores Airport - Gobernador Gregores (SAWR)'),
('SAWT', '28 de Noviembre Airport - Rio Turbio (SAWT)'),
('SAZB', 'Comandante Espora Airport - Bahía Blanca (SAZB)'),
('SAZL', 'Santa Teresita Airport - Santa Teresita (SAZL)'),
('SAZM', 'Ástor Piazzola International Airport - Mar del Plata (SAZM)'),
('SAZN', 'Presidente Peron Airport - Neuquen (SAZN)'),
('SAZO', 'Necochea Airport - Necochea (SAZO)'),
('SAZR', 'Santa Rosa Airport - Santa Rosa (SAZR)'),
('SAZS', 'San Carlos de Bariloche Airport - San Carlos de Bariloche (SAZS)'),
('SAZY', 'Aviador C. Campos Airport - Chapelco/San Martin de los Andes (SAZY)'),
('NSAS', 'Ofu Airport - Ofu (NSAS)'),
('NSFQ', 'Fitiuta Airport - Fitiuta Village (NSFQ)'),
('NSTU', 'Pago Pago International Airport - Pago Pago (NSTU)'),
('LOWG', 'Graz Airport - Feldkirchen bei Graz (LOWG)'),
('LOWI', 'Innsbruck Airport - Innsbruck (LOWI)'),
('LOWK', 'Klagenfurt Airport - Klagenfurt am Wörthersee (LOWK)'),
('LOWL', 'Linz-Hörsching Airport / Vogler Air Base - Linz (LOWL)'),
('LOWS', 'Salzburg Airport - Salzburg (LOWS)'),
('LOWW', 'Vienna International Airport - Vienna (LOWW)'),
('LSGT', 'Gruyere Airport - Cosmo Newbery (LSGT)'),
('YABA', 'Albany Airport - Albany (YABA)'),
('YARM', 'Armidale Airport - Armidale (YARM)'),
('YAUR', 'Aurukun Airport - Aurukun (YAUR)'),
('YAYE', 'Ayers Rock Connellan Airport - Yulara (YAYE)'),
('YBAR', 'Barcaldine Airport - Barcaldine (YBAR)'),
('YBAS', 'Alice Springs Airport - Alice Springs (YBAS)'),
('YBAU', 'Badu Island Airport - Badu Island (YBAU)'),
('YBBN', 'Brisbane International Airport - Brisbane (YBBN)'),
('YBCG', 'Gold Coast Airport - Gold Coast (YBCG)'),
('YBCK', 'Blackall Airport - Blackall (YBCK)'),
('YBCS', 'Cairns International Airport - Cairns (YBCS)'),
('YBCV', 'Charleville Airport - Charleville (YBCV)'),
('YBDG', 'Bendigo Airport - Bendigo (YBDG)'),
('YBDV', 'Birdsville Airport - Birdsville (YBDV)'),
('YBHI', 'Broken Hill Airport - Broken Hill (YBHI)'),
('YBHM', 'Hamilton Island Airport - Hamilton Island (YBHM)'),
('YBIE', 'Bedourie Airport - Bedourie (YBIE)'),
('YBKE', 'Bourke Airport - Bourke (YBKE)'),
('YBKT', 'Burketown Airport - Burketown (YBKT)'),
('YBLN', 'Busselton Margaret River Regional Airport - Busselton (YBLN)'),
('YBMA', 'Mount Isa Airport - Mount Isa (YBMA)'),
('YBMK', 'Mackay Airport - Mackay (YBMK)'),
('YBNA', 'Ballina Byron Gateway Airport - Ballina (YBNA)'),
('YBOI', 'Boigu Island Airport - Boigu Island (YBOI)'),
('YBOK', 'Oakey Army Aviation Centre - Oakey (YBOK)'),
('YBOU', 'Boulia Airport - Boulia (YBOU)'),
('YBPN', 'Proserpine Whitsunday Coast Airport - Proserpine (YBPN)'),
('YBRK', 'Rockhampton Airport - Rockhampton (YBRK)'),
('YBRM', 'Broome International Airport - Broome (YBRM)'),
('YBSU', 'Sunshine Coast Airport - Maroochydore (YBSU)'),
('YBTH', 'Bathurst Airport - Bathurst (YBTH)'),
('YBTL', 'Townsville Airport / RAAF Base Townsville - Townsville (YBTL)'),
('YBUD', 'Bundaberg Airport - Bundaberg (YBUD)'),
('YBWP', 'Weipa Airport - Weipa (YBWP)'),
('YBWW', 'Toowoomba Wellcamp Airport - Toowoomba (YBWW)'),
('YCAR', 'Carnarvon Airport - Carnarvon (YCAR)'),
('YCBA', 'Cobar Airport - Cobar (YCBA)'),
('YCBP', 'Coober Pedy Airport - Coober Pedy (YCBP)'),
('YCCT', 'Coconut Island Airport - Coconut Island (YCCT)'),
('YCCY', 'Cloncurry Airport - Cloncurry (YCCY)'),
('YCDU', 'Ceduna Airport - Ceduna  (YCDU)'),
('YCFS', 'Coffs Harbour Airport - Coffs Harbour (YCFS)'),
('YCHK', 'Christmas Creek Airport - Christmas Creek Mine (YCHK)'),
('YCKN', 'Cooktown Airport - Cooktown (YCKN)'),
('YCMU', 'Cunnamulla Airport - Cunnamulla (YCMU)'),
('YCNM', 'Coonamble Airport - Coonamble (YCNM)'),
('YCOE', 'Coen Airport - Coen (YCOE)'),
('YCOM', 'Cooma Snowy Mountains Airport - Cooma (YCOM)'),
('YDMG', 'Doomadgee Airport - Doomadgee (YDMG)'),
('YDNI', 'Darnley Island Airport - Darnley Island (YDNI)'),
('YDPO', 'Devonport Airport - Devonport (YDPO)'),
('YELD', 'Elcho Island Airport - Elcho Island (YELD)'),
('YEML', 'Emerald Airport - Emerald (YEML)'),
('YESP', 'Esperance Airport - Esperance (YESP)'),
('YFLI', 'Flinders Island Airport - Whitemark (YFLI)'),
('YFTZ', 'Fitzroy Crossing Airport - Fitzroy Crossing (YFTZ)'),
('YGDO', 'Gundaroo Airport - Gundaroo (YGDO)')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
