-- airports seed batch 4/11
INSERT INTO public.airports (code, name) VALUES
('NZWK', 'Whakatane Airport - Whakatane Airport (NZWK)'),
('NZWN', 'Wellington International Airport - Wellington (NZWN)'),
('NZWR', 'Whangarei Airport - Whangarei (NZWR)'),
('NZWS', 'Westport Airport - Westport (NZWS)'),
('NZWU', 'Wanganui Airport - Wanganui (NZWU)'),
('OODQ', 'Duqm International Airport - Duqm (OODQ)'),
('OOKB', 'Khasab Airport - Khasab (OOKB)'),
('OOMS', 'Muscat International Airport - Muscat (OOMS)'),
('OOSA', 'Salalah Airport - Salalah (OOSA)'),
('OOSH', 'Sohar Airport - Sohar (OOSH)'),
('MPBO', 'Bocas del Toro International Airport - Isla Colón (MPBO)'),
('MPCE', 'Alonso Valderrama Airport - Chitré (MPCE)'),
('MPCH', 'Changuinola Captain Manuel Nino International Airport - Changuinola (MPCH)'),
('MPDA', 'Enrique Malek International Airport - David (MPDA)'),
('MPEJ', 'Enrique Adolfo Jimenez Airport - Colón (MPEJ)'),
('MPPA', 'Panamá Pacífico International Airport - Panamá City (MPPA)'),
('MPMG', 'Marcos A. Gelabert International Airport - Albrook (MPMG)'),
('MPPD', 'Capt. J. Montenegro Airport - Pedasí (MPPD)'),
('MPSM', 'Scarlett Martinez International Airport - Río Hato (MPSM)'),
('MPTO', 'Tocumen International Airport - Tocumen (MPTO)'),
('MPPX', 'Pixvae Airstrip - Pixvae (MPPX)'),
('MPRA', 'Raul Arias Espinoza Airport - Contadora Island (MPRA)'),
('SPCL', 'Cap FAP David Abenzur Rengifo International Airport - Pucallpa (SPCL)'),
('SPEO', 'FAP Lieutenant Jaime Andres de Montreuil Morales Airport - Chimbote (SPEO)'),
('SPHI', 'Air Force Captain Jose A Quinones Gonzales International Airport - Chiclayo (SPHI)'),
('SPHO', 'Air Force Colonel Alfredo Mendivil Duarte Airport - Ayacucho (SPHO)'),
('SPHU', 'Huancayo Airport - Huancayo (SPHU)'),
('SPHY', 'Andahuaylas Airport - Andahuaylas (SPHY)'),
('SPJC', 'Jorge Chávez International Airport - Lima (SPJC)'),
('SPJE', 'Shumba Airport - Jaén (SPJE)'),
('SPJJ', 'Francisco Carle Airport - Jauja (SPJJ)'),
('SPJL', 'Inca Manco Capac International Airport - Juliaca (SPJL)'),
('SPJR', 'Mayor General FAP Armando Revoredo Iglesias Airport - Cajamarca (SPJR)'),
('SPLO', 'General Jorge Fernandez Maldon Airport - Ilo (SPLO)'),
('SPME', 'Captain Pedro Canga Rodríguez International Airport - Tumbes (SPME)'),
('SPMS', 'Moises Benzaquen Rengifo Airport - Yurimaguas (SPMS)'),
('SPNC', 'Alferez Fap David Figueroa Fernandini Airport - Huánuco (SPNC)'),
('SPPO', 'Pozuzo Airport - Pozuzo (SPPO)'),
('SPPY', 'Chachapoyas Airport - Chachapoyas (SPPY)'),
('SPQT', 'Coronel FAP Francisco Secada Vignetta International Airport - Iquitos (SPQT)'),
('SPQU', 'Rodríguez Ballón International Airport - Arequipa (SPQU)'),
('SPRU', 'Capitan FAP Carlos Martinez De Pinillos International Airport - Trujillo (SPRU)'),
('SPST', 'Cadete FAP Guillermo Del Castillo Paredes Airport - Tarapoto (SPST)'),
('SPTN', 'Coronel FAP Carlos Ciriani Santa Rosa International Airport - Tacna (SPTN)'),
('SPTU', 'Padre Aldamiz International Airport - Puerto Maldonado (SPTU)'),
('SPUR', 'Capitán FAP Guillermo Concha Iberico International Airport - Piura (SPUR)'),
('SPYL', 'Captain Victor Montes Arias International Airport - Talara (SPYL)'),
('SPZA', 'Maria Reiche Neuman Airport - Nazca (SPZA)'),
('SPZO', 'Alejandro Velasco Astete International Airport - Cusco (SPZO)'),
('NTAA', 'Faa''a International Airport - Papeete (NTAA)'),
('NTAM', 'Rimatara Airport - Rimatara Island (NTAM)'),
('NTAR', 'Rurutu Airport - Rurutu (NTAR)'),
('NTAT', 'Tubuai Airport - Mataura (NTAT)'),
('NTAV', 'Raivavae Airport - Raivavae (NTAV)'),
('NTGA', 'Anaa Airport - Anaa (NTGA)'),
('NTGB', 'Fangatau Airport - Fangatau (NTGB)'),
('NTGC', 'Tikehau Airport -  Tikehau (NTGC)'),
('NTGD', 'Apataki Airport - Apataki (NTGD)'),
('NTGF', 'Fakarava Airport - Rotoava (NTGF)'),
('NTGH', 'Hikueru Airport - Hikueru (NTGH)'),
('NTGI', 'Manihi Airport - Paeva (NTGI)'),
('NTGJ', 'Totegegie Airport - Totegegie (NTGJ)'),
('NTGK', 'Kaukura Airport - Raitahiti (NTGK)'),
('NTGM', 'Makemo Airport - Makemo (NTGM)'),
('NTGN', 'Napuka Island Airport - Napuka Island (NTGN)'),
('NTGO', 'Tatakoto Airport - Tatakoto (NTGO)'),
('NTGP', 'Puka Puka Airport - Puka Puka (NTGP)'),
('NTGT', 'Takapoto Airport - Takapoto  (NTGT)'),
('NTGU', 'Arutua Airport -  Arutua (NTGU)'),
('NTGV', 'Mataiva Airport - Rangiroa (NTGV)'),
('NTHE', 'Ahe Airport - Ahe Atoll (NTHE)'),
('NTKA', 'Kauehi Airport - Kauehi (NTKA)'),
('NTKH', 'Fakahina Airport - Fakahina (NTKH)'),
('NTKN', 'Naiu Airport - Naiu Atoll (NTKN)'),
('NTKO', 'Raroia Airport - Raroia (NTKO)'),
('NTKR', 'Takaroa Airport - Takaroa (NTKR)'),
('NTMD', 'Nuku Hiva Airport - Nuku Hiva (NTMD)'),
('NTMN', 'Hiva Oa-Atuona Airport - Hiva Oa Island (NTMN)'),
('NTMP', 'Ua Pou Airport - Ua Pou (NTMP)'),
('NTMU', 'Ua Huka Airport - Ua Huka (NTMU)'),
('RPVB', 'Bacolod-Silay Airport - Bacolod City (RPVB)'),
('RPVC', 'Calbayog Airport - Calbayog City (RPVC)'),
('RPVD', 'Sibulan Airport - Dumaguete City (RPVD)'),
('RPVE', 'Godofredo P. Ramos Airport - Caticlan (RPVE)'),
('RPVF', 'Catarman National Airport - Catarman (RPVF)'),
('RPVI', 'Iloilo International Airport - Cabatuan (RPVI)'),
('RPVJ', 'Moises R. Espinosa Airport - Masbate (RPVJ)'),
('RPVK', 'Kalibo International Airport - Kalibo (RPVK)'),
('RPVM', 'Mactan Cebu International Airport - Lapu-Lapu City (RPVM)'),
('RPVP', 'Puerto Princesa International Airport / PAF Antonio Bautista Air Base - Puerto Princesa (RPVP)'),
('RPVR', 'Roxas Airport - Roxas City (RPVR)'),
('RPVU', 'Tugdan Airport - Tablas Island (RPVU)'),
('RPVV', 'Francisco B. Reyes (Busuanga) Airport - Coron (RPVV)'),
('OPBW', 'Bahawalpur Airport - Bahawalpur (OPBW)'),
('OPCH', 'Chitral Airport - Chitral (OPCH)'),
('OPDB', 'Dalbandin Airport - Dalbandin (OPDB)'),
('OPDG', 'Dera Ghazi Khan Airport - Dera Ghazi Khan (OPDG)'),
('OPFA', 'Faisalabad International Airport - Faisalabad (OPFA)'),
('OPGD', 'New Gwadar International Airport - Gurandani (OPGD)'),
('OPGT', 'Gilgit Airport - Gilgit (OPGT)'),
('OPIS', 'Islamabad International Airport - Attock (OPIS)'),
('OPKC', 'Jinnah International Airport - Karachi (OPKC)'),
('OPKD', 'Hyderabad Airport - Hyderabad (OPKD)'),
('OPKH', 'Khuzdar Airport - Khuzdar (OPKH)'),
('OPLA', 'Allama Iqbal International Airport - Lahore (OPLA)'),
('OPMT', 'Multan International Airport - Multan (OPMT)'),
('OPNH', 'Shaheed Benazirabad Airport - Nawabashah (OPNH)'),
('OPPS', 'Peshawar International Airport - Peshawar (OPPS)'),
('OPQT', 'Quetta International Airport - Quetta (OPQT)'),
('OPRK', 'Shaikh Zaid Airport - Rahim Yar Khan (OPRK)'),
('OPSD', 'Skardu Airport - Skardu (OPSD)'),
('OPSK', 'Sukkur Airport - Mirpur Khas (OPSK)'),
('OPST', 'Sialkot International Airport - Sialkot (OPST)'),
('OPTU', 'Turbat International Airport - Turbat (OPTU)'),
('OPZB', 'Zhob Airport - Fort Sandeman (OPZB)'),
('EPBY', 'Bydgoszcz Ignacy Jan Paderewski Airport - Bydgoszcz (EPBY)'),
('EPGD', 'Gdańsk Lech Wałęsa Airport - Gdańsk (EPGD)'),
('EPKK', 'Kraków John Paul II International Airport - Balice (EPKK)'),
('EPKT', 'Katowice Wojciech Korfanty International Airport - Katowice (EPKT)'),
('EPLB', 'Lublin Airport - Lublin (EPLB)'),
('EPLL', 'Łódź Władysław Reymont Airport - Łódź (EPLL)'),
('EPMO', 'Modlin Airport - Nowy Dwór Mazowiecki (EPMO)'),
('EPPO', 'Poznań-Ławica Airport - Poznań (EPPO)'),
('EPRA', 'Warsaw Radom Airport - Radom (EPRA)'),
('EPRZ', 'Rzeszów-Jasionka Airport - Jasionka (EPRZ)'),
('EPSC', 'Solidarity Szczecin–Goleniów Airport - Glewice (EPSC)'),
('EPSY', 'Olsztyn-Mazury Airport - Szymany (EPSY)'),
('EPWA', 'Warsaw Chopin Airport - Warsaw (EPWA)'),
('EPWR', 'Copernicus Wrocław Airport - Wrocław (EPWR)'),
('EPZG', 'Zielona Góra-Babimost Airport - Nowe Kramsko (EPZG)'),
('LFVM', 'Miquelon Airport - Miquelon (LFVM)'),
('LFVP', 'St Pierre Airport - Saint-Pierre (LFVP)'),
('TJBQ', 'Rafael Hernández International Airport - Aguadilla (TJBQ)'),
('TJCP', 'Benjamin Rivera Noriega Airport - Culebra (TJCP)'),
('TJIG', 'Fernando Luis Ribas Dominicci Airport - San Juan (TJIG)'),
('TJMZ', 'Eugenio Maria De Hostos Airport - Mayaguez (TJMZ)'),
('TJPS', 'Mercedita Airport - Ponce (TJPS)'),
('TJRV', 'José Aponte de la Torre Airport - Ceiba (TJRV)'),
('TJSJ', 'Luis Munoz Marin International Airport - San Juan (TJSJ)'),
('TJVQ', 'Antonio Rivera Rodriguez Airport - Vieques (TJVQ)'),
('LPAZ', 'Santa Maria Airport - Vila do Porto (LPAZ)'),
('LPBG', 'Bragança Airport - Bragança (LPBG)'),
('LPCR', 'Corvo Airport - Corvo (LPCR)'),
('LPCS', 'Cascais Airport - Cascais (LPCS)'),
('LPFL', 'Flores Airport - Santa Cruz das Flores (LPFL)'),
('LPFR', 'Faro Airport - Faro (LPFR)'),
('LPGR', 'Graciosa Airport - Santa Cruz da Graciosa (LPGR)'),
('LPHR', 'Horta Airport - Horta (LPHR)'),
('LPLA', 'Lajes Airport - Praia da Vitória (LPLA)'),
('LPMA', 'Madeira International Airport Cristiano Ronaldo - Funchal (LPMA)'),
('LPPD', 'Joao Paulo II Airport - Ponta Delgada (LPPD)'),
('LPPI', 'Pico Airport - Pico Island (LPPI)'),
('LPPM', 'Portimao Airport - Portimao (LPPM)'),
('LPPR', 'Francisco de Sá Carneiro Airport - Porto (LPPR)'),
('LPPS', 'Porto Santo Airport - Vila Baleira (LPPS)'),
('LPPT', 'Lisbon Humberto Delgado Airport - Lisbon (LPPT)'),
('LPSJ', 'Sao Jorge Airport - Velas (LPSJ)'),
('LPVR', 'Vila Real Airport - Vila Real (LPVR)'),
('LPVZ', 'Aerodromo Goncalves Lobato (Viseu Airport) - Viseu (LPVZ)'),
('PTRO', 'Babelthuap Airport - Babelthuap Island (PTRO)'),
('SGAS', 'Silvio Pettirossi International Airport - Asunción (SGAS)'),
('SGEN', 'Lieutenant Amin Ayub González International Airport - Encarnación (SGEN)'),
('SGES', 'Guaraní International Airport - Ciudad del Este (SGES)'),
('OTHH', 'Hamad International Airport - Doha (OTHH)'),
('FMEE', 'Roland Garros Airport - Sainte-Marie (FMEE)'),
('FMEP', 'Pierrefonds Airport - Saint-Pierre (FMEP)'),
('LRAR', 'Arad International Airport - Arad (LRAR)'),
('LRBC', 'Bacău George Enescu International  Airport - Bacău (LRBC)'),
('LRBM', 'Maramures International Airport - Tăuaii-Măgherăua (LRBM)'),
('LRBS', 'Bucharest Băneasa Aurel Vlaicu International Airport - Bucharest (LRBS)'),
('LRBV', 'Brasov-Ghimbav International Airport - Brasov  (Ghimbav) (LRBV)'),
('LRCK', 'Mihail Kogălniceanu International Airport - Mihail Kogălniceanu (LRCK)'),
('LRCL', 'Cluj Avram Iancu International Airport - Cluj-Napoca (LRCL)'),
('LRCV', 'Craiova International Airport - Craiova (LRCV)'),
('LRIA', 'Iaşi Airport - Iaşi (LRIA)'),
('LROD', 'Oradea International Airport - Oradea (LROD)'),
('LROP', 'Bucharest Henri Coandă International Airport - Otopeni (LROP)'),
('LRSB', 'Sibiu International Airport - Sibiu (LRSB)'),
('LRSM', 'Satu Mare International Airport - Satu Mare (LRSM)'),
('LRSV', 'Suceava Stefan cel Mare Airport - Suceava (LRSV)'),
('LRTM', 'Târgu Mureş Transilvania International Airport - Recea (LRTM)'),
('LRTR', 'Timişoara Traian Vuia Airport - Timişoara (LRTR)'),
('LYBE', 'Belgrade Nikola Tesla Airport - Belgrade (LYBE)'),
('LYKV', 'Morava Airport - Kraljevo (LYKV)'),
('LYNI', 'Niš Constantine the Great Airport - Niš (LYNI)'),
('UHHD', 'Dalnerechensk Airport - Dalnerechensk (UHHD)'),
('UEBD', 'Deputatskiy Airport - Deputatskiy (UEBD)'),
('USMQ', 'Yamburg Airport - Yamburg (USMQ)'),
('UIKG', 'Taksimo Airport - Taksimo (UIKG)'),
('ULPM', 'Kostomuksha Airfield - Kostomuksha (ULPM)'),
('ZC2P', 'Bichevaya Airport - Bichevaya (ZC2P)'),
('RU-0527', 'Byas-Kyuyol Airport - Byas-Kyuyol (RU-0527)'),
('USDM', 'Utrenniy Airport - Arctic LNG 2 project - Utrenneye gas field (USDM)'),
('ULPA', 'Pudozh - Pudozh (ULPA)'),
('URKE', 'Yeysk Airport - Yeysk (URKE)'),
('UEBB', 'Batagay Airport - Batagay (UEBB)'),
('UEBS', 'Sakkyryr Airport - Batagay-Alyta (UEBS)'),
('UEBT', 'Ust-Kuyga Airport - Ust-Kuyga (UEBT)'),
('UEEE', 'Yakutsk Airport - Yakutsk (UEEE)'),
('UEKU', 'Kutana Airport - Kutana (UEKU)'),
('UELL', 'Chulman Airport - Neryungri (UELL)'),
('UEMA', 'Moma Airport - Khonuu (UEMA)'),
('UEMO', 'Olyokminsk Airport - Olyokminsk (UEMO)'),
('UEMT', 'Ust-Nera Airport - Ust-Nera (UEMT)'),
('UEMU', 'Ust-Maya Airport - Ust-Maya (UEMU)'),
('UENI', 'Verkhnevilyuisk Airport - Verkhnevilyuisk (UENI)'),
('UENS', 'Suntar Airport - Suntar (UENS)'),
('UENW', 'Vilyuisk Airport - Vilyuisk (UENW)'),
('UERL', 'Lensk Airport - Lensk (UERL)'),
('UERP', 'Polyarny Airport - Yakutia (UERP)'),
('UERR', 'Mirny Airport - Mirny (UERR)'),
('UERS', 'Saskylakh Airport - Saskylakh (UERS)'),
('UESK', 'Srednekolymsk Airport - Srednekolymsk (UESK)'),
('UESO', 'Chokurdakh Airport - Chokurdah (UESO)'),
('UESS', 'Cherskiy Airport - Cherskiy (UESS)'),
('UEST', 'Tiksi Airport - Tiksi (UEST)'),
('UESU', 'Zyryanka Airport - Zyryanka (UESU)'),
('UEVV', 'Zhigansk Airport - Zhigansk (UEVV)'),
('UHBB', 'Ignatyevo Airport - Blagoveschensk (UHBB)'),
('UHHH', 'Khabarovsk Novy Airport - Khabarovsk (UHHH)'),
('UHKD', 'Dzemgi Airport - Komsomolsk-na-Amur (UHKD)'),
('UHKK', 'Komsomolsk-on-Amur Airport - Komsomolsk-on-Amur (UHKK)'),
('UHMA', 'Ugolny Yuri Ryktheu Airport - Anadyr (UHMA)'),
('UHMF', 'Omsukchan Airport - Omsukchan (UHMF)'),
('UHMG', 'Chaybukha Airport - Chaybukha (UHMG)'),
('UHMH', 'Susuman Airport - Susman (UHMH)'),
('UHMK', 'Keperveem Airport - Keperveem (UHMK)'),
('UHMM', 'Sokol Airport - Magadan (UHMM)'),
('UHMN', 'Omolon Airport - Omolon (UHMN)'),
('UHMO', 'Markovo Airport - Markovo (UHMO)'),
('UHMP', 'Pevek Airport - Apapelgino (UHMP)'),
('UHNB', 'Bogorodskoye Airport - Bogorodskoye (UHNB)'),
('UHNN', 'Nikolayevsk-na-Amure Airport - Nikolayevsk-na-Amure Airport (UHNN)'),
('UHOO', 'Okhotsk Airport - Okhotsk (UHOO)'),
('UHPK', 'Ust''-Kamchatsk Airport - Ust''-Kamchatsk (Krutoberegovo) (UHPK)'),
('UHPP', 'Yelizovo Airport - Petropavlovsk-Kamchatsky (UHPP)'),
('UHSI', 'Iturup Airport - Kurilsk (UHSI)'),
('UHSK', 'Shakhtyorsk Airport - Shakhtyorsk (UHSK)'),
('UHSM', 'Yuzhno-Kurilsk Mendeleyevo Airport - Yuzhno-Kurilsk (UHSM)'),
('UHSN', 'Nogliki Airport - Nogliki (UHSN)'),
('UHWP', 'Plastun Airport - Plastun (UHWP)'),
('UHWW', 'Vladivostok International Airport - Artyom (UHWW)'),
('UIAA', 'Chita-Kadala International Airport - Chita (UIAA)'),
('UIBB', 'Bratsk Airport - Bratsk (UIBB)'),
('UIIH', 'Khuzhir Airport - Khuzhir, Olkhon Island (UIIH)'),
('UIII', 'Irkutsk International Airport - Irkutsk (UIII)'),
('UIKB', 'Bodaybo Airport - Bodaybo (UIKB)'),
('UITT', 'Ust-Kut Airport - Ust-Kut (UITT)'),
('UIUN', 'Nizhneangarsk International Airport - Nizhneangarsk (UIUN)'),
('UIUU', 'Baikal International Airport - Ulan Ude (UIUU)'),
('ULAA', 'Talagi Airport - Archangelsk (ULAA)'),
('ULAL', 'Leshukonskoye Airport - Leshukonskoye (ULAL)'),
('ULAM', 'Naryan Mar Airport - Naryan Mar (ULAM)'),
('ULAS', 'Solovki Airport - Solovetsky Islands (ULAS)'),
('ULDD', 'Amderma Airport - Amderma (ULDD)'),
('ULKK', 'Kotlas Airport - Kotlas (ULKK)'),
('ULLI', 'Pulkovo Airport - St. Petersburg (ULLI)'),
('ULMM', 'Murmansk Airport - Murmansk (ULMM)'),
('ULOO', 'Pskov Airport - Pskov (ULOO)'),
('ULPB', 'Petrozavodsk Airport - Petrozavodsk (ULPB)'),
('ULWC', 'Cherepovets Airport - Cherepovets (ULWC)'),
('ULWK', 'Kichmengskiy Gorodok Airport - Kichmengskiy Gorodok (ULWK)'),
('ULWU', 'Velikiy Ustyug Airport - Velikiy Ustyug (ULWU)'),
('UMKK', 'Khrabrovo Airport - Kaliningrad (UMKK)'),
('UNAA', 'Abakan International Airport - Abakan (UNAA)'),
('UNAU', 'Shushenskoye Airport - Kazantsevo (UNAU)'),
('UNBB', 'Barnaul Airport - Barnaul (UNBB)'),
('UNEE', 'Kemerovo Airport - Kemerovo (UNEE)'),
('UNII', 'Yeniseysk Airport - Yeniseysk (UNII)'),
('UNIS', 'Severo-Yeniseysk Airport - Severo-Yeniseysk (UNIS)'),
('UNIT', 'Tura Mountain Airport - Tura (UNIT)'),
('UNIW', 'Vanavara Airport - Vanavara (UNIW)'),
('UNKL', 'Krasnoyarsk International Airport - Krasnoyarsk (UNKL)'),
('UNKM', 'Krasnoyarsk Cheremshanka Airport - Krasnoyarsk (UNKM)'),
('UNKY', 'Kyzyl Airport - Kyzyl (UNKY)'),
('UNNT', 'Novosibirsk Tolmachevo Airport - Novosibirsk (UNNT)'),
('UNOO', 'Omsk Central Airport - Omsk (UNOO)'),
('UNTT', 'Bogashevo Airport - Tomsk (UNTT)'),
('UNWW', 'Spichenkovo Airport - Novokuznetsk (UNWW)'),
('UOHH', 'Khatanga Airport - Khatanga (UOHH)'),
('UOII', 'Igarka Airport - Igarka (UOII)'),
('UOOO', 'Norilsk-Alykel Airport - Norilsk (UOOO)'),
('UOTT', 'Turukhansk Airport - Turukhansk (UOTT)'),
('URKA', 'Anapa Vityazevo Airport - Krasnyi Kurgan (URKA)'),
('URKG', 'Gelendzhik Airport - Gelendzhik (URKG)'),
('URKK', 'Krasnodar Pashkovsky International Airport - Krasnodar (URKK)'),
('URMG', 'Grozny Airport - Grozny (URMG)'),
('URML', 'Makhachkala Uytash International Airport - Makhachkala (URML)'),
('URMM', 'Mineralnyye Vody Airport - Mineralnyye Vody (URMM)'),
('URMN', 'Nalchik Airport - Nalchik (URMN)'),
('URMO', 'Vladikavkaz Beslan International Airport - Beslan (URMO)'),
('URMS', 'Magas Airport - Sunzha (URMS)'),
('URMT', 'Stavropol Shpakovskoye Airport - Stavropol (URMT)'),
('URRP', 'Platov International Airport - Rostov-on-Don (URRP)'),
('URRT', 'Taganrog Yuzhny Airport - Taganrog (URRT)'),
('URSS', 'Sochi International Airport - Sochi (URSS)'),
('NTTB', 'Bora Bora Airport - Motu Mute (NTTB)'),
('NTTG', 'Rangiroa Airport - Rangiroa (NTTG)'),
('NTTH', 'Huahine-Fare Airport - Fare (NTTH)'),
('NTTM', 'Moorea Temae Airport - Moorea-Maiao (NTTM)'),
('NTTO', 'Hao Airport - Otepa (NTTO)'),
('NTTP', 'Maupiti Airport - Maupiti (NTTP)'),
('NTTR', 'Raiatea Airport - Uturoa (NTTR)'),
('AYBA', 'Baimuru Airport - Baimuru (AYBA)'),
('AYBK', 'Buka Airport - Buka Island (AYBK)'),
('AYBM', 'Balimo Airport - Balimo (AYBM)'),
('AYCH', 'Chimbu Airport - Kundiawa (AYCH)'),
('AYDU', 'Daru Airport - Daru (AYDU)'),
('AYET', 'Bosset Airport - Bosset (AYET)'),
('AYGA', 'Goroka Airport - Goronka (AYGA)'),
('AYGN', 'Gurney Airport - Gurney (AYGN)'),
('AYGR', 'Girua Airport - Popondetta (AYGR)'),
('AYGT', 'Gasmata Island Airport - Gasmata Island (AYGT)'),
('AYHK', 'Hoskins Airport - Kimbe (AYHK)'),
('AYIQ', 'Aropa Airport - Kieta (AYIQ)'),
('AYKA', 'Losuia Airport - Losuia (AYKA)'),
('AYKI', 'Kiunga Airport - Kiunga (AYKI)'),
('AYKK', 'Kikori Airport - Kikori (AYKK)'),
('AYKM', 'Kerema Airport - Kerema (AYKM)'),
('AYKV', 'Kavieng Airport - Kavieng (AYKV)'),
('AYKY', 'Londolovit Airport - Londolovit (AYKY)'),
('AYMD', 'Madang Airport - Madang (AYMD)'),
('AYMH', 'Mount Hagen Kagamuga Airport - Mount Hagen (AYMH)'),
('AYMN', 'Mendi Airport - Mendi (AYMN)'),
('AYMO', 'Momote Airport - Manus Island (AYMO)'),
('AYMR', 'Moro Airport - Moro (AYMR)'),
('AYMS', 'Misima Island Airport - Misima Island (AYMS)'),
('AYNZ', 'Nadzab Airport - Lae (AYNZ)'),
('AYOB', 'Obo Airport - Obo (AYOB)'),
('AYPY', 'Port Moresby Jacksons International Airport - Port Moresby (AYPY)'),
('AYSS', 'Sasereme Airport - Sasereme (AYSS)'),
('AYTA', 'Tari Airport - Tari (AYTA)'),
('AYTB', 'Tabubil Airport - Tabubil (AYTB)'),
('AYTI', 'Tapini Airport - Tapini (AYTI)'),
('AYTK', 'Tokua Airport - Kokopo (AYTK)'),
('AYTU', 'Tufi Airport - Tufi (AYTU)'),
('AYVN', 'Vanimo Airport - Vanimo (AYVN)'),
('AYWD', 'Wapenamanda Airport - Wapenamanda (AYWD)'),
('AYWK', 'Wewak International Airport - Wewak (AYWK)'),
('AYLM', 'Lake Murray Airport - Lake Murray (AYLM)'),
('RPEN', 'El Nido Airport - El Nido (RPEN)'),
('RPLB', 'Subic Bay International Airport / Naval Air Station Cubi Point - Olongapo (RPLB)'),
('RPLC', 'Clark International Airport / Clark Air Base - Mabalacat (RPLC)'),
('RPLI', 'Laoag International Airport - Laoag City (RPLI)'),
('RPLK', 'Bicol International Airport - Legazpi (RPLK)'),
('RPLL', 'Ninoy Aquino International Airport - Manila (Pasay) (RPLL)'),
('RPLN', 'Palanan Community Airport - Palanan (RPLN)'),
('RPLO', 'Cuyo Airport - Cuyo (RPLO)'),
('RPLT', 'Itbayat Jorge Abad Airport - Itbayat (RPLT)'),
('RPMC', 'Cotabato (Awang) Airport - Datu Odin Sinsuat (RPMC)'),
('RPMD', 'Francisco Bangoy International Airport - Davao (RPMD)'),
('RPME', 'Bancasi Airport - Butuan (RPME)'),
('RPMG', 'Dipolog Airport - Dipolog (RPMG)'),
('RPMH', 'Camiguin Airport - Mambajao (RPMH)'),
('RPMJ', 'Jolo Airport - Jolo (RPMJ)'),
('RPMN', 'Sanga Sanga Airport - Bongao (RPMN)'),
('RPMO', 'Labo Airport - Ozamiz (RPMO)'),
('RPMP', 'Pagadian Airport - Pagadian (RPMP)'),
('RPMR', 'General Santos International Airport - General Santos (RPMR)'),
('RPMS', 'Surigao Airport - Surigao City (RPMS)'),
('RPMY', 'Laguindingan International Airport - Laguindingan (RPMY)'),
('RPMZ', 'Zamboanga International Airport - Zamboanga (RPMZ)'),
('RPNS', 'Siargao Airport - Del Carmen (RPNS)'),
('RPSP', 'Bohol-Panglao International Airport - Panglao (RPSP)'),
('RPSV', 'San Vicente Airport - San Vicente (RPSV)'),
('RPUB', 'Loakan Airport - Baguio (RPUB)'),
('RPUH', 'San Jose Airport - San Jose (RPUH)'),
('RPUN', 'Naga Airport - Naga (RPUN)'),
('RPUO', 'Basco Airport - Basco (RPUO)'),
('RPUT', 'Tuguegarao Airport - Tuguegarao City (RPUT)'),
('RPUV', 'Virac Airport - Virac (RPUV)'),
('RPUY', 'Cauayan Airport - Cauayan City (RPUY)'),
('RPVA', 'Daniel Z. Romualdez Airport - Tacloban City (RPVA)'),
('VIGR', 'Gwalior Airport - Gwalior (VIGR)'),
('VIHR', 'Hisar Airport - Hisar (VIHR)'),
('VIJO', 'Jodhpur Airport - Jodhpur (VIJO)'),
('VIJP', 'Jaipur International Airport - Jaipur (VIJP)'),
('VIJR', 'Jaisalmer Airport - Jaisalmer (VIJR)'),
('VIJU', 'Jammu Airport - Jammu (VIJU)'),
('VIKG', 'Kishangarh Airport Ajmer - Ajmer (Kishangarh) (VIKG)'),
('VILH', 'Leh Kushok Bakula Rimpochee Airport - Leh (VILH)'),
('VILK', 'Chaudhary Charan Singh International Airport - Lucknow (VILK)'),
('VIMB', 'Moradabad Airport - Moradabad (VIMB)'),
('VIPK', 'Pathankot Airport - Pathankot (VIPK)'),
('VIPT', 'Pantnagar Airport - Pantnagar (VIPT)'),
('VISR', 'Sheikh ul Alam International Airport - Srinagar (VISR)'),
('VISV', 'Shravasti Airport - Shravasti (VISV)'),
('VOAT', 'Agatti Airport - Agatti (VOAT)'),
('VOBL', 'Kempegowda International Airport - Bangalore (VOBL)'),
('VOBZ', 'Vijayawada Airport - Gannavaram (VOBZ)'),
('VOCB', 'Coimbatore International Airport - Coimbatore (VOCB)'),
('VOCI', 'Cochin International Airport - Kochi (VOCI)'),
('VOCL', 'Calicut International Airport - Calicut (VOCL)'),
('VOCP', 'Kadapa Airport - Kadapa (VOCP)'),
('VOGA', 'Manohar International Airport - Mopa (VOGA)'),
('VOGB', 'Kalaburagi Airport - Kalaburagi (VOGB)'),
('VOGO', 'Dabolim Airport - Vasco da Gama (VOGO)'),
('VOHS', 'Rajiv Gandhi International Airport - Hyderabad (VOHS)'),
('VOKN', 'Kannur International Airport - Kannur (VOKN)'),
('VOKU', 'Kurnool Airport - Orvakal (VOKU)')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
