-- airports seed batch 3/11
INSERT INTO public.airports (code, name) VALUES
('LTCR', 'Mardin Airport - Mardin (LTCR)'),
('LTCS', 'Şanliurfa GAP Airport - Şanliurfa (LTCS)'),
('LTCT', 'Igdir Airport - Igdir (LTCT)'),
('LTCU', 'Bingöl Airport - Bingöl (LTCU)'),
('LTCV', 'ŞirnakŞerafettin Elçi Airport - Şirnak (LTCV)'),
('LTCW', 'Hakkari Yüksekova Airport - Hakkari (LTCW)'),
('LTDA', 'Hatay Airport - Antakya (LTDA)'),
('LTDB', 'Çukurova International Airport - Tarsus (LTDB)'),
('LTFC', 'Süleyman Demirel International Airport - Isparta (LTFC)'),
('LTFD', 'Balikesir Koca Seyit Airport - Edremit (LTFD)'),
('LTFE', 'Milas Bodrum International Airport - Bodrum (LTFE)'),
('LTFG', 'Gazipaşa-Alanya Airport - Gazipaşa (LTFG)'),
('LTFH', 'Samsun-Çarşamba Airport - Samsun (LTFH)'),
('LTFJ', 'Istanbul Sabiha Gökçen International Airport - Pendik, Istanbul (LTFJ)'),
('LTFM', 'Istanbul Airport - Arnavutköy, Istanbul (LTFM)'),
('LTFO', 'Rize–Artvin Airport - Rize (LTFO)'),
('TTCP', 'A.N.R. Robinson International Airport - Scarborough (TTCP)'),
('TTPP', 'Piarco International Airport - Port of Spain (TTPP)'),
('NGFU', 'Funafuti International Airport - Funafuti (NGFU)'),
('RCBS', 'Kinmen Airport - Shang-I (RCBS)'),
('RCFG', 'Matsu Nangan Airport - Matsu (Nangan) (RCFG)'),
('RCFN', 'Taitung Airport - Taitung City (RCFN)'),
('RCKH', 'Kaohsiung International Airport - Kaohsiung (Xiaogang) (RCKH)'),
('RCKU', 'Chiayi Airport - Shuishang (RCKU)'),
('RCLY', 'Lanyu Airport - Orchid Island (RCLY)'),
('RCMQ', 'Taichung International Airport / Ching Chuang Kang Air Base - Taichung (Qingshui) (RCMQ)'),
('RCMT', 'Matsu Beigan Airport - Matsu (Beigan) (RCMT)'),
('RCNN', 'Tainan International Airport / Tainan Air Base - Tainan (Rende) (RCNN)'),
('RCQC', 'Penghu Magong Airport - Huxi (RCQC)'),
('RCSQ', 'Pingtung Air Force Base North - Pingtung (RCSQ)'),
('RCSS', 'Taipei Songshan Airport - Taipei (Songshan) (RCSS)'),
('RCTP', 'Taiwan Taoyuan International Airport - Taoyuan (RCTP)'),
('RCYU', 'Hualien Airport - Hualien City (RCYU)'),
('HTAR', 'Arusha Airport - Arusha (HTAR)'),
('HTBU', 'Bukoba Airport - Bukoba (HTBU)'),
('HTDA', 'Julius Nyerere International Airport - Dar es Salaam (HTDA)'),
('HTDO', 'Dodoma Airport - Dodoma (HTDO)'),
('HTGW', 'Songwe Airport - Mbeya (HTGW)'),
('HTKA', 'Kigoma Airport - Kigoma (HTKA)'),
('HTKJ', 'Kilimanjaro International Airport - Arusha (HTKJ)'),
('HTMA', 'Mafia Airport - Kilindoni (HTMA)'),
('HTMT', 'Mtwara Airport - Mtwara (HTMT)'),
('HTMU', 'Musoma Airport - Musoma (HTMU)'),
('HTMW', 'Mwanza Airport - Mwanza (HTMW)'),
('HTSN', 'Seronera Airport - Seronera (HTSN)'),
('HTSY', 'Shinyanga Airport - Shinyanga (HTSY)'),
('HTTB', 'Tabora Airport - Tabora (HTTB)'),
('HTTG', 'Tanga Airport - Tanga (HTTG)'),
('HTZA', 'Abeid Amani Karume International Airport - Zanzibar (HTZA)'),
('UKBB', 'Boryspil International Airport - Boryspil (UKBB)'),
('UKCM', 'Mariupol International Airport - Mariupol (UKCM)'),
('UKDD', 'Dnipro International Airport - Dnipro (UKDD)'),
('UKDE', 'Zaporizhzhia International Airport - Zaporizhia (UKDE)'),
('UKDR', 'Kryvyi Rih International Airport - Kryvyi Rih (UKDR)'),
('UKFF', 'Simferopol International Airport - Simferopol (UKFF)'),
('UKHH', 'Kharkiv International Airport - Kharkiv (UKHH)'),
('UKKK', 'Ihor Sikorsky Kyiv International Airport (Zhuliany) - Kyiv (UKKK)'),
('UKLI', 'Ivano-Frankivsk International Airport - Ivano-Frankivsk (UKLI)'),
('UKLL', 'Lviv International Airport - Lviv (UKLL)'),
('UKLN', 'Chernivtsi International Airport - Chernivtsi (UKLN)'),
('UKLR', 'Rivne International Airport - Rivne (UKLR)'),
('UKLU', 'Uzhhorod International Airport - Uzhhorod (UKLU)'),
('UKOH', 'Kherson International Airport - Kherson (UKOH)'),
('UKON', 'Mykolaiv International Airport - Nikolayev (UKON)'),
('UKOO', 'Odessa International Airport - Odessa (UKOO)'),
('HUAR', 'Arua Airport - Arua (HUAR)'),
('HUEN', 'Entebbe International Airport - Kampala (HUEN)'),
('HUGU', 'Gulu Airport - Gulu (HUGU)'),
('HUSO', 'Soroti Airport - Soroti (HUSO)'),
('HUKI', 'Kisoro Airport - Kisoro (HUKI)'),
('PWAK', 'Wake Island Airfield - Wake Island (PWAK)'),
('PPIT', 'Nunapitchuk Airport - Nunapitchuk (PPIT)'),
('1RL', 'Point Roberts Airpark - Point Roberts (1RL)'),
('35ME', 'Matinicus Island Airport - Matinicus Island (35ME)'),
('38WA', 'Blakely Island Airport - Blakely Island (38WA)'),
('PAAT', 'Atmautluak Airport - Atmautluak (PAAT)'),
('4K0', 'Pedro Bay Airport - Pedro Bay (4K0)'),
('POKA', 'Tununak Airport - Tununak (POKA)'),
('K51Z', 'Minto Al Wright Airport - Minto (K51Z)'),
('K57B', 'Islesboro Airport - Islesboro (K57B)'),
('5A8', 'Aleknagik / New Airport - Aleknagik (5A8)'),
('PAKA', 'Tatitlek Airport - Tatitlek (PAKA)'),
('KNWL', 'Waldron Airstrip - Eastsound (KNWL)'),
('PACH', 'Chuathbaluk Airport - Chuathbaluk (PACH)'),
('A61', 'Tuntutuliak Airport - Tuntutuliak (A61)'),
('A63', 'Twin Hills Airport - Twin Hills (A63)'),
('PAJC', 'Chignik Lake Airport - Chignik Lake (PAJC)'),
('PACJ', 'Crooked Creek Airport - Crooked Creek (PACJ)'),
('KCKX', 'Chicken Airport - Chicken (KCKX)'),
('KGNU', 'Goodnews Airport - Goodnews (KGNU)'),
('KBVU', 'Boulder City Municipal Airport - Boulder City (KBVU)'),
('K74S', 'Anacortes Airport - Anacortes (K74S)'),
('KABE', 'Lehigh Valley International Airport - Allentown (KABE)'),
('KABI', 'Abilene Regional Airport - Abilene (KABI)'),
('KABQ', 'Albuquerque International Sunport - Albuquerque (KABQ)'),
('KABR', 'Aberdeen Regional Airport - Aberdeen (KABR)'),
('KABY', 'Southwest Georgia Regional Airport - Albany (KABY)'),
('KACK', 'Nantucket Memorial Airport - Nantucket (KACK)'),
('KACT', 'Waco Regional Airport - Waco (KACT)'),
('KACV', 'California Redwood Coast-Humboldt County Airport - Arcata/Eureka (KACV)'),
('KACY', 'Atlantic City International Airport - Atlantic City (KACY)'),
('KAEX', 'Alexandria International Airport - Alexandria (KAEX)'),
('KAGS', 'Augusta Regional At Bush Field - Augusta (KAGS)'),
('KAIA', 'Alliance Municipal Airport - Alliance (KAIA)'),
('KALB', 'Albany International Airport - Albany (KALB)'),
('KALO', 'Waterloo Regional Airport - Waterloo (KALO)'),
('KALS', 'San Luis Valley Regional Airport/Bergman Field - Alamosa (KALS)'),
('KALW', 'Walla Walla Regional Airport - Walla Walla (KALW)'),
('KAMA', 'Rick Husband Amarillo International Airport - Amarillo (KAMA)'),
('KAOO', 'Altoona Blair County Airport - Altoona (KAOO)'),
('KAPN', 'Alpena County Regional Airport - Alpena (KAPN)'),
('KART', 'Watertown International Airport - Watertown (KART)'),
('KASE', 'Aspen-Pitkin County Airport (Sardy Field) - Aspen (KASE)'),
('KATL', 'Hartsfield Jackson Atlanta International Airport - Atlanta (KATL)'),
('KATW', 'Appleton International Airport - Appleton (KATW)'),
('KATY', 'Watertown Regional Airport - Watertown (KATY)'),
('KAUG', 'Augusta State Airport - Augusta (KAUG)'),
('KAUS', 'Austin Bergstrom International Airport - Austin (KAUS)'),
('KAVL', 'Asheville Regional Airport - Asheville (KAVL)'),
('KAVP', 'Wilkes Barre Scranton International Airport - Wilkes-Barre/Scranton (KAVP)'),
('KGKY', 'Arlington Municipal Airport - Arlington (KGKY)'),
('KAZO', 'Kalamazoo Battle Creek International Airport - Kalamazoo (KAZO)'),
('KBBG', 'Branson Airport - Branson (KBBG)'),
('KBDL', 'Bradley International Airport - Hartford (KBDL)'),
('KBED', 'Laurence G Hanscom Field - Bedford (KBED)'),
('KBFD', 'Bradford Regional Airport - Bradford (KBFD)'),
('KBFF', 'Western Neb. Rgnl/William B. Heilig Airport - Scottsbluff (KBFF)'),
('KBFI', 'Boeing Field King County International Airport - Seattle (KBFI)'),
('KBFL', 'Meadows Field - Bakersfield (KBFL)'),
('KBGM', 'Greater Binghamton/Edwin A Link field - Binghamton (KBGM)'),
('KBGR', 'Bangor International Airport - Bangor (KBGR)'),
('KBHB', 'Hancock County-Bar Harbor Airport - Bar Harbor (KBHB)'),
('KBHM', 'Birmingham-Shuttlesworth International Airport - Birmingham (KBHM)'),
('KBID', 'Block Island State Airport - Block Island (KBID)'),
('KBIH', 'Eastern Sierra Regional Airport - Bishop (KBIH)'),
('KBIL', 'Billings Logan International Airport - Billings (KBIL)'),
('KBIS', 'Bismarck Municipal Airport - Bismarck (KBIS)'),
('KBJC', 'Rocky Mountain Metropolitan Airport - Denver (KBJC)'),
('KBKW', 'Raleigh County Memorial Airport - Beaver (KBKW)'),
('KBLI', 'Bellingham International Airport - Bellingham (KBLI)'),
('KBLV', 'Scott AFB/Midamerica Airport - Belleville (KBLV)'),
('KBMI', 'Central Illinois Regional Airport at Bloomington-Normal - Bloomington/Normal (KBMI)'),
('KBNA', 'Nashville International Airport - Nashville (KBNA)'),
('KBOI', 'Boise Air Terminal/Gowen Field - Boise (KBOI)'),
('KBOS', 'Logan International Airport - Boston (KBOS)'),
('KBPT', 'Jack Brooks Regional Airport - Beaumont/Port Arthur (KBPT)'),
('KBQK', 'Brunswick Golden Isles Airport - Brunswick (KBQK)'),
('KBRD', 'Brainerd Lakes Regional Airport - Brainerd (KBRD)'),
('KBRL', 'Southeast Iowa Regional Airport - Burlington (KBRL)'),
('KBRO', 'Brownsville South Padre Island International Airport - Brownsville (KBRO)'),
('KBTM', 'Bert Mooney Airport - Butte (KBTM)'),
('KBTR', 'Baton Rouge Metropolitan Airport - Baton Rouge (KBTR)'),
('KBTV', 'Burlington International Airport - South Burlington (KBTV)'),
('KBUF', 'Buffalo Niagara International Airport - Buffalo (KBUF)'),
('KBUR', 'Hollywood Burbank Airport - Burbank (KBUR)'),
('KBWI', 'Baltimore/Washington International Thurgood Marshall Airport - Baltimore (KBWI)'),
('KBZN', 'Bozeman Yellowstone International Airport - Bozeman (KBZN)'),
('KCAE', 'Columbia Metropolitan Airport - Columbia (KCAE)'),
('KCAK', 'Akron Canton Regional Airport - Akron (KCAK)'),
('KCCR', 'Buchanan Field - Concord (KCCR)'),
('KCDC', 'Cedar City Regional Airport - Cedar City (KCDC)'),
('KCDR', 'Chadron Municipal Airport - Chadron (KCDR)'),
('KCEC', 'Jack Mc Namara Field Airport - Crescent City (KCEC)'),
('KCEZ', 'Cortez Municipal Airport - Cortez (KCEZ)'),
('KCGI', 'Cape Girardeau Regional Airport - Cape Girardeau (KCGI)'),
('KCHA', 'Chattanooga Metropolitan Airport (Lovell Field) - Chattanooga (KCHA)'),
('KCHO', 'Charlottesville Albemarle Airport - Charlottesville (KCHO)'),
('KCHS', 'Charleston International Airport - Charleston (KCHS)'),
('KCID', 'The Eastern Iowa Airport - Cedar Rapids (KCID)'),
('KCIU', 'Chippewa County International Airport - Kincheloe (KCIU)'),
('KCKB', 'North Central West Virginia Airport - Bridgeport (KCKB)'),
('KCLE', 'Cleveland Hopkins International Airport - Cleveland (KCLE)'),
('KCLL', 'Easterwood Field - College Station (KCLL)'),
('KCLT', 'Charlotte Douglas International Airport - Charlotte (KCLT)'),
('KCMH', 'John Glenn Columbus International Airport - Columbus (KCMH)'),
('KCMI', 'University of Illinois Willard Airport - Savoy (KCMI)'),
('KCMX', 'Houghton County Memorial Airport - Hancock (KCMX)'),
('KCNM', 'Cavern City Air Terminal - Carlsbad (KCNM)'),
('KCNY', 'Canyonlands Regional Airport - Moab (KCNY)'),
('KCOD', 'Yellowstone Regional Airport - Cody (KCOD)'),
('KCOS', 'City of Colorado Springs Municipal Airport - Colorado Springs (KCOS)'),
('KCOU', 'Columbia Regional Airport - Columbia (KCOU)'),
('KCPR', 'Casper-Natrona County International Airport - Casper (KCPR)'),
('KCRP', 'Corpus Christi International Airport - Corpus Christi (KCRP)'),
('KCRQ', 'McClellan-Palomar Airport - Carlsbad (KCRQ)'),
('KCRW', 'Yeager Airport - Charleston (KCRW)'),
('KCSG', 'Columbus Metropolitan Airport - Columbus (KCSG)'),
('KCVG', 'Cincinnati Northern Kentucky International Airport - Cincinnati / Covington (KCVG)'),
('KCVN', 'Clovis Municipal Airport - Clovis (KCVN)'),
('KCVX', 'Charlevoix Municipal Airport - Charlevoix (KCVX)'),
('KCWA', 'Central Wisconsin Airport - Mosinee (KCWA)'),
('KCYS', 'Cheyenne Regional Jerry Olson Field - Cheyenne (KCYS)'),
('KDAB', 'Daytona Beach International Airport - Daytona Beach (KDAB)'),
('KDAL', 'Dallas Love Field - Dallas (KDAL)'),
('KDAY', 'James M Cox Dayton International Airport - Dayton (KDAY)'),
('KDBQ', 'Dubuque Regional Airport - Dubuque (KDBQ)'),
('KDCA', 'Ronald Reagan Washington National Airport - Washington (KDCA)'),
('KDDC', 'Dodge City Regional Airport - Dodge City (KDDC)'),
('KDEC', 'Decatur Airport - Decatur (KDEC)'),
('KDEN', 'Denver International Airport - Denver (KDEN)'),
('KDFW', 'Dallas Fort Worth International Airport - Dallas-Fort Worth (KDFW)'),
('KDHN', 'Dothan Regional Airport - Dothan (KDHN)'),
('KDIK', 'Dickinson Theodore Roosevelt Regional Airport - Dickinson (KDIK)'),
('KDLH', 'Duluth International Airport - Duluth (KDLH)'),
('KDRO', 'Durango La Plata County Airport - Durango (KDRO)'),
('KDSM', 'Des Moines International Airport - Des Moines (KDSM)'),
('KDTS', 'Destin Executive Airport - Destin (KDTS)'),
('KDTW', 'Detroit Metropolitan Wayne County Airport - Detroit (KDTW)'),
('KDUJ', 'DuBois Regional Airport - Dubois (KDUJ)'),
('KDVL', 'Devils Lake Regional Airport - Devils Lake (KDVL)'),
('KEAR', 'Kearney Regional Airport - Kearney (KEAR)'),
('KEAT', 'Pangborn Memorial Airport - Wenatchee (KEAT)'),
('KEAU', 'Chippewa Valley Regional Airport - Eau Claire (KEAU)'),
('KKEB', 'Nanwalek Airport - Nanwalek (KKEB)'),
('KECP', 'Northwest Florida Beaches International Airport - Panama City Beach (KECP)'),
('KEGE', 'Eagle County Regional Airport - Eagle (KEGE)'),
('KEKO', 'Elko Regional Airport - Elko (KEKO)'),
('KELD', 'South Arkansas Regional Airport at Goodwin Field - El Dorado (KELD)'),
('KELM', 'Elmira Corning Regional Airport - Elmira/Corning (KELM)'),
('KELP', 'El Paso International Airport - El Paso (KELP)'),
('KERI', 'Erie International Tom Ridge Field - Erie (KERI)'),
('KESC', 'Delta County Airport - Escanaba (KESC)'),
('KEUG', 'Mahlon Sweet Field - Eugene (KEUG)'),
('KEVV', 'Evansville Regional Airport - Evansville (KEVV)'),
('KEWB', 'New Bedford Regional Airport - New Bedford (KEWB)'),
('KEWN', 'Coastal Carolina Regional Airport - New Bern (KEWN)'),
('KEWR', 'Newark Liberty International Airport - Newark (KEWR)'),
('KEYW', 'Key West International Airport - Key West (KEYW)'),
('KFAR', 'Hector International Airport - Fargo (KFAR)'),
('KFAT', 'Fresno Yosemite International Airport - Fresno (KFAT)'),
('KFAY', 'Fayetteville Regional Airport - Grannis Field - Fayetteville (KFAY)'),
('KFHR', 'Friday Harbor Airport - Friday Harbor (KFHR)'),
('KFLG', 'Flagstaff Pulliam International Airport - Flagstaff (KFLG)'),
('KFLL', 'Fort Lauderdale Hollywood International Airport - Fort Lauderdale (KFLL)'),
('KFLO', 'Florence Regional Airport - Florence (KFLO)'),
('KFNT', 'Bishop International Airport - Flint (KFNT)'),
('KFOD', 'Fort Dodge Regional Airport - Fort Dodge (KFOD)'),
('KFSD', 'Sioux Falls Regional Airport / Joe Foss Field - Sioux Falls (KFSD)'),
('KFSM', 'Fort Smith Regional Airport - Fort Smith (KFSM)'),
('KFWA', 'Fort Wayne International Airport - Fort Wayne (KFWA)'),
('KGCC', 'Northeast Wyoming Regional Airport - Gillette (KGCC)'),
('KGCK', 'Garden City Regional Airport - Garden City (KGCK)'),
('KGCN', 'Grand Canyon National Park Airport - Grand Canyon - Tusayan (KGCN)'),
('KGDV', 'Dawson Community Airport - Glendive (KGDV)'),
('KGEG', 'Spokane International Airport - Spokane (KGEG)'),
('KGFK', 'Grand Forks International Airport - Grand Forks (KGFK)'),
('KGGG', 'East Texas Regional Airport - Longview (KGGG)'),
('KGGW', 'Glasgow Valley County Airport Wokal Field - Glasgow (KGGW)'),
('KGJT', 'Grand Junction Regional Airport - Grand Junction (KGJT)'),
('KGLH', 'Mid Delta Regional Airport - Greenville (KGLH)'),
('KGNV', 'Gainesville Regional Airport - Gainesville (KGNV)'),
('KGPI', 'Glacier Park International Airport - Kalispell (KGPI)'),
('KGPT', 'Gulfport Biloxi International Airport - Gulfport (KGPT)'),
('KGRB', 'Austin Straubel International Airport - Green Bay (KGRB)'),
('KGRI', 'Central Nebraska Regional Airport - Grand Island (KGRI)'),
('KGRK', 'Killeen Regional Airport / Robert Gray Army Airfield - Fort Cavazos (KGRK)'),
('KGRR', 'Gerald R. Ford International Airport - Grand Rapids (KGRR)'),
('KGSO', 'Piedmont Triad International Airport - Greensboro (KGSO)'),
('KGSP', 'Greenville Spartanburg International Airport - Greer (KGSP)'),
('KGTF', 'Great Falls International Airport - Great Falls (KGTF)'),
('KGTR', 'Golden Triangle Regional Airport - Columbus/W Point/Starkville (KGTR)'),
('KGUC', 'Gunnison Crested Butte Regional Airport - Gunnison (KGUC)'),
('KGUP', 'Gallup Municipal Airport - Gallup (KGUP)'),
('PAGX', 'Grayling Airport - Grayling (PAGX)'),
('KHDN', 'Yampa Valley Airport - Hayden (KHDN)'),
('KHGR', 'Hagerstown Regional Richard A Henson Field - Hagerstown (KHGR)'),
('KHHR', 'Jack Northrop Field Hawthorne Municipal Airport - Hawthorne (KHHR)'),
('KHIB', 'Range Regional Airport - Hibbing (KHIB)'),
('KHLN', 'Helena Regional Airport - Helena (KHLN)'),
('KHOB', 'Lea County Regional Airport - Hobbs (KHOB)'),
('KHOT', 'Memorial Field Airport - Hot Springs (KHOT)'),
('KHOU', 'William P Hobby Airport - Houston (KHOU)'),
('KHPN', 'Westchester County Airport - White Plains (KHPN)'),
('KHRL', 'Valley International Airport - Harlingen (KHRL)'),
('KHRO', 'Boone County Airport - Harrison (KHRO)'),
('KHSV', 'Huntsville International Carl T Jones Field - Huntsville (KHSV)'),
('KHTS', 'Tri-State Airport / Milton J. Ferguson Field - Huntington (KHTS)'),
('KHVN', 'Tweed New Haven Airport - New Haven (KHVN)'),
('KHVR', 'Havre City County Airport - Havre (KHVR)'),
('KHXD', 'Hilton Head Airport - Hilton Head Island (KHXD)'),
('KHYA', 'Cape Cod Gateway Airport - Hyannis (KHYA)'),
('KHYS', 'Hays Regional Airport - Hays (KHYS)'),
('KIAD', 'Washington Dulles International Airport - Dulles (KIAD)'),
('KIAG', 'Niagara Falls International Airport - Niagara Falls (KIAG)'),
('KIAH', 'George Bush Intercontinental Houston Airport - Houston (KIAH)'),
('KICT', 'Wichita Eisenhower National Airport - Wichita (KICT)'),
('KIDA', 'Idaho Falls Regional Airport - Idaho Falls (KIDA)'),
('KILG', 'Wilmington Airport - Wilmington (KILG)'),
('KILM', 'Wilmington International Airport - Wilmington (KILM)'),
('KIMT', 'Ford Airport - Kingsford (KIMT)'),
('KIND', 'Indianapolis International Airport - Indianapolis (KIND)'),
('KINL', 'Falls International Airport - International Falls (KINL)'),
('KIPL', 'Imperial County Airport - Imperial (KIPL)'),
('KIPT', 'Williamsport Regional Airport - Williamsport (KIPT)'),
('KIRK', 'Kirksville Regional Airport - Kirksville (KIRK)'),
('KISP', 'Long Island Mac Arthur Airport - Islip (KISP)'),
('KITH', 'Ithaca Tompkins Regional Airport - Ithaca (KITH)'),
('KIWA', 'Mesa Gateway Airport - Mesa (KIWA)'),
('KIWD', 'Gogebic Iron County Airport - Ironwood (KIWD)'),
('KJAC', 'Jackson Hole Airport - Jackson (KJAC)'),
('KJAN', 'Jackson-Medgar Wiley Evers International Airport - Jackson (KJAN)'),
('KJAX', 'Jacksonville International Airport - Jacksonville (KJAX)'),
('KJBR', 'Jonesboro Municipal Airport - Jonesboro (KJBR)'),
('KJFK', 'John F Kennedy International Airport - New York (KJFK)'),
('KJLN', 'Joplin Regional Airport - Joplin (KJLN)'),
('KJMS', 'Jamestown Regional Airport - Jamestown (KJMS)'),
('KJQF', 'Concord-Padgett Regional Airport - Concord (KJQF)'),
('KJST', 'John Murtha Johnstown Cambria County Airport - Johnstown (KJST)'),
('KLAF', 'Purdue University Airport - West Lafayette (KLAF)'),
('KLAL', 'Lakeland Linder International Airport - Lakeland (KLAL)'),
('KLAN', 'Capital City Airport - Lansing (KLAN)'),
('KLAR', 'Laramie Regional Airport - Laramie (KLAR)'),
('KLAS', 'Harry Reid International Airport - Las Vegas (KLAS)'),
('KLAW', 'Lawton Fort Sill Regional Airport - Lawton (KLAW)'),
('KLAX', 'Los Angeles International Airport - Los Angeles (KLAX)'),
('KLBB', 'Lubbock Preston Smith International Airport - Lubbock (KLBB)'),
('KLBE', 'Arnold Palmer Regional Airport - Latrobe (KLBE)'),
('KLBF', 'North Platte Regional Airport Lee Bird Field - North Platte (KLBF)'),
('KLBL', 'Liberal Mid-America Regional Airport - Liberal (KLBL)'),
('KLCH', 'Lake Charles Regional Airport - Lake Charles (KLCH)'),
('KLCK', 'Rickenbacker International Airport - Columbus (KLCK)'),
('KLEB', 'Lebanon Municipal Airport - Lebanon (KLEB)'),
('KLEX', 'Blue Grass Airport - Lexington (KLEX)'),
('KLFT', 'Lafayette Regional Airport - Lafayette (KLFT)'),
('KLGA', 'LaGuardia Airport - New York (KLGA)'),
('KLGB', 'Long Beach Airport (Daugherty Field) - Long Beach (KLGB)'),
('KLIT', 'Bill & Hillary Clinton National Airport/Adams Field - Little Rock (KLIT)'),
('KLNK', 'Lincoln Airport - Lincoln (KLNK)'),
('KLNS', 'Lancaster Airport - Lancaster (KLNS)'),
('KLRD', 'Laredo International Airport - Laredo (KLRD)'),
('KLRU', 'Las Cruces International Airport - Las Cruces (KLRU)'),
('KLSE', 'La Crosse Regional Airport - La Crosse (KLSE)'),
('KLUK', 'Cincinnati Municipal Airport Lunken Field - Cincinnati (KLUK)'),
('ENNA', 'Lakselv Airport, Banak - Lakselv (ENNA)'),
('ENNM', 'Namsos Airport - Namsos (ENNM)'),
('ENOL', 'Ørland Airport - Ørland (ENOL)'),
('ENOV', 'Ørsta-Volda Airport, Hovden - Ørsta (ENOV)'),
('ENRA', 'Mo i Rana Airport, Rossvoll - Mo i Rana (ENRA)'),
('ENRM', 'Rorvik Airport, Ryum - Rorvik (ENRM)'),
('ENRO', 'Roros Airport -  Roros (ENRO)'),
('ENRS', 'Rost Airport - Rost (ENRS)'),
('ENSB', 'Svalbard Airport, Longyear - Longyearbyen (ENSB)'),
('ENSD', 'Sandane Airport, Anda - Sandane (ENSD)'),
('ENSG', 'Sogndal Airport, Haukasen - Sogndal (ENSG)'),
('ENSH', 'Svolvaer Airport, Helle - Svolvaer (ENSH)'),
('ENSK', 'Stokmarknes Airport, Skagen - Hadsel (ENSK)'),
('ENSO', 'Stord Airport, Sorstokken - Leirvik (ENSO)'),
('ENSR', 'Sorkjosen Airport - Sorkjosen (ENSR)'),
('ENSS', 'Vardo Airport, Svartnes - Vardo (ENSS)'),
('ENST', 'Sandnessjoen Airport, Stokka - Alstahaug (ENST)'),
('ENTC', 'Tromso Airport, Langnes - Tromso (ENTC)'),
('ENTO', 'Sandefjord Airport, Torp - Torp (ENTO)'),
('ENVA', 'Trondheim Airport, Vaernes - Trondheim (ENVA)'),
('ENVD', 'Vadso Airport - Vadso (ENVD)'),
('ENZV', 'Stavanger Airport, Sola - Stavanger (ENZV)'),
('VNBP', 'Bharatpur Airport - Bharatpur (VNBP)'),
('VNBW', 'Gautam Buddha International Airport - Siddharthanagar (Bhairahawa) (VNBW)'),
('VNCG', 'Bhadrapur Airport - Bhadrapur (VNCG)'),
('VNDP', 'Dolpa Airport - Dolpa (VNDP)'),
('VNDT', 'Silgadi Doti Airport - Silgadi Doti (VNDT)'),
('VNJL', 'Jumla Airport - Jumla (VNJL)'),
('VNJP', 'Janakpur Airport - Janakpur (VNJP)'),
('VNJS', 'Jomsom Airport - Jomsom (VNJS)'),
('VNKT', 'Tribhuvan International Airport - Kathmandu (VNKT)'),
('VNLK', 'Lukla Airport - Lukla (VNLK)'),
('VNNG', 'Nepalgunj Airport - Nepalgunj (VNNG)'),
('VNPK', 'Pokhara Airport - Pokhara (VNPK)'),
('VNSI', 'Simara Airport - Simara (VNSI)'),
('VNSK', 'Surkhet Airport - Surkhet (VNSK)'),
('VNSL', 'Rukum Salle Airport - Musikot (VNSL)'),
('VNST', 'Simikot Airport - Simikot (VNST)'),
('VNTJ', 'Taplejung Airport - Taplejung (VNTJ)'),
('VNTR', 'Tumling Tar Airport - Tumling Tar (VNTR)'),
('VNVT', 'Biratnagar Airport - Biratnagar (VNVT)'),
('ANYN', 'Nauru International Airport - Yaren District (ANYN)'),
('NIUE', 'Niue International Airport - Alofi (NIUE)'),
('PITT', 'Pitt Island Aerodrome - Pitt Island (PITT)'),
('NZAA', 'Auckland International Airport - Auckland (NZAA)'),
('NZAP', 'Taupo Airport - Taupo (NZAP)'),
('NZCH', 'Christchurch International Airport - Christchurch (NZCH)'),
('NZCI', 'Chatham Islands / Tuuta Airport - Te One (NZCI)'),
('NZDN', 'Dunedin International Airport - Dunedin (NZDN)'),
('NZGS', 'Gisborne Airport - Gisborne (NZGS)'),
('NZHK', 'Hokitika Airfield - Hokitika (NZHK)'),
('NZHN', 'Hamilton International Airport - Hamilton (NZHN)'),
('NZKK', 'Kerikeri Airport - Kerikeri (NZKK)'),
('NZKT', 'Kaitaia Airport - Awanui (NZKT)'),
('NZNP', 'New Plymouth Airport - New Plymouth (NZNP)'),
('NZNR', 'Hawke''s Bay Airport - Napier (NZNR)'),
('NZNS', 'Nelson Airport - Nelson (NZNS)'),
('NZNV', 'Invercargill Airport - Invercargill (NZNV)'),
('NZOT', 'Otaki Airport - Otaki (NZOT)'),
('NZPM', 'Palmerston North Airport - Palmerston North (NZPM)'),
('NZPN', 'Picton Aerodrome - Koromiko (NZPN)'),
('NZQN', 'Queenstown International Airport - Queenstown (NZQN)'),
('NZRO', 'Rotorua Regional Airport - Rotorua (NZRO)'),
('NZTG', 'Tauranga Airport - Tauranga (NZTG)'),
('NZTU', 'Timaru Airport - Timaru (NZTU)'),
('NZWB', 'Woodbourne Airport - Blenheim (NZWB)'),
('NZWF', 'Wanaka Airport - Wanaka (NZWF)')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
