-- airports seed batch 2/11
INSERT INTO public.airports (code, name) VALUES
('SVIE', 'Andrés Miguel Salazar Marcano Airport - Isla de Coche (SVIE)'),
('SVJC', 'Josefa Camejo International Airport - Paraguaná (SVJC)'),
('SVMC', 'La Chinita International Airport - Maracaibo (SVMC)'),
('SVMG', 'Del Caribe Santiago Marino International Airport - Isla Margarita (SVMG)'),
('SVMI', 'Maiquetía Simón Bolívar International Airport - Maiquetía (SVMI)'),
('SVMT', 'José Tadeo Monagas International Airport - Maturín (SVMT)'),
('SVPR', 'General Manuel Carlos Piar International Airport - Puerto Ordaz-Ciudad Guayana (SVPR)'),
('SVRS', 'Los Roques Airport - Gran Roque Island (SVRS)'),
('SVSA', 'San Antonio Del Tachira Airport - San Antonio del Táchira (SVSA)'),
('SVSO', 'Mayor Buenaventura Vivas International Airport - Santo Domingo (SVSO)'),
('SVST', 'San Tomé Airport - El Tigre (SVST)'),
('SVVA', 'Arturo Michelena International Airport - Valencia (SVVA)'),
('SVVG', 'Juan Pablo Pérez Alfonso Airport - El Vigía (SVVG)'),
('SVVL', 'Dr. Antonio Nicolás Briceno Airport - Valera (SVVL)'),
('TUPJ', 'Terrance B. Lettsome International Airport - Beef Island (TUPJ)'),
('TUPW', 'Virgin Gorda Airport - Spanish Town (TUPW)'),
('TIST', 'Cyril E. King Airport - Charlotte Amalie (TIST)'),
('TISX', 'Henry E Rohlsen Airport - Christiansted (TISX)'),
('VVBM', 'Buon Ma Thuot Airport - Buon Ma Thuot (VVBM)'),
('VVCA', 'Chu Lai Airport - Chu Lai (VVCA)'),
('VVCI', 'Cat Bi International Airport - Haiphong (Hai An) (VVCI)'),
('VVCM', 'Ca Mau Airport - Ca Mau City (VVCM)'),
('VVCR', 'Cam Ranh International Airport / Cam Ranh Air Base - Cam Ranh (VVCR)'),
('VVCS', 'Con Dao Airport - Con Dao (VVCS)'),
('VVCT', 'Can Tho International Airport - Can Tho (VVCT)'),
('VVDB', 'Dien Bien Phu Airport - Dien Bien Phu (VVDB)'),
('VVDH', 'Dong Hoi Airport - Dong Hoi (VVDH)'),
('VVDL', 'Lien Khuong Airport - Da Lat (VVDL)'),
('KSJC', 'Norman Y. Mineta San Jose International Airport - San Jose (KSJC)'),
('KSJT', 'San Angelo Regional Mathis Field - San Angelo (KSJT)'),
('KSJX', 'Beaver Island Airport - Beaver Island (KSJX)'),
('KSKX', 'Taos Regional Airport - Taos (KSKX)'),
('KSLC', 'Salt Lake City International Airport - Salt Lake City (KSLC)'),
('KSLE', 'Salem-Willamette Valley Airport/McNary Field - Salem (KSLE)'),
('KSLK', 'Adirondack Regional Airport - Saranac Lake (KSLK)'),
('KSLN', 'Salina Municipal Airport - Salina (KSLN)'),
('KSMF', 'Sacramento International Airport - Sacramento (KSMF)'),
('KSMN', 'Lemhi County Airport - Salmon (KSMN)'),
('KSMX', 'Santa Maria Public Airport Captain G Allan Hancock Field - Santa Maria (KSMX)'),
('KSNA', 'John Wayne Orange County International Airport - Santa Ana (KSNA)'),
('KSOW', 'Show Low Regional Airport - Show Low (KSOW)'),
('KSPI', 'Abraham Lincoln Capital Airport - Springfield (KSPI)'),
('KSPS', 'Wichita Falls Municipal Airport / Sheppard Air Force Base - Wichita Falls (KSPS)'),
('KSQL', 'San Carlos Airport - San Carlos (KSQL)'),
('KSRQ', 'Sarasota Bradenton International Airport - Sarasota/Bradenton (KSRQ)'),
('KSTC', 'Saint Cloud Regional Airport - Saint Cloud (KSTC)'),
('KSTL', 'St. Louis Lambert International Airport - St Louis (KSTL)'),
('KSTS', 'Charles M. Schulz Sonoma County Airport - Santa Rosa (KSTS)'),
('KSUN', 'Friedman Memorial Airport - Hailey (KSUN)'),
('KSUX', 'Sioux Gateway Airport / Brigadier General Bud Day Field - Sioux City (KSUX)'),
('KSVC', 'Grant County Airport - Silver City (KSVC)'),
('KSWF', 'New York Stewart International Airport - Newburgh (KSWF)'),
('KSWO', 'Stillwater Regional Airport - Stillwater (KSWO)'),
('KSYR', 'Syracuse Hancock International Airport - Syracuse (KSYR)'),
('KTBN', 'Waynesville-St. Robert Regional Airport-Forney Field - Fort Leonard Wood (KTBN)'),
('KTEB', 'Teterboro Airport - Teterboro (KTEB)'),
('KTEX', 'Telluride Regional Airport - Telluride (KTEX)'),
('KTIW', 'Tacoma Narrows Airport - Tacoma (KTIW)'),
('KTLH', 'Tallahassee Regional Airport - Tallahassee (KTLH)'),
('KTOL', 'Eugene F. Kranz Toledo Express Airport - Toledo (KTOL)'),
('KTPA', 'Tampa International Airport - Tampa (KTPA)'),
('KTRI', 'Tri-Cities Regional TN/VA Airport - Blountville (KTRI)'),
('KTRK', 'Truckee Tahoe Airport - Truckee (KTRK)'),
('KTTN', 'Trenton Mercer Airport - Ewing Township (KTTN)'),
('KTUL', 'Tulsa International Airport - Tulsa (KTUL)'),
('KTUP', 'Tupelo Regional Airport - Tupelo (KTUP)'),
('KTUS', 'Tucson International Airport / Morris Air National Guard Base - Tucson (KTUS)'),
('KTVC', 'Cherry Capital Airport - Traverse City (KTVC)'),
('KTVF', 'Thief River Falls Regional Airport - Thief River Falls (KTVF)'),
('KTWF', 'Joslin Field Magic Valley Regional Airport - Twin Falls (KTWF)'),
('KTXK', 'Texarkana Regional Airport (Webb Field) - Texarkana (KTXK)'),
('KTYR', 'Tyler Pounds Regional Airport - Tyler (KTYR)'),
('KTYS', 'McGhee Tyson Airport - Alcoa (KTYS)'),
('KUIN', 'Quincy Regional Airport Baldwin Field - Quincy (KUIN)'),
('KUNV', 'State College Regional Airport - State College (KUNV)'),
('KUUU', 'Newport State Airport - Newport (KUUU)'),
('KVCT', 'Victoria Regional Airport - Victoria (KVCT)'),
('KVEL', 'Vernal Regional Airport - Vernal (KVEL)'),
('KVLD', 'Valdosta Regional Airport - Valdosta (KVLD)'),
('KVPS', 'Destin-Fort Walton Beach Airport - Valparaiso (KVPS)'),
('KVRB', 'Vero Beach Regional Airport - Vero Beach (KVRB)'),
('KWST', 'Westerly State Airport - Westerly (KWST)'),
('KWYS', 'Yellowstone Airport - West Yellowstone (KWYS)'),
('KXNA', 'Northwest Arkansas National Airport - Fayetteville/Springdale/Rogers (KXNA)'),
('KXWA', 'Williston Basin International Airport - Williston (KXWA)'),
('KYKM', 'Yakima Air Terminal McAllister Field - Yakima (KYKM)'),
('ME55', 'Vinalhaven Airport - Vinalhaven (ME55)'),
('KMYK', 'May Creek Airport - May Creek (KMYK)'),
('ORI', 'Port Lions Airport - Port Lions (ORI)'),
('PAAK', 'Atka Airport - Atka (PAAK)'),
('PABA', 'Barter Island Long Range Radar Station Airport - Barter Island (PABA)'),
('PABE', 'Bethel Airport - Bethel (PABE)'),
('PABL', 'Buckland Airport - Buckland (PABL)'),
('PABR', 'Wiley Post Will Rogers Memorial Airport - Utqiagvik (PABR)'),
('PABT', 'Bettles Airport - Bettles (PABT)'),
('PACD', 'Cold Bay Airport - Cold Bay (PACD)'),
('URWA', 'Astrakhan Narimanovo Boris M. Kustodiev International Airport - Astrakhan (URWA)'),
('URWI', 'Elista Airport - Elista (URWI)'),
('URWW', 'Volgograd International Airport - Volgograd (URWW)'),
('USCC', 'Chelyabinsk Balandino Airport - Chelyabinsk (USCC)'),
('USCM', 'Magnitogorsk International Airport - Magnitogorsk (USCM)'),
('USDA', 'Sabetta International Airport - Sabetta (USDA)'),
('USDB', 'Bovanenkovo Airport - Bovanenkovo (USDB)'),
('USDD', 'Salekhard Airport - Salekhard (USDD)'),
('USDO', 'Tolka Airport - Tolka (USDO)'),
('USHH', 'Khanty Mansiysk Airport - Khanty-Mansiysk (USHH)'),
('UA36', 'Lugovoy Airport - Lugovoy (UA36)'),
('USHN', 'Nyagan Airport - Nyagan (USHN)'),
('USHQ', 'Beloyarskiy Airport - Biełojarskij (USHQ)'),
('USHS', 'Sovetskiy Airport - Sovetskiy (USHS)'),
('USHU', 'Uray Airport - Uray (USHU)'),
('USII', 'Izhevsk Airport - Izhevsk (USII)'),
('USKK', 'Pobedilovo Airport - Kirov (USKK)'),
('USMM', 'Nadym Airport - Nadym (USMM)'),
('USMU', 'Novy Urengoy Airport - Novy Urengoy (USMU)'),
('USNN', 'Nizhnevartovsk Airport - Nizhnevartovsk (USNN)'),
('USPP', 'Perm International Airport - Perm (USPP)'),
('USRK', 'Kogalym International Airport - Kogalym (USRK)'),
('USRN', 'Nefteyugansk Airport - Nefteyugansk (USRN)'),
('USRO', 'Noyabrsk Airport - Noyabrsk (USRO)'),
('USRR', 'Surgut Airport - Surgut (USRR)'),
('USSS', 'Koltsovo Airport - Yekaterinburg (USSS)'),
('USTJ', 'Remezov Airport - Tobolsk (USTJ)'),
('USTR', 'Roshchino International Airport - Tyumen (USTR)'),
('USUU', 'Kurgan Airport - Kurgan (USUU)'),
('UUBA', 'Kostroma Sokerkino Airport - Kostroma (UUBA)'),
('UUBI', 'Ivanovo South Airport - Ivanovo (UUBI)'),
('UUBK', 'Staroselye Airport - Rybinsk (UUBK)'),
('UUBP', 'Bryansk Airport - Bryansk (UUBP)'),
('UUBW', 'Zhukovsky International Airport - Moscow (UUBW)'),
('UUDD', 'Domodedovo International Airport - Moscow (UUDD)'),
('UUEE', 'Sheremetyevo International Airport - Moscow (UUEE)'),
('UUOB', 'Belgorod International Airport - Belgorod (UUOB)'),
('UUOK', 'Kursk East Airport - Kursk (UUOK)'),
('UUOL', 'Lipetsk Airport - Lipetsk (UUOL)'),
('UUOO', 'Voronezh International Airport - Voronezh (UUOO)'),
('UUWW', 'Vnukovo International Airport - Moscow (UUWW)'),
('UUYH', 'Ukhta Airport - Ukhta (UUYH)'),
('UUYP', 'Pechora Airport - Pechora (UUYP)'),
('UUYS', 'Usinsk Airport - Usinsk (UUYS)'),
('UUYW', 'Vorkuta Airport - Vorkuta (UUYW)'),
('UUYY', 'Syktyvkar Airport - Syktyvkar (UUYY)'),
('UWGG', 'Nizhny Novgorod / Strigino International Airport - Nizhny Novgorod (UWGG)'),
('UWKB', 'Bugulma Airport - Bugulma (UWKB)'),
('UWKD', 'Kazan International Airport - Kazan (UWKD)'),
('UWKE', 'Begishevo Airport - Nizhnekamsk (UWKE)'),
('UWKS', 'Cheboksary Airport - Cheboksary (UWKS)'),
('UWLL', 'Ulyanovsk Baratayevka Airport - Ulyanovsk (UWLL)'),
('UWLW', 'Ulyanovsk East Airport - Cherdakly (UWLW)'),
('UWOH', 'Kvarkeno Airport - Kvarkeno (UWOH)'),
('UWOO', 'Orenburg Central Airport - Orenburg (UWOO)'),
('UWOR', 'Orsk Airport - Orsk (UWOR)'),
('UHSS', 'Svetlyy Airport - Swietły (UHSS)'),
('UWPP', 'Penza Airport - Penza (UWPP)'),
('UWPS', 'Saransk Airport - Saransk (UWPS)'),
('UWSB', 'Balakovo Airport - Balakovo (UWSB)'),
('UWSG', 'Gagarin International Airport - Saratov (UWSG)'),
('UWUU', 'Ufa International Airport - Ufa (UWUU)'),
('UWWW', 'Kurumoch International Airport - Samara (UWWW)'),
('HRYR', 'Kigali International Airport - Kigali (HRYR)'),
('HRZA', 'Kamembe Airport - Kamembe (HRZA)'),
('OEBT', 'Batha Airport - Batha (OEBT)'),
('OEAB', 'Abha International Airport - Abha (OEAB)'),
('OEAH', 'Al-Ahsa International Airport - Hofuf (OEAH)'),
('OEAO', 'Majeed Bin Abdulaziz Airport - Al Ula (OEAO)'),
('OEBA', 'King Saud Bin Abdulaziz (Al Baha) Airport - Al-Baha (OEBA)'),
('OEBH', 'Bisha Airport - Bisha (OEBH)'),
('OEDF', 'King Fahd International Airport - Ad Dammam (OEDF)'),
('OEDM', 'King Salman Abdulaziz Airport - Dawadmi (OEDM)'),
('OEGN', 'Jizan Regional Airport / King Abdullah bin Abdulaziz Airport - Jizan (OEGN)'),
('OEGS', 'Gassim Airport - Buraidah (OEGS)'),
('OEGT', 'Gurayat Domestic Airport - Gurayat (OEGT)'),
('OEHL', 'Ha''il Airport - Ha''il (OEHL)'),
('OEJN', 'King Abdulaziz International Airport - Jeddah (OEJN)'),
('OEKK', 'King Khaled Military City Airport - King Khaled Military City (OEKK)'),
('OEMA', 'Prince Mohammad Bin Abdulaziz Airport - Medina (OEMA)'),
('OENG', 'Najran Domestic Airport - Najran (OENG)'),
('OENN', 'Neom Bay Airport - Sharma (OENN)'),
('OEPA', 'Al Qaisumah/Hafr Al Batin Airport - Qaisumah (OEPA)'),
('OERF', 'Rafha Domestic Airport - Rafha (OERF)'),
('OERK', 'King Khaled International Airport - Riyadh (OERK)'),
('OERR', 'Arar Domestic Airport - Arar (OERR)'),
('OESH', 'Sharurah Domestic Airport - Sharurah (OESH)'),
('OESK', 'Al-Jawf Domestic Airport - Al-Jawf (OESK)'),
('OETB', 'Tabuk Airport - Tabuk (OETB)'),
('OETF', 'Ta’if Regional Airport - Ta’if (OETF)'),
('OETR', 'Turaif Domestic Airport - Turaif (OETR)'),
('OEWD', 'Wadi Al Dawasir Domestic Airport - Wadi Al Dawasir (OEWD)'),
('OEWJ', 'Al Wajh Domestic Airport - Al Wajh (OEWJ)'),
('OEYN', 'Prince Abdul Mohsin bin Abdulaziz International Airport / Yanbu Airport - Yanbu (OEYN)'),
('OERS', 'Red Sea International Airport - Hanak (OERS)'),
('AGGA', 'Gwaunaru''u Airport - Auki (AGGA)'),
('AGGB', 'Bellona/Anua Airport - Anua (AGGB)'),
('AGGC', 'Choiseul Bay Airport - Choiseul Bay (AGGC)'),
('AGGE', 'Ballalae Airport - Ballalae (AGGE)'),
('AGGF', 'Fera/Maringe Airport - Fera Island (AGGF)'),
('AGGH', 'Honiara International Airport - Honiara (AGGH)'),
('AGGK', 'Ngorangora Airport - Kirakira (AGGK)'),
('AGGL', 'Santa Cruz/Graciosa Bay/Luova Airport - Santa Cruz/Graciosa Bay/Luova (AGGL)'),
('AGGM', 'Munda Airport - Munda (AGGM)'),
('AGGN', 'Nusatupe Airport - Gizo (AGGN)'),
('AGGO', 'Mono Airport - Stirling Island (AGGO)'),
('AGGR', 'Rennell/Tingoa Airport - Rennell Island (AGGR)'),
('AGGT', 'Santa Ana Airport - Santa Ana Island (AGGT)'),
('AGGU', 'Marau Airport - Marau (AGGU)'),
('AGGV', 'Suavanao Airport - Suavanao (AGGV)'),
('AGGY', 'Yandina Airport - Yandina (AGGY)'),
('AGKG', 'Kaghau Airport - Kagau Island (AGKG)'),
('AGOB', 'Manaoba Airport - Manaoba (AGOB)'),
('AGOK', 'Gatokae Aerodrome - Gatokae (AGOK)'),
('AGRM', 'Ramata Airport - Ramata (AGRM)'),
('FSAL', 'Alphonse Airport - Alphonse Island (FSAL)'),
('FSIA', 'Seychelles International Airport - Mahe Island (FSIA)'),
('FSPP', 'Praslin Island Airport - Praslin Island (FSPP)'),
('HSDN', 'Dongola Airport - Dongola (HSDN)'),
('HSFS', 'El Fasher Airport - El Fasher (HSFS)'),
('HSKA', 'Kassala Airport - Kassala (HSKA)'),
('HSNN', 'Nyala Airport - Nyala (HSNN)'),
('HSOB', 'El-Obeid Airport - El-Obeid (HSOB)'),
('HSPN', 'Port Sudan New International Airport - Port Sudan (HSPN)'),
('HSSK', 'Khartoum International Airport - Khartoum (HSSK)'),
('ESDF', 'Ronneby Airport - Ronneby (ESDF)'),
('ESGG', 'Göteborg Landvetter Airport - Göteborg (ESGG)'),
('ESGJ', 'Jönköping Airport - Jönköping (ESGJ)'),
('ESGT', 'Trollhättan-Vänersborg Airport - Trollhättan (ESGT)'),
('ESKM', 'Mora Airport - Mora (ESKM)'),
('ESKN', 'Stockholm Skavsta Airport - Nyköping (ESKN)'),
('ESKS', 'Scandinavian Mountains Airport - Malung-Sälen (ESKS)'),
('ESMQ', 'Kalmar Airport - Kalmar (ESMQ)'),
('ESMS', 'Malmö Sturup Airport - Malmö (ESMS)'),
('ESMT', 'Halmstad Airport - Halmstad (ESMT)'),
('ESMX', 'Växjö Kronoberg Airport - Växjö (ESMX)'),
('ESND', 'Sveg Airport - Sveg (ESND)'),
('ESNG', 'Gällivare Airport - Gällivare (ESNG)'),
('ESNK', 'Kramfors-Solleftea Höga Kusten Airport - Nyland (ESNK)'),
('ESNL', 'Lycksele Airport - Lycksele (ESNL)'),
('ESNN', 'Sundsvall-Härnösand Airport - Sundsvall/ Härnösand (ESNN)'),
('ESNO', 'Örnsköldsvik Airport - Örnsköldsvik (ESNO)'),
('ESNQ', 'Kiruna Airport - Kiruna (ESNQ)'),
('ESNS', 'Skelleftea Airport - Skelleftea (ESNS)'),
('ESNU', 'Umea Airport - Umea (ESNU)'),
('ESNV', 'Vilhelmina South Lapland Airport - Vilhelmina (ESNV)'),
('ESNX', 'Arvidsjaur Airport - Arvidsjaur (ESNX)'),
('ESNZ', 'Åre Östersund Airport - Östersund (ESNZ)'),
('ESOE', 'Örebro Airport - Örebro (ESOE)'),
('ESOH', 'Hagfors Airport - Hagfors (ESOH)'),
('ESOK', 'Karlstad Airport - Karlstad (ESOK)'),
('ESOW', 'Stockholm Västeras Airport - Stockholm / Västeras (ESOW)'),
('ESPA', 'Lulea Airport - Lulea (ESPA)'),
('ESSA', 'Stockholm-Arlanda Airport - Stockholm (ESSA)'),
('ESSB', 'Stockholm-Bromma Airport - Stockholm (ESSB)'),
('ESSD', 'Dala Airport - Borlange (ESSD)'),
('ESSL', 'Linköping City Airport - Linköping (ESSL)'),
('ESSP', 'Norrköping Airport - Norrköping (ESSP)'),
('ESST', 'Torsby Airport - Torsby (ESST)'),
('ESSV', 'Visby Airport - Visby (ESSV)'),
('ESTA', 'Ängelholm-Helsingborg Airport - Ängelholm (ESTA)'),
('ESUP', 'Pajala Airport - Pajala (ESUP)'),
('ESUT', 'Hemavan Airport - Hemavan (ESUT)'),
('WSSL', 'Seletar Airport - Seletar (WSSL)'),
('WSSS', 'Singapore Changi Airport - Singapore (WSSS)'),
('FHAW', 'RAF Ascension Island - Cat Hill (FHAW)'),
('FHSH', 'Saint Helena Airport - Longwood (FHSH)'),
('LJLJ', 'Ljubljana Jože Pučnik Airport - Zgornji Brnik (LJLJ)'),
('LZIB', 'M. R. Štefánik Airport - Bratislava (LZIB)'),
('LZKZ', 'Košice International Airport - Košice (LZKZ)'),
('LZSL', 'Sliač Airport - Sliač (LZSL)'),
('LZTT', 'Poprad-Tatry Airport - Poprad (LZTT)'),
('GFLL', 'Lungi International Airport - Freetown (Lungi-Town) (GFLL)'),
('GOBD', 'Blaise Diagne International Airport - Dakar (GOBD)'),
('GOGS', 'Cap Skirring Airport - Cap Skirring (GOGS)'),
('HCMF', 'Bosaso / Bender Qassim International Airport - Bosaso (HCMF)'),
('HCMH', 'Egal International Airport - Hargeisa (HCMH)'),
('HCMI', 'Berbera Airport - Berbera (HCMI)'),
('HCMM', 'Aden Adde International Airport - Mogadishu (HCMM)'),
('HCMN', 'Beledweyne Airport - Beledweyne (HCMN)'),
('HCMR', 'Galcaio Airport - Galcaio (HCMR)'),
('HCMW', 'Garowe Airport - Garowe (HCMW)'),
('SMAF', 'Afobakka Airstrip - Afobakka (SMAF)'),
('SMCT', 'Cottica Airstrip - Lawa Cottica (SMCT)'),
('SMDA', 'Drietabbetje Airport - Drietabbetje (SMDA)'),
('SMGH', 'Godo Holo Airstrip - Pikienkondre of Miranda (SMGH)'),
('SMJP', 'Johan Adolf Pengel International Airport - Zandery (SMJP)'),
('SMMO', 'Moengo Airstrip - Moengo (SMMO)'),
('SMTA', 'Tabiki Airstrip - Benzdorp (SMTA)'),
('SMWA', 'Wageningen Airstrip - Wageningen (SMWA)'),
('SMZO', 'Zorg en Hoop Airport - Paramaribo (SMZO)'),
('HJJJ', 'Juba International Airport - Juba (HJJJ)'),
('FPPR', 'Principe Airport - Sao Tomé e Príncipe (FPPR)'),
('FPST', 'Sao Tomé International Airport - Sao Tomé (FPST)'),
('MSLP', 'Monsenor Óscar Arnulfo Romero International Airport - San Salvador (San Luis Talpa) (MSLP)'),
('MSSS', 'Ilopango International Airport - San Salvador (MSSS)'),
('TNCM', 'Princess Juliana International Airport - Sint Maarten (TNCM)'),
('OSAP', 'Aleppo International Airport - Aleppo (OSAP)'),
('OSDI', 'Damascus International Airport - Damascus (OSDI)'),
('OSKL', 'Qamishli Airport - Qamishly (OSKL)'),
('FDSK', 'King Mswati III International Airport - Mpaka (FDSK)'),
('MBGT', 'JAGS McCartney International Airport - Cockburn Town (MBGT)'),
('MBNC', 'North Caicos Airport - North Caicos (MBNC)'),
('MBPV', 'Providenciales International Airport - Providenciales (MBPV)'),
('MBSC', 'South Caicos Airport - South Caicos (MBSC)'),
('MBSY', 'Salt Cay Airport - Salt Cay (MBSY)'),
('FTTC', 'Abeche Airport - Abeche (FTTC)'),
('FTTJ', 'N''Djamena International Airport - N''Djamena (FTTJ)'),
('DXXX', 'Lomé–Tokoin International Airport - Lomé (DXXX)'),
('VTBD', 'Don Mueang International Airport - Bangkok (VTBD)'),
('VTBO', 'Trat Airport - Laem Ngop (VTBO)'),
('VTBS', 'Suvarnabhumi Airport - Bangkok (VTBS)'),
('VTBU', 'U-Tapao International Airport - Rayong (VTBU)'),
('VTCC', 'Chiang Mai International Airport - Chiang Mai (VTCC)'),
('VTCH', 'Mae Hong Son Airport - Mae Hong Son (VTCH)'),
('VTCL', 'Lampang Airport -  Lampang (VTCL)'),
('VTCN', 'Nan Airport - Nan (VTCN)'),
('VTCO', 'Lamphun Airport - Lamphun  (VTCO)'),
('VTCT', 'Mae Fah Luang - Chiang Rai International Airport - Chiang Rai (VTCT)'),
('VTPB', 'Phetchabun Airport - Phetchabun (VTPB)'),
('VTPH', 'Hua Hin Airport - Hua Hin (VTPH)'),
('VTPM', 'Mae Sot Airport - Mae Sot (VTPM)'),
('VTPO', 'Sukhothai Airport - Sukhothai (VTPO)'),
('VTPP', 'Phitsanulok Airport - Phitsanulok (VTPP)'),
('VTSB', 'Surat Thani Airport - Surat Thani (VTSB)'),
('VTSC', 'Narathiwat Airport - Narathiwat (VTSC)'),
('VTSE', 'Chumphon Airport - Chumphon (VTSE)'),
('VTSF', 'Nakhon Si Thammarat Airport - Nakhon Si Thammarat (VTSF)'),
('VTSG', 'Krabi Airport - Krabi (VTSG)'),
('VTSM', 'Samui Airport - Na Thon (Ko Samui Island) (VTSM)'),
('VTSP', 'Phuket International Airport - Phuket (VTSP)'),
('VTSR', 'Ranong Airport - Ranong (VTSR)'),
('VTSS', 'Hat Yai International Airport - Hat Yai (VTSS)'),
('VTST', 'Trang Airport - Trang (VTST)'),
('VTUD', 'Udon Thani Airport - Udon Thani (VTUD)'),
('VTUI', 'Sakon Nakhon Airport - Sakon Nakhon (VTUI)'),
('VTUJ', 'Surin Airport - Surin (VTUJ)'),
('VTUK', 'Khon Kaen Airport - Khon Kaen (VTUK)'),
('VTUL', 'Loei Airport -  Loei (VTUL)'),
('VTUO', 'Buri Ram Airport - Buriram (VTUO)'),
('VTUU', 'Ubon Ratchathani Airport - Ubon Ratchathani (VTUU)'),
('VTUV', 'Roi Et Airport - Roi Et (VTUV)'),
('VTUW', 'Nakhon Phanom Airport - Nakhon Phanom (VTUW)'),
('UTDD', 'Dushanbe International Airport - Dushanbe (UTDD)'),
('UTDK', 'Kulob Airport - Kulyab (UTDK)'),
('UTDL', 'Khujand Airport - Khujand (UTDL)'),
('UTDT', 'Qurghonteppa International Airport - Kurgan-Tyube (UTDT)'),
('WPDL', 'Presidente Nicolau Lobato International Airport - Dili (WPDL)'),
('UTAN', 'Balkanabat Airport - Balkanabat (UTAN)'),
('UTAA', 'Ashgabat International Airport - Ashgabat (UTAA)'),
('UTAK', 'Turkmenbashi International Airport - Turkmenbashi (UTAK)'),
('UTAM', 'Mary International Airport - Mary (UTAM)'),
('UTAT', 'Daşoguz Airport - Daşoguz (UTAT)'),
('UTAV', 'Türkmenabat International Airport - Türkmenabat (UTAV)'),
('DTKA', 'Tabarka-Ain Draham International Airport - Tabarka (DTKA)'),
('DTMB', 'Monastir Habib Bourguiba International Airport - Monastir (DTMB)'),
('DTNH', 'Enfidha - Hammamet International Airport - Enfidha (DTNH)'),
('DTTA', 'Tunis Carthage International Airport - Tunis (DTTA)'),
('DTTF', 'Gafsa Ksar International Airport - Gafsa (DTTF)'),
('DTTG', 'Gabes Matmata International Airport - Gabes (DTTG)'),
('DTTJ', 'Djerba Zarzis International Airport - Mellita (DTTJ)'),
('DTTX', 'Sfax Thyna International Airport - Sfax (DTTX)'),
('DTTZ', 'Tozeur Nefta International Airport - Tozeur (DTTZ)'),
('NFTE', 'Kaufana Airport - Eua Island (NFTE)'),
('NFTF', 'Fua''amotu International Airport - Nuku''alofa (NFTF)'),
('NFTL', 'Lifuka Island Airport - Lifuka (NFTL)'),
('NFTP', 'Kuini Lavenia Airport - Niuatoputapu (NFTP)'),
('NFTV', 'Vava''u International Airport - Vava''u Island (NFTV)'),
('LTAC', 'Ankara Esenboga Airport - Ankara (LTAC)'),
('LTAF', 'Adana Şakirpaşa Airport - Seyhan (LTAF)'),
('LTAI', 'Antalya International Airport - Antalya (LTAI)'),
('LTAJ', 'Gaziantep International Airport - Gaziantep (LTAJ)'),
('LTAN', 'Konya Airport - Konya (LTAN)'),
('LTAO', 'Malatya Tulga Airport - Malatya (LTAO)'),
('LTAP', 'Amasya Merzifon Airport - Amasya (LTAP)'),
('LTAR', 'Sivas Nuri Demirag Airport - Sivas (LTAR)'),
('LTAS', 'Zonguldak Çaycuma Airport - Zonguldak (LTAS)'),
('LTAT', 'Malatya Erhaç Airport - Malatya (LTAT)'),
('LTAU', 'Kayseri Erkilet Airport - Kayseri (LTAU)'),
('LTAW', 'Tokat Airport - Tokat (LTAW)'),
('LTAY', 'Çardak Airport - Denizli (LTAY)'),
('LTAZ', 'Nevşehir Kapadokya Airport - Nevşehir (LTAZ)'),
('LTBF', 'Balikesir  Airport - Balikesir  (LTBF)'),
('LTBH', 'Çanakkale Airport - Çanakkale (LTBH)'),
('LTBJ', 'Adnan Menderes International Airport - Gaziemir (LTBJ)'),
('LTBR', 'Bursa Yenişehir Airport - Yenişehir (LTBR)'),
('LTBS', 'Dalaman International Airport - Dalaman (LTBS)'),
('LTBU', 'Tekirdag Çorlu Airport - Çorlu (LTBU)'),
('LTBY', 'Anadolu Airport - Eskişehir (LTBY)'),
('LTBZ', 'Zafer Airport - Altintaş (LTBZ)'),
('LTCA', 'Elazig Airport - Elazig (LTCA)'),
('LTCB', 'Ordu–Giresun Airport - Ordu (LTCB)'),
('LTCC', 'Diyarbakir Airport - Diyarbakir (LTCC)'),
('LTCD', 'Erzincan Airport - Erzincan (LTCD)'),
('LTCE', 'Erzurum International Airport - Erzurum (LTCE)'),
('LTCF', 'Kars Airport - Kars (LTCF)'),
('LTCG', 'Trabzon International Airport - Trabzon (LTCG)'),
('LTCI', 'Van Ferit Melen Airport - Van (LTCI)'),
('LTCJ', 'Batman Airport - Batman (LTCJ)'),
('LTCK', 'Muş Airport - Muş (LTCK)'),
('LTCM', 'Sinop Airport - Sinop (LTCM)'),
('LTCN', 'Kahramanmaraş Airport - Kahramanmaraş (LTCN)'),
('LTCO', 'Atatürk Airport - Atatürk (LTCO)'),
('LTCP', 'Adiyaman Airport - Adiyaman (LTCP)')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
