-- airports seed batch 6/11
INSERT INTO public.airports (code, name) VALUES
('ZMMG', 'Mandalgobi Airport - Mandalgobi (ZMMG)'),
('ZMMN', 'Mörön Airport - Mörön (ZMMN)'),
('ZMUG', 'Ulaangom Airport - Ulaangom (ZMUG)'),
('ZMUL', 'Ölgii Mongolei Airport - Ölgii (ZMUL)'),
('VMMC', 'Macau International Airport - Nossa Senhora do Carmo (VMMC)'),
('PGRO', 'Rota International Airport - Rota Island (PGRO)'),
('PGSN', 'Saipan International Airport - I Fadang, Saipan (PGSN)'),
('PGWT', 'Tinian International Airport - Tinian Island (PGWT)'),
('TFFF', 'Martinique Aimé Césaire International Airport - Fort-de-France (TFFF)'),
('GQNO', 'Nouakchott–Oumtounsy International Airport - Nouakchott (GQNO)'),
('GQPP', 'Nouadhibou International Airport - Nouadhibou (GQPP)'),
('GQPZ', 'Tazadit Airport - Zouérate (GQPZ)'),
('TRPG', 'John A. Osborne Airport - Gerald''s Park (TRPG)'),
('LMML', 'Malta International Airport - Valletta (LMML)'),
('FIMP', 'Sir Seewoosagur Ramgoolam International Airport - Plaine Magnien (FIMP)'),
('FIMR', 'Sir Charles Gaetan Duval Airport - Port Mathurin (FIMR)'),
('VRCF', 'Funadhoo Airport - Funadhoo (VRCF)'),
('VRQF', 'Faresmaathoda Airport - Faresmaathodaa (VRQF)'),
('VRAH', 'Hoarafushi Airport - Hoarafushi (VRAH)'),
('VRBK', 'Kulhudhuffushi Airport - Kulhudhuffushi (VRBK)'),
('VRDA', 'Maafaru International Airport - Noonu Atoll (VRDA)'),
('VRMD', 'Dharavandhoo Airport - Baa Atoll (VRMD)'),
('VRMG', 'Gan International Airport - Gan (VRMG)'),
('VRMH', 'Hanimaadhoo Airport - Haa Dhaalu Atoll (VRMH)'),
('VRMK', 'Kadhdhoo Airport - Kadhdhoo (VRMK)'),
('VRMM', 'Malé International Airport - Malé (VRMM)'),
('VRMO', 'Kooddoo Airport - Huvadhu Atoll (VRMO)'),
('VRMT', 'Kaadedhdhoo Airport - Huvadhu Atoll (VRMT)'),
('VRMV', 'Villa International Airport Maamigili - Maamigili (VRMV)'),
('VRNT', 'Thimarafushi Airport - Thimarafushi (VRNT)'),
('VRQM', 'Maavaarulaa Airport - Maavaarulu (VRQM)'),
('FWCL', 'Chileka International Airport - Blantyre (FWCL)'),
('FWKI', 'Kamuzu International Airport - Lumbadzi (FWKI)'),
('MMCD', 'Isla Cedros Airport - Cedros Island (MMCD)'),
('MM52', 'Camaguey-Campo Cuatro Milpas Airport - Guasave (MM52)'),
('MMAA', 'General Juan N. Álvarez International Airport - Acapulco (MMAA)'),
('MMAS', 'Jesús Terán Peredo International Airport - Aguascalientes (MMAS)'),
('MMBT', 'Bahías de Huatulco International Airport - Huatulco (MMBT)'),
('MMCE', 'Ciudad del Carmen International Airport - Ciudad del Carmen (MMCE)'),
('MMCL', 'Bachigualato Federal International Airport - Culiacán (MMCL)'),
('MMCM', 'Chetumal International Airport - Chetumal (MMCM)'),
('MMCN', 'Ciudad Obregón International Airport - Ciudad Obregón (MMCN)'),
('MMCP', 'Ingeniero Alberto Acuna Ongay International Airport - Campeche (MMCP)'),
('MMCS', 'Abraham González International Airport - Ciudad Juárez (MMCS)'),
('MMCU', 'General Roberto Fierro Villalobos International Airport - Chihuahua (MMCU)'),
('MMCV', 'General Pedro Jose Mendez International Airport - Ciudad Victoria (MMCV)'),
('MMCZ', 'Cozumel International Airport - Cozumel (MMCZ)'),
('MMDA', 'Ciudad Constitución National Airport - Comondú (MMDA)'),
('MMDO', 'General Guadalupe Victoria International Airport - Durango (MMDO)'),
('MMEP', 'Amado Nervo National Airport - Tepic (MMEP)'),
('MMGL', 'Guadalajara International Airport - Guadalajara (MMGL)'),
('MMGM', 'General José María Yánez International Airport - Guaymas (MMGM)'),
('MMGR', 'Guerrero Negro Airport - San Quintín (MMGR)'),
('MMHO', 'General Ignacio P. Garcia International Airport - Hermosillo (MMHO)'),
('MMIA', 'Licenciado Miguel de la Madrid International Airport - Colima (MMIA)'),
('MMIT', 'General Antonio Cárdenas Rodríguez National Airport / Ixtepec Air Base - Ixtepec (MMIT)'),
('MMLM', 'Valle del Fuerte International Airport - Los Mochis (MMLM)'),
('MMLO', 'Del Bajío International Airport - Silao (MMLO)'),
('MMLP', 'Manuel Márquez de León International Airport - La Paz (MMLP)'),
('MMLT', 'Loreto International Airport - Loreto (MMLT)'),
('MMMA', 'General Servando Canales International Airport - Matamoros (MMMA)'),
('MMMD', 'Manuel Crescencio Rejón International Airport - Mérida (MMMD)'),
('MMML', 'General Rodolfo Sánchez Taboada International Airport - Mexicali (MMML)'),
('MMMM', 'General Francisco J. Mujica International Airport - Morelia (MMMM)'),
('MMMT', 'Minatitlán/Coatzacoalcos International Airport - Cosoleacaque (MMMT)'),
('MMMX', 'Benito Juárez International Airport - Ciudad de México (MMMX)'),
('MMMY', 'Monterrey International Airport - Monterrey (MMMY)'),
('MMMZ', 'General Rafael Buelna International Airport - Mazatlán (MMMZ)'),
('MMNL', 'Quetzalcóatl International Airport - Nuevo Laredo (MMNL)'),
('MMOX', 'Xoxocotlán International Airport - Oaxaca (MMOX)'),
('MMPA', 'El Tajín National Airport - Poza Rica (MMPA)'),
('MMPB', 'Hermanos Serdán International Airport - Puebla (MMPB)'),
('MMPE', 'Mar de Cortés International Airport - Puerto Penasco (MMPE)'),
('MMPG', 'Piedras Negras International Airport - Piedras Negras (MMPG)'),
('MMPN', 'Uruapan - Licenciado y General Ignacio Lopez Rayon International Airport - Uruapan (MMPN)'),
('MMPR', 'Puerto Vallarta International Airport - Puerto Vallarta (MMPR)'),
('MMPS', 'Puerto Escondido International Airport - Puerto Escondido (MMPS)'),
('MMQT', 'Querétaro Intercontinental Airport - Querétaro (MMQT)'),
('MMRX', 'General Lucio Blanco International Airport - Reynosa (MMRX)'),
('MMSD', 'Los Cabos International Airport - San José del Cabo (MMSD)'),
('MMSL', 'Cabo San Lucas International Airport - Cabo San Lucas (MMSL)'),
('MMSM', 'General Felipe Ángeles International Airport - Mexico City (MMSM)'),
('MMSP', 'Ponciano Arriaga International Airport - San Luis Potosí (MMSP)'),
('MMTC', 'Francisco Sarabia Tinoco International Airport - Torreón (MMTC)'),
('MMTG', 'Angel Albino Corzo International Airport - Tuxtla Gutiérrez (MMTG)'),
('MMTJ', 'General Abelardo L. Rodriguez International Airport - Tijuana (MMTJ)'),
('MMTL', 'Felipe Carrillo Puerto International Airport - Tulum (MMTL)'),
('MMTM', 'General Francisco Javier Mina International Airport - Tampico (MMTM)'),
('MMTO', 'Adolfo López Mateos International Airport - Toluca (MMTO)'),
('MMTP', 'Tapachula International Airport - Tapachula (MMTP)'),
('MMUN', 'Cancún International Airport - Cancún (MMUN)'),
('MMVA', 'Carlos Rovirosa Pérez International Airport - Villahermosa (MMVA)'),
('MMVR', 'General Heriberto Jara International Airport - Veracruz (MMVR)'),
('MMZC', 'General Leobardo C. Ruiz International Airport - Zacatecas (MMZC)'),
('MMZH', 'Ixtapa-Zihuatanejo International Airport - Ixtapa (MMZH)'),
('MMZO', 'Playa de Oro International Airport - Manzanillo (MMZO)'),
('WBGB', 'Bintulu Airport - Bintulu (WBGB)'),
('WBGF', 'Long Lellang Airport - Long Datih (WBGF)'),
('WBGG', 'Kuching International Airport - Kuching (WBGG)'),
('WBGI', 'Long Seridan Airport - Long Seridan (WBGI)'),
('WBGJ', 'Limbang Airport - Limbang (WBGJ)'),
('WBGK', 'Mukah Airport - Mukah (WBGK)'),
('WBGM', 'Marudi Airport - Marudi (WBGM)'),
('WBGQ', 'Bakalalan Airport - Bakalalan (WBGQ)'),
('WBGR', 'Miri Airport - Miri (WBGR)'),
('WBGS', 'Sibu Airport - Sibu (WBGS)'),
('WBGW', 'Lawas Airport - Lawas (WBGW)'),
('WBGZ', 'Bario Airport - Bario (WBGZ)'),
('WBKD', 'Lahad Datu Airport - Lahad Datu (WBKD)'),
('WBKK', 'Kota Kinabalu International Airport - Kota Kinabalu (WBKK)'),
('WBKL', 'Labuan Airport - Labuan (WBKL)'),
('WBKM', 'Tomanggong Airport - Tomanggong (WBKM)'),
('WBKS', 'Sandakan Airport - Sandakan (WBKS)'),
('WBKT', 'Kudat Airport - Kudat (WBKT)'),
('WBKW', 'Tawau Airport - Tawau (WBKW)'),
('WBMU', 'Mulu Airport - Mulu (WBMU)'),
('WMBT', 'Tioman Airport - Tioman Island (WMBT)'),
('WMKA', 'Sultan Abdul Halim Airport - Alor Satar (WMKA)'),
('WMKC', 'Sultan Ismail Petra Airport - Kota Baharu (WMKC)'),
('WMKD', 'Kuantan Airport - Kuantan (WMKD)'),
('WMKI', 'Sultan Azlan Shah Airport - Ipoh (WMKI)'),
('WMKJ', 'Senai International Airport - Johor Bahru (WMKJ)'),
('WMKK', 'Kuala Lumpur International Airport - Sepang (WMKK)'),
('WMKL', 'Langkawi International Airport - Langkawi (WMKL)'),
('WMKN', 'Sultan Mahmud Airport - Kuala Terengganu (WMKN)'),
('WMKP', 'Penang International Airport - Penang (WMKP)'),
('WMPA', 'Pulau Pangkor Airport - Pangkor Island (WMPA)'),
('WMSA', 'Sultan Abdul Aziz Shah International Airport - Subang (WMSA)'),
('FQBR', 'Beira Airport - Beira (FQBR)'),
('FQCH', 'Chimoio Airport - Chimoio (FQCH)'),
('FQIN', 'Inhambane Airport - Inhambane (FQIN)'),
('FQLC', 'Lichinga Airport - Lichinga (FQLC)'),
('FQMA', 'Maputo Airport - Maputo (FQMA)'),
('FQNP', 'Nampula Airport - Nampula (FQNP)'),
('FQPB', 'Pemba Airport - Pemba (FQPB)'),
('FQQL', 'Quelimane Airport - Quelimane (FQQL)'),
('FQTT', 'Chingozi Airport - Tete (FQTT)'),
('FQVL', 'Vilankulo Airport - Vilanculo (FQVL)'),
('FQXA', 'Xai-Xai Chongoene Airport - Xai-Xai (FQXA)'),
('FYHI', 'Halali Airport - Halali (FYHI)'),
('FYKM', 'Katima Mulilo Airport - Mpacha (FYKM)'),
('FYLZ', 'Luderitz Airport - Luderitz (FYLZ)'),
('FYOA', 'Ondangwa Airport - Ondangwa (FYOA)'),
('FYOG', 'Oranjemund Airport - Oranjemund (FYOG)'),
('FYRU', 'Rundu Airport - Rundu (FYRU)'),
('FYWB', 'Walvis Bay Airport - Rooikop (FYWB)'),
('FYWE', 'Eros Airport - Windhoek (FYWE)'),
('FYWH', 'Hosea Kutako International Airport - Windhoek (FYWH)'),
('NWWA', 'Tiga Airport - Tiga (NWWA)'),
('NWWC', 'Île Art - Waala Airport - Waala (NWWC)'),
('NWWD', 'Koné Airport - Koné (NWWD)'),
('NWWE', 'Île des Pins Airport - Île des Pins (NWWE)'),
('NWWK', 'Koumac Airport - Koumac (NWWK)'),
('NWWL', 'Lifou Airport - Lifou (NWWL)'),
('NWWM', 'Nouméa Magenta Airport - Nouméa (NWWM)'),
('NWWR', 'Maré Airport - Maré (NWWR)'),
('NWWU', 'Touho Airport - Touho (NWWU)'),
('NWWV', 'Ouvéa Airport - Ouvéa (NWWV)'),
('NWWW', 'La Tontouta International Airport - Nouméa (La Tontouta) (NWWW)'),
('DRRN', 'Diori Hamani International Airport - Niamey (DRRN)'),
('DRZA', 'Mano Dayak International Airport - Agadez (DRZA)'),
('DRZR', 'Zinder Airport - Zinder (DRZR)'),
('YSNF', 'Norfolk Island International Airport - Burnt Pine (YSNF)'),
('DNAA', 'Nnamdi Azikiwe International Airport - Abuja (DNAA)'),
('DNAI', 'Akwa Ibom International Airport - Uyo (DNAI)'),
('DNAK', 'Akure Airport - Akure (DNAK)'),
('DNAN', 'Chinua Achebe International Airport - Umuleri (DNAN)'),
('DNBC', 'Sir Abubakar Tafawa Balewa International Airport - Bauchi (DNBC)'),
('DNBE', 'Benin Airport - Benin (DNBE)'),
('DNBY', 'Bayelsa International Airport - Yenagoa (DNBY)'),
('DNCA', 'Margaret Ekpo International Airport - Calabar (DNCA)'),
('DNEN', 'Akanu Ibiam International Airport - Enegu (DNEN)'),
('DNGO', 'Gombe Lawanti International Airport - Gombe (DNGO)'),
('DNIB', 'Ibadan Airport - Ibadan (DNIB)'),
('DNIL', 'Ilorin International Airport - Ilorin (DNIL)'),
('DNIM', 'Sam Mbakwe International Airport - Owerri (DNIM)'),
('DNJO', 'Yakubu Gowon Airport - Jos (DNJO)'),
('DNKA', 'Kaduna Airport - Kaduna (DNKA)'),
('DNKN', 'Mallam Aminu International Airport - Kano (DNKN)'),
('DNMA', 'Maiduguri International Airport - Maiduguri (DNMA)'),
('DNMK', 'Makurdi Airport - Makurdi (DNMK)'),
('DNMM', 'Murtala Muhammed International Airport - Lagos (DNMM)'),
('DNPO', 'Port Harcourt International Airport - Port Harcourt (DNPO)'),
('DNSO', 'Sadiq Abubakar III International Airport - Sokoto (DNSO)'),
('DNSU', 'Warri Airport - Okpe (DNSU)'),
('DNYO', 'Yola Airport - Yola (DNYO)'),
('DNBK', 'Srr Ahmadu Bello International Airport - Birinin Kebbi (DNBK)'),
('MNBL', 'Bluefields Airport - Bluefileds (MNBL)'),
('MNLP', 'Ometepe Airport - Omtepe Island (MNLP)'),
('MNMG', 'Augusto C. Sandino (Managua) International Airport - Managua (MNMG)'),
('MNPC', 'Puerto Cabezas Airport - Puerto Cabezas (MNPC)'),
('EHAM', 'Amsterdam Airport Schiphol - Amsterdam (EHAM)'),
('EHBK', 'Maastricht Aachen Airport - Maastricht (EHBK)'),
('EHEH', 'Eindhoven Airport - Eindhoven (EHEH)'),
('EHGG', 'Groningen Airport Eelde - Groningen (EHGG)'),
('EHRD', 'Rotterdam The Hague Airport - Rotterdam (EHRD)'),
('ENAL', 'Ålesund Airport, Vigra - Ålesund (ENAL)'),
('ENAN', 'Andoya Airport, Andenes - Andenes (ENAN)'),
('ENAT', 'Alta Airport - Alta (ENAT)'),
('ENBL', 'Forde Airport, Bringeland - Forde (ENBL)'),
('ENBN', 'Brønnøysund Airport,  Brønnøy - Brønnøy (ENBN)'),
('ENBO', 'Bodo Airport - Bodo (ENBO)'),
('ENBR', 'Bergen Airport, Flesland - Bergen (ENBR)'),
('ENBS', 'Batsfjord Airport - Batsfjord (ENBS)'),
('ENBV', 'Berlevag Airport - Berlevag (ENBV)'),
('ENCN', 'Kristiansand Airport, Kjevik - Kjevik (ENCN)'),
('ENDU', 'Bardufoss Airport -  Malselv (ENDU)'),
('ENEV', 'Harstad/Narvik Airport, Evenes - Evenes (ENEV)'),
('ENFL', 'Floro Airport - Floro (ENFL)'),
('ENGM', 'Oslo Airport, Gardermoen - Oslo (Gardermoen) (ENGM)'),
('ENHD', 'Haugesund Airport, Karmoy - Karmoy (ENHD)'),
('ENHF', 'Hammerfest Airport - Hammerfest (ENHF)'),
('ENHK', 'Hasvik Airport - Hasvik (ENHK)'),
('ENHV', 'Honningsvag Airport, Valan - Honningsvag (ENHV)'),
('ENKB', 'Kristiansund Airport, Kvernberget - Kvernberget (ENKB)'),
('ENKR', 'Kirkenes Airport, Haybuktmoen - Kirkenes (ENKR)'),
('ENLK', 'Leknes Airport - Leknes (ENLK)'),
('ENMH', 'Mehamn Airport - Mehamn (ENMH)'),
('ENML', 'Molde Airport, Årø - Årø (ENML)'),
('ENMS', 'Mosjoen Airport,  Kjaerstad - Mosjoen (ENMS)'),
('SBRB', 'Rio Branco-Plácido de Castro International Airport - Rio Branco (SBRB)'),
('SBRD', 'Maestro Marinho Franco Airport - Rondonópolis (SBRD)'),
('SBRF', 'Recife/Guararapes - Gilberto Freyre International Airport - Recife (SBRF)'),
('SBRJ', 'Santos Dumont Airport - Rio de Janeiro (SBRJ)'),
('SBRP', 'Leite Lopes Airport - Ribeirao Preto (SBRP)'),
('SSRS', 'Barreirinhas National Airport - Barreirinhas (SSRS)'),
('SBSG', 'Sao Gonçalo do Amarante - Governador Aluízio Alves International Airport - Natal (SBSG)'),
('SBSI', 'Presidente Joao Batista Figueiredo Airport - Sinop (SBSI)'),
('SBSJ', 'Professor Urbano Ernesto Stumpf Airport - Sao José Dos Campos (SBSJ)'),
('SBSL', 'Marechal Cunha Machado International Airport - Sao Luís (SBSL)'),
('SBSM', 'Santa Maria Airport - Santa Maria (SBSM)'),
('SBSN', 'Santarém - Maestro Wilson Fonseca International Airport - Santarém (SBSN)'),
('SBSO', 'Adolino Bedin Regional Airport - Sorriso (SBSO)'),
('SBSP', 'Congonhas Airport - Sao Paulo (SBSP)'),
('SBSR', 'Prof. Eribelto Manoel Reino State Airport - Sao José do Rio Preto (SBSR)'),
('SBSV', 'Deputado Luiz Eduardo Magalhaes International Airport - Salvador (SBSV)'),
('SBTB', 'Trombetas Airport - Oriximiná (SBTB)'),
('SBTC', 'Una-Comandatuba Airport - Una (SBTC)'),
('SBTD', 'Toledo - Luiz Dalcanale Filho Municipal Airport - Toledo (SBTD)'),
('SBTE', 'Senador Petrônio Portela Airport - Teresina (SBTE)'),
('SBTF', 'Tefé Airport - Tefé (SBTF)'),
('SBTG', 'Plínio Alarcom Airport - Tres Lagoas (SBTG)'),
('SBTT', 'Tabatinga Airport - Tabatinga (SBTT)'),
('SBTU', 'Tucuruí Airport - Tucuruí (SBTU)'),
('SBUA', 'Sao Gabriel da Cachoeira Airport - Sao Gabriel da Cachoeira (SBUA)'),
('SBUF', 'Paulo Afonso Airport - Paulo Afonso (SBUF)'),
('SBUG', 'Rubem Berta Airport - Uruguaiana (SBUG)'),
('SBUL', 'Ten. Cel. Aviador César Bombonato Airport - Uberlândia (SBUL)'),
('SBUR', 'Mário de Almeida Franco Airport - Uberaba (SBUR)'),
('SBVH', 'Brigadeiro Camarao Airport - Vilhena (SBVH)'),
('SBVT', 'Eurico de Aguiar Salles Airport - Vitória (SBVT)'),
('SBZM', 'Presidente Itamar Franco Airport - Juiz de Fora (SBZM)'),
('SDCO', 'Sorocaba Airport - Sorocaba (SDCO)'),
('SNJD', 'Joao Durval Carneiro Airport - Feira de Santana (SNJD)'),
('SDTK', 'Paraty Airport - Paraty (SDTK)'),
('SIRI', 'Barra Grande Airport - Maraú (SIRI)'),
('SN6L', 'Dr. Luciano de Arruda Coelho Regional Airport - Sobral (SN6L)'),
('SNBR', 'Dom Ricardo Weberberger Airport - Barreiras (SNBR)'),
('SNEB', 'Nagib Demachki Airport - Paragominas (SNEB)'),
('SNFH', 'Fazenda Dom Felipe Airport - Ponta Pora (SNFH)'),
('SNGA', 'Guarapari Airport - Guarapari (SNGA)'),
('SNHS', 'SantaMagalhaes Airpor - Serra Talhada (SNHS)'),
('SILN', 'Fazenda Riozinho Airport - Corumbá (SILN)'),
('SSEO', 'Fazenda Mimosa Airport - Ivinhema (SSEO)'),
('SNPP', 'Morro de SAo Paulo Airport - Cairu (SNPP)'),
('SNRU', 'Caruaru Airport - Caruaru (SNRU)'),
('SNSM', 'Salinópolis Airport - Salinópolis (SNSM)'),
('SNVB', 'Valença Airport - Valença (SNVB)'),
('SNVS', 'Breves Airport - Breves (SNVS)'),
('SNYA', 'Almeirim Airport - Almeirim (SNYA)'),
('SNZR', 'Pedro Rabelo de Souza Airport - Paracatu (SNZR)'),
('SSCN', 'Canela Airport - Canela (SSCN)'),
('SSFB', 'Paulo Abdala Airport - Francisco Beltrao (SSFB)'),
('SSGY', 'Guaíra Airport - Guaíra (SSGY)'),
('SSKW', 'Cacoal Airport - Cacoal (SSKW)'),
('SSUM', 'Orlando de Carvalho Airport - Umuarama (SSUM)'),
('SSUV', 'José Cleto Airport - Uniao da Vitória (SSUV)'),
('SSZR', 'Luis Alberto Lehr Airport - Santa Rosa (SSZR)'),
('SWBC', 'Barcelos Airport - Barcelos (SWBC)'),
('SWBG', 'André Antônio Maggi Airport - Pontes e Lacerda (SWBG)'),
('SWBR', 'Borba Airport - Borba (SWBR)'),
('SWCA', 'Carauari Airport - Carauari (SWCA)'),
('SWGN', 'Araguaína Airport - Araguaína (SWGN)'),
('SWGT', 'Fazenda Nova Airport - Jandaia (SWGT)'),
('SWLB', 'Lábrea Airport - Lábrea (SWLB)'),
('SWTP', 'Tapuruquara Airport - Santa Isabel Do Rio Negro (SWTP)'),
('SWTS', 'Tangará da Serra Airport - Tangará da Serra (SWTS)'),
('MYAK', 'Congo Town Airport - Andros (MYAK)'),
('MYAM', 'Leonard M Thompson International Airport - Marsh Harbour (MYAM)'),
('MYAN', 'San Andros Airport - Andros Island (MYAN)'),
('MYAP', 'Spring Point Airport - Spring Point (MYAP)'),
('MYAT', 'Treasure Cay Airport - Treasure Cay (MYAT)'),
('MYBC', 'Chub Cay Airport - Chub Cay (MYBC)'),
('MYBS', 'South Bimini Airport - South Bimini (MYBS)'),
('MYCA', 'Arthur''s Town Airport - Arthur''s Town (MYCA)'),
('MYCB', 'New Bight Airport - Cat Island (MYCB)'),
('MYCI', 'Colonel Hill Airport - Colonel Hill (MYCI)'),
('MYEF', 'Exuma International Airport - Moss Town (MYEF)'),
('MYEH', 'North Eleuthera Airport - North Eleuthera (MYEH)'),
('MYEM', 'Governor''s Harbour Airport - Governor''s Harbour (MYEM)'),
('MYGF', 'Grand Bahama International Airport - Freeport (MYGF)'),
('MYIG', 'Inagua Airport - Matthew Town (MYIG)'),
('MYLD', 'Deadman''s Cay Airport - Deadman''s Cay (MYLD)'),
('MYLS', 'Stella Maris Airport - Stella Maris (MYLS)'),
('MYMM', 'Mayaguana Airport - Abraham Bay Settlement (MYMM)'),
('MYNN', 'Lynden Pindling International Airport - Nassau (MYNN)'),
('MYSM', 'San Salvador Airport - San Salvador (MYSM)'),
('VQBT', 'Bathpalathang Airport - Jakar (VQBT)'),
('VQPR', 'Paro International Airport - Paro (VQPR)'),
('VQTY', 'Yongphulla Airport - Yongphulla (VQTY)'),
('FBPM', 'P G Matante Intl - Francistown (FBPM)'),
('FBKE', 'Kasane Airport - Kasane (FBKE)'),
('FBMN', 'Maun Airport - Maun (FBMN)'),
('FBSK', 'Sir Seretse Khama International Airport - Gaborone (FBSK)'),
('FBSW', 'Shakawe Airport - Shakawe (FBSW)'),
('UMBB', 'Brest Airport - Brest (UMBB)'),
('UMGG', 'Gomel Airport - Gomel (UMGG)'),
('UMMS', 'Minsk National Airport - Minsk (UMMS)'),
('UMOO', 'Mogilev Airport - Mogilev (UMOO)'),
('MZBG', 'Big Creek Airport - Big Creek (MZBG)'),
('MZCK', 'Caye Caulker Airport - Caye Caulker (MZCK)'),
('MZCP', 'Caye Chapel Airport - Caye Chapel (MZCP)'),
('MZCZ', 'Corozal Airport - Corozal (MZCZ)'),
('MZPB', 'Dangriga Airport - Dangriga (MZPB)'),
('MZSV', 'Independence Airport - Independence (MZSV)'),
('MZTH', 'H.E Alfredo Martinez (Tower Hill) Airstrip - Orange Walk (MZTH)'),
('MZSJ', 'Sartaneja Airport - Sartaneja (MZSJ)'),
('MZSP', 'John Greif II Airport - San Pedro (MZSP)'),
('MZKT', 'Silver Creek Airport - Silver Creek (MZKT)'),
('MZBE', 'Sir Barry Bowen Municipal Airport - Belize City (MZBE)'),
('MZBZ', 'Philip S. W. Goldson International Airport - Belize City (MZBZ)'),
('MZPL', 'Placencia Airport - Placencia (MZPL)'),
('CAD4', 'Trail Regional Airport - Trail (CAD4)'),
('CAJ4', 'Anahim Lake Airport - Anahim Lake (CAJ4)'),
('CAJ9', 'Fort Ware Airport - Fort Ware (CAJ9)'),
('CAT4', 'Qualicum Beach Airport - Qualicum Beach (CAT4)'),
('CAT5', 'Port McNeill Airport - Port McNeill (CAT5)'),
('CBA9', 'Ospika Airport - Ospika (CBA9)'),
('CBBC', 'Bella Bella (Campbell Island) Airport - Bella Bella (CBBC)'),
('CBN9', 'Tsay Keh Airport - Tsay Keh (CBN9)'),
('CCA6', 'Williams Harbour Airport - Williams Harbour (CCA6)'),
('CCD4', 'Postville Airport - Postville (CCD4)'),
('CCE4', 'Black Tickle Airport - Black Tickle (CCE4)'),
('CCK4', 'St. Lewis (Fox Harbour) Airport - St. Lewis (CCK4)'),
('CCP4', 'Port Hope Simpson Airport - Port Hope Simpson (CCP4)'),
('CCZ2', 'Rigolet Airport - Rigolet (CCZ2)'),
('CEM3', 'Whati Airport - Whati (CEM3)'),
('CFH4', 'Fox Harbour Airport - Fox Harbour (CFH4)'),
('CJV7', 'Summer Beaver Airport - Summer Beaver (CJV7)'),
('CKB6', 'Wapekeka Airport - Angling Lake (CKB6)'),
('CKD9', 'Slate Falls Airport - Slate Falls (CKD9)'),
('CKL3', 'Wunnumin Lake Airport - Wunnumin Lake (CKL3)'),
('CKQ3', 'North Spirit Lake Airport - North Spirit Lake (CKQ3)'),
('CNE3', 'Bearskin Lake Airport - Bearskin Lake (CNE3)'),
('CNH2', 'Natuashish Airport - Natuashish (CNH2)'),
('CNM5', 'Kingfisher Lake Airport - Kingfisher Lake (CNM5)'),
('CPV8', 'Keewaywin Airport - Keewaywin (CPV8)'),
('CRHA', 'Streatham Reef Hueston Airfield - Streatham (CRHA)'),
('CSU2', 'Chisasibi Airport - Chisasibi (CSU2)'),
('CTB6', 'Tête-à-la-BaleineAirport  - Tête-à-la-Baleine (CTB6)'),
('CTT5', 'La Romaine Airport - Le Golfe-du-Saint-Laurent (CTT5)'),
('CYIK', 'Ivujivik Airport - Ivujivik (CYIK)'),
('CYIO', 'Pond Inlet Airport - Pond Inlet (CYIO)'),
('CYIV', 'Island Lake Airport - Island Lake (CYIV)'),
('CYKA', 'Kamloops John Moose Fulton Field Regional Airport - Kamloops (CYKA)'),
('CYKD', 'Aklavik/Freddie Carmichael Airport - Aklavik (CYKD)'),
('CYKF', 'Region of Waterloo International Airport - Breslau (CYKF)'),
('CYKG', 'Kangiqsujuaq (Wakeham Bay) Airport - Kangiqsujuaq (CYKG)'),
('CYKL', 'Schefferville Airport - Schefferville (CYKL)'),
('CYKO', 'Akulivik Airport - Akulivik (CYKO)'),
('CYKP', 'Ogoki Post Airport - Ogoki Post (CYKP)'),
('CYKQ', 'Waskaganish Airport - Waskaganish (CYKQ)'),
('CYLA', 'Aupaluk Airport - Aupaluk (CYLA)'),
('CYLC', 'Kimmirut Airport - Kimmirut (CYLC)'),
('CYLH', 'Lansdowne House Airport - Lansdowne House (CYLH)'),
('CYLK', 'Lutselk''e Airport - Lutselk''e (CYLK)'),
('CYLL', 'Lloydminster Airport - Lloydminster (CYLL)'),
('CYLS', 'Barrie-Lake Simcoe Regional Airport - Barrie (CYLS)'),
('CYLU', 'Kangiqsualujjuaq (Georges River) Airport - Kangiqsualujjuaq (CYLU)'),
('CYLW', 'Kelowna International Airport - Kelowna (CYLW)'),
('CYMH', 'Mary''s Harbour Airport - Mary''s Harbour (CYMH)'),
('CYMM', 'Fort McMurray Airport - Fort McMurray (CYMM)'),
('CYMO', 'Moosonee Airport - Moosonee (CYMO)'),
('CYMT', 'Chapais Airport - Chibougamau (CYMT)'),
('CYMU', 'Umiujaq Airport - Umiujaq (CYMU)'),
('CYNA', 'Natashquan Airport - Natashquan (CYNA)'),
('CYNC', 'Wemindji Airport - Wemindji (CYNC)'),
('CYND', 'Ottawa / Gatineau Airport - Gatineau (CYND)'),
('CYNE', 'Norway House Airport - Norway House (CYNE)'),
('CYNL', 'Points North Landing Airport - Points North Landing (CYNL)'),
('CYOC', 'Old Crow Airport - Old Crow (CYOC)'),
('CYOH', 'Oxford House Airport - Oxford House (CYOH)'),
('CYOJ', 'High Level Airport - High Level (CYOJ)'),
('CYOW', 'Ottawa Macdonald-Cartier International Airport - Ottawa (CYOW)'),
('CYPA', 'Prince Albert Glass Field - Prince Albert (CYPA)'),
('CYPC', 'Paulatuk (Nora Aliqatchialuk Ruben) Airport - Paulatuk (CYPC)'),
('CYPE', 'Peace River Airport - Peace River (CYPE)'),
('CYPH', 'Inukjuak Airport - Inukjuak (CYPH)'),
('CYPK', 'Pitt Meadows Airport - Pitt Meadows (CYPK)'),
('CYPL', 'Pickle Lake Airport - Pickle Lake (CYPL)')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
