-- airports seed batch 11/11
INSERT INTO public.airports (code, name) VALUES
('HAGO', 'Gode Airport - Gode (HAGO)'),
('HAJJ', 'Wilwal International Airport - Jijiga (HAJJ)'),
('HAJM', 'Jimma Airport - Jimma (HAJM)'),
('HAKD', 'Kebri Dahar Airport - Kebri Dahar (HAKD)'),
('HALA', 'Hawassa International Airport - Hawassa (HALA)'),
('HAMK', 'Alula Aba Nega Airport - Mekele (HAMK)'),
('HAMT', 'Mizan Teferi Airport - Mizan Teferi (HAMT)'),
('HASL', 'Shilavo Airport - Shilavo (HASL)'),
('HASM', 'Semera Airport - Semera (HASM)'),
('HASO', 'Asosa Airport - Asosa (HASO)'),
('HATP', 'Tippi Airport - Tippi (HATP)'),
('EFET', 'Enontekio Airport - Enontekio (EFET)'),
('EFHK', 'Helsinki Vantaa Airport - Helsinki (Vantaa) (EFHK)'),
('EFIV', 'Ivalo Airport - Ivalo (EFIV)'),
('EFJO', 'Joensuu Airport - Joensuu (EFJO)'),
('EFJY', 'Jyväskylä Airport - Jyväskylän Maalaiskunta (EFJY)'),
('EFKE', 'Kemi-Tornio Airport - Kemi / Tornio (EFKE)'),
('EFKI', 'Kajaani Airport - Kajaani (EFKI)'),
('EFKK', 'Kokkola-Pietarsaari Airport - Kokkola / Kruunupyy (EFKK)'),
('EFKS', 'Kuusamo Airport - Kuusamo (EFKS)'),
('EFKT', 'Kittilä Airport - Kittilä (EFKT)'),
('EFKU', 'Kuopio Airport - Kuopio / Siilinjärvi (EFKU)'),
('EFLP', 'Lappeenranta Airport - Lappeenranta (EFLP)'),
('EFMA', 'Mariehamn Airport - Mariehamn (EFMA)'),
('EFOU', 'Oulu Airport - Oulu / Oulunsalo (EFOU)'),
('EFPO', 'Pori Airport - Pori (EFPO)'),
('EFRO', 'Rovaniemi Airport - Rovaniemi (EFRO)'),
('EFSA', 'Savonlinna Airport - Savonlinna (EFSA)'),
('EFTP', 'Tampere-Pirkkala Airport - Tampere / Pirkkala (EFTP)'),
('EFTU', 'Turku Airport - Turku (EFTU)'),
('EFVA', 'Vaasa Airport - Vaasa (EFVA)'),
('NFCI', 'Cicia Airport - Cicia (NFCI)'),
('NFFN', 'Nadi International Airport - Nadi (NFFN)'),
('NFFO', 'Malolo Lailai Island Airport - Malolo Lailai Island (NFFO)'),
('NFKD', 'Vunisea Airport - Vunisea (NFKD)'),
('NFMA', 'Mana Island Airport - Mana Island (NFMA)'),
('NFMO', 'Moala Airport - Moala (NFMO)'),
('NFNA', 'Nausori International Airport - Nausori (NFNA)'),
('NFNB', 'Levuka Airfield - Bureta (NFNB)'),
('NFNG', 'Ngau Airport - Ngau (NFNG)'),
('NFNK', 'Lakeba Island Airport - Lakeba Island (NFNK)'),
('NFNL', 'Labasa Airport - Labasa (NFNL)'),
('NFNM', 'Matei Airport - Matei (NFNM)'),
('NFNO', 'Koro Island Airport - Koro Island (NFNO)'),
('NFNR', 'Rotuma Airport - Rotuma (NFNR)'),
('NFNS', 'Savusavu Airport - Savusavu (NFNS)'),
('NFSW', 'Yasawa Island Airport - Yasawa Island (NFSW)'),
('NFVB', 'Vanua Balavu Airport - Vanua Balavu (NFVB)'),
('EGYP', 'Mount Pleasant Airport - Mount Pleasant (EGYP)'),
('SFAL', 'Port Stanley Airport - Stanley (SFAL)'),
('PTKK', 'Chuuk International Airport - Weno Island (PTKK)'),
('PTPN', 'Pohnpei International Airport - Pohnpei Island (PTPN)'),
('PTSA', 'Kosrae International Airport - Okat (PTSA)'),
('PTYA', 'Yap International Airport - Yap Island (PTYA)'),
('EKVG', 'Vágar Airport - Vágar (EKVG)'),
('LFBD', 'Bordeaux-Mérignac Airport - Bordeaux/Mérignac (LFBD)'),
('LFBE', 'Bergerac Dordogne Périgord Airport - Bergerac/Roumaniere (LFBE)'),
('LFBH', 'La Rochelle-Île de Ré Airport - La Rochelle/Île de Ré (LFBH)'),
('LFBI', 'Poitiers-Biard Airport - Poitiers/Biard (LFBI)'),
('LFBL', 'Limoges Airport - Limoges/Bellegarde (LFBL)'),
('LFBO', 'Toulouse-Blagnac Airport - Toulouse/Blagnac (LFBO)'),
('LFBP', 'Pau Pyrénées Airport - Pau/Pyrénées (Uzein) (LFBP)'),
('LFBT', 'Tarbes-Lourdes-Pyrénées Airport - Tarbes/Lourdes/Pyrénées (LFBT)'),
('LFBZ', 'Biarritz-Anglet-Bayonne Airport - Biarritz/Anglet/Bayonne (LFBZ)'),
('LFCK', 'Castres-Mazamet Airport - Castres/Mazamet (LFCK)'),
('LFCR', 'Rodez–Aveyron Airport - Rodez/Marcillac (LFCR)'),
('LFEA', 'Aérodrome de Belle Île - Bangor (LFEA)'),
('LFEC', 'Ouessant Airport - Ushant (LFEC)'),
('LFEY', 'Île d''Yeu Airport - Île d''Yeu (LFEY)'),
('LFFO', 'Beauvoir Fromentine Airfield - Fromentine (LFFO)'),
('LFGJ', 'Dole-Jura Airport - Tavaux, Jura (LFGJ)'),
('LFHP', 'Le Puy-Loudes Airfield - Chaspuzac, Haute-Loire (LFHP)'),
('LFJL', 'Metz-Nancy-Lorraine Airport - Goin (LFJL)'),
('LFKB', 'Bastia-Poretta Airport - Bastia/Poretta (LFKB)'),
('LFKC', 'Calvi-Sainte-Catherine Airport - Calvi/Sainte-Catherine (LFKC)'),
('LFKF', 'Figari Sud-Corse Airport - Figari Sud-Corse (LFKF)'),
('LFKJ', 'Ajaccio-Napoléon Bonaparte Airport - Ajaccio/Napoléon Bonaparte (LFKJ)'),
('LFLB', 'Chambéry Savoie Mont Blanc Airport - Viviers-du-Lac (LFLB)'),
('LFLC', 'Clermont-Ferrand Auvergne Airport - Aulnat, Puy-de-Dôme (LFLC)'),
('LFLL', 'Lyon Saint-Exupéry Airport - Colombier-Saugnieu, Rhône (LFLL)'),
('LFLP', 'Annecy Haute-Savoie Mont Blanc Airport - Epagny Metz-Tessy (LFLP)'),
('LFLS', 'Grenoble Alpes Isere Airport - Saint-Étienne-de-Saint-Geoirs, Isere (LFLS)'),
('LFLW', 'Aurillac Airport - Aurillac (LFLW)'),
('LFMK', 'Carcassonne Airport - Carcassonne/Salvaza (LFMK)'),
('LFML', 'Marseille Provence Airport - Marignane, Bouches-du-Rhône (LFML)'),
('LFMN', 'Nice-Côte d''Azur Airport - Nice, Alpes-Maritimes (LFMN)'),
('LFMP', 'Perpignan-Rivesaltes (Llabanare) Airport - Perpignan/Rivesaltes (LFMP)')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
