-- airports seed batch 9/11
INSERT INTO public.airports (code, name) VALUES
('WAHI', 'Yogyakarta International Airport - Yogyakarta (WAHI)'),
('WAHL', 'Tunggul Wulung Airport - Cilacap (WAHL)'),
('WAHU', 'Dewadaru Airport - Karimunjawa (WAHU)'),
('WAJB', 'Bokondini Airport - Bokondini (WAJB)'),
('WAJJ', 'Dortheys Hiyo Eluay International Airport - Sentani (WAJJ)'),
('WAJK', 'Kiwirok Airstrip - Kiwirok (WAJK)'),
('WAJO', 'Oksibil Airport - Oksibil (WAJO)'),
('WAJY', 'Werur Airport - Mar (WAJY)'),
('WAKK', 'Mopah International Airport - Merauke (WAKK)'),
('WAKT', 'Tanah Merah Airport - Tanah Merah (WAKT)'),
('WALG', 'Tanjung Harapan Airport - Tanjung Selor-Borneo Island (WALG)'),
('WALJ', 'Datadawai Airport - Datadawai-Borneo Island (WALJ)'),
('WALL', 'Sultan Aji Muhammad Sulaiman Sepinggan International Airport - Balikpapan (WALL)'),
('WALR', 'Juwata International Airport / Suharnoko Harbani AFB - Tarakan (WALR)'),
('WALS', 'Aji Pangeran Tumenggung Pranoto International Airport - Samarinda (WALS)'),
('WAMG', 'Jalaluddin Airport - Gorontalo-Celebes Island (WAMG)'),
('WAMH', 'Naha Airport - Tabukan Utara, Sangihe Islands (WAMH)'),
('WAMM', 'Sam Ratulangi Airport - Manado (WAMM)'),
('WAFY', 'Buol - Pogogul Airport - Buol-Celebes Island (WAFY)'),
('WAOC', 'Bersujud Airport - Batu Licin (WAOC)'),
('WAGI', 'Iskandar Airport - Pangkalanbun (WAGI)'),
('WAOK', 'Gusti Syamsir Alam Airport - Stagen (WAOK)'),
('WAON', 'Warukin Airport - Tanta-Tabalong (WAON)'),
('WAOO', 'Syamsudin Noor International Airport - Landasan Ulin (WAOO)'),
('WAOS', 'Sampit (Hasan) Airport - Sampit (WAOS)'),
('WAOW', 'Tumbang Samba Airport - Tumbang Samba-Borneo Island (WAOW)'),
('WAPF', 'Karel Sadsuitubun Airport - Langgur (WAPF)'),
('WAPN', 'Namniwel Airport - Namniwel (WAPN)'),
('WAPP', 'Pattimura International Airport - Ambon (WAPP)'),
('WAQM', 'Robert Atty Bessing - Malinau (WAQM)'),
('WAQT', 'Kalimarau Airport - Tanjung Redeb - Borneo Island (WAQT)'),
('WARA', 'Abdul Rachman Saleh Airport - Malang (WARA)'),
('WARE', 'Notohadinegoro Airport - Jember (WARE)'),
('WAHH', 'Adisutjipto Airport - Yogyakarta (WAHH)'),
('WAHQ', 'Adisumarmo Airport - Surakarta (WAHQ)'),
('WARR', 'Juanda International Airport - Surabaya (WARR)'),
('WAHS', 'Achmad Yani Airport - Semarang (WAHS)'),
('WASF', 'Fakfak Airport - Fakfak (WASF)'),
('WASK', 'Kaimana Airport - Kaimana (WASK)'),
('WASN', 'Marinda Airport - Waisai (WASN)'),
('WAUU', 'Rendani Airport - Manokwari (WAUU)'),
('WASS', 'Domine Eduard Osok Airport - Sorong (WASS)'),
('WATA', 'AA Bere Tallo (Haliwen) Airport - Atambua (WATA)'),
('WATC', 'Frans Xavier Seda Airport - Waioti (WATC)'),
('WATE', 'H. Hasan Aroeboesman (Ende) Airport - Ende (WATE)'),
('WATG', 'Frans Sales Lega Airport - Satar Tacik, Manggarai (WATG)'),
('WATL', 'Larantuka Gewayentana Airport - Tiwatobi (WATL)'),
('WATM', 'Alor Island - Mali Airport - Kabola (WATM)'),
('WATO', 'Komodo Airport - Labuan Bajo, Manggarai Barat (WATO)'),
('WATT', 'El Tari Airport - Kupang (WATT)'),
('WAVV', 'Wamena Airport - Wamena (WAVV)'),
('WAWD', 'Matahora Airport - Wangi-wangi Island (WAWD)'),
('WAWH', 'Selayar - Haji Aroeppala Airport - Benteng (WAWH)'),
('WAWP', 'Sangia Nibandera Airport - Kolaka (WAWP)'),
('WAWW', 'Haluoleo Airport - Kendari (WAWW)'),
('WIBB', 'Sultan Syarif Kasim II International Airport / Roesmin Nurjadin AFB - Pekanbaru (WIBB)'),
('WIBD', 'Pinang Kampai Airport - Dumai (WIBD)'),
('WICA', 'Kertajati International Airport - Kertajati (WICA)'),
('WICC', 'Husein Sastranegara International Airport - Bandung (WICC)'),
('WICN', 'Nusawiru Airport - Cijulang (WICN)'),
('WIDD', 'Hang Nadim International Airport - Batam (WIDD)'),
('WIDN', 'Raja Haji Fisabilillah International Airport - Tanjung Pinang-Bintan Island (WIDN)'),
('WIPU', 'Muko Muko Airport - Muko Muko (WIPU)'),
('WIHH', 'Halim Perdanakusuma International Airport - Jakarta (WIHH)'),
('WIII', 'Soekarno-Hatta International Airport - Jakarta (WIII)'),
('WILL', 'Radin Inten II International Airport - Bandar Lampung (WILL)'),
('WITM', 'Malikus Saleh Airport - Lhok Seumawe-Sumatra Island (WITM)'),
('WIMB', 'Binaka Airport - Gunungsitoli (WIMB)'),
('WIMM', 'Kualanamu International Airport - Beringin (WIMM)'),
('WIMN', 'Silangit Airport - Siborong-Borong (WIMN)'),
('WIMS', 'Dr. Ferdinand Lumban Tobing Airport - Sibolga (Pinangsori) (WIMS)'),
('WIMU', 'Alas Leuser Airport - Kutacane (WIMU)'),
('WIKT', 'H.A.S Hanandjoeddin International Airport - Tanjung Pandan (WIKT)'),
('WIOG', 'Nanga Pinoh Airport - Nanga Pinoh-Borneo Island (WIOG)'),
('WIOK', 'Rahadi Osman Airport - Ketapang (WIOK)'),
('WIDO', 'Ranai Airport - Ranai-Natuna Besar Island (WIDO)'),
('WIOO', 'Supadio Airport - Pontianak (WIOO)'),
('WIOP', 'Pangsuma Airport - Putussibau-Borneo Island (WIOP)'),
('WIOS', 'Tebelian Airport - Sintang (WIOS)'),
('WIJJ', 'Sultan Thaha Airport - Jambi (WIJJ)'),
('WIJB', 'Muara Bungo Airport - Muara Bungo (WIJB)'),
('WIPK', 'Depati Amir Airport - Pangkal Pinang (WIPK)'),
('WIGG', 'Fatmawati Soekarno Airport - Bengkulu (WIGG)'),
('WIPP', 'Sultan Mahmud Badaruddin II Airport - Palembang (WIPP)'),
('WIPQ', 'Pendopo Airport - Talang Gudang-Sumatra Island (WIPQ)'),
('WIPT', 'Minangkabau International Airport - Padang (Katapiang) (WIPT)'),
('WITC', 'Cut Nyak Dhien Airport - Kuala Pesisir (WITC)'),
('WITG', 'Lasikin Airport - Lubang (WITG)'),
('WITK', 'Rembele Airport - Takengon (WITK)'),
('WITT', 'Sultan Iskandar Muda International Airport - Banda Aceh (WITT)'),
('WAPS', 'Mathilda Batlayeri Airport - Saumlaki-Yamdena Island (WAPS)'),
('WAQJ', 'Yuvai Semaring Airport - Long Bawan (WAQJ)'),
('WALC', 'LNG Badak Airport - Bontang-Borneo Island (WALC)'),
('WRLP', 'Long Apung Airport - Long Apung-Borneo Island (WRLP)'),
('EICA', 'Connemara Regional Airport - Inverin (EICA)'),
('EICK', 'Cork Airport - Cork (EICK)'),
('EIDL', 'Donegal Airport - Donegal (EIDL)'),
('EIDW', 'Dublin Airport - Dublin (EIDW)'),
('EIIM', 'Inishmore Aerodrome - Inis Mór (EIIM)'),
('EIIR', 'Inisheer Aerodrome - Inis Oírr (EIIR)'),
('EIKN', 'Ireland West Knock Airport - Charlestown (EIKN)'),
('EIKY', 'Kerry Airport - Farranfore (EIKY)'),
('EIMN', 'Inishmaan Aerodrome - Inis Meáin (EIMN)'),
('EINN', 'Shannon Airport - Shannon (EINN)'),
('LLBG', 'Ben Gurion International Airport - Tel Aviv (LLBG)'),
('LLER', 'Ramon International Airport - Eilat (LLER)'),
('LLHA', 'Haifa International Airport - Haifa (LLHA)'),
('EGNS', 'Isle of Man Airport - Castletown (EGNS)'),
('VETU', 'Baljek Airport - Baljek (VETU)'),
('IN-0024', 'Baramati Airport - Pune (IN-0024)'),
('VEAY', 'Ayodhya Airport - Faizabad (VEAY)'),
('VANM', 'Navi Mumbai International Airport - Navi Mumbai (VANM)'),
('VEHO', 'Itanagar Donyi Polo Hollongi Airport - Hollongi (VEHO)'),
('VEUK', 'Utkela Airport - Bhawanipatna (VEUK)'),
('VEJR', 'Jagdalpur Airport - Jagdalpur (VEJR)'),
('VA1G', 'Rewa Airport, Chorhata, REWA - Rewa (VA1G)'),
('VADU', 'Diu Airport - Diu (VADU)'),
('VAGD', 'Gondia Airport - Gondia (VAGD)'),
('VAAH', 'Sardar Vallabh Bhai Patel International Airport - Ahmedabad (VAAH)'),
('VAAU', 'Aurangabad Airport - Aurangabad (VAAU)'),
('VABB', 'Chhatrapati Shivaji International Airport - Mumbai (VABB)'),
('VABJ', 'Bhuj Airport - Bhuj (VABJ)'),
('VOBM', 'Belagavi Airport - Belgaum (VOBM)'),
('VABO', 'Vadodara Airport - Vadodara (VABO)'),
('VABP', 'Raja Bhoj International Airport - Bhopal (VABP)'),
('VABV', 'Bhavnagar Airport - Bhavnagar (VABV)'),
('VOHB', 'Hubli Airport - Hubli (VOHB)'),
('VAID', 'Devi Ahilyabai Holkar Airport - Indore (VAID)'),
('VAJB', 'Jabalpur Airport - Jabalpur (VAJB)'),
('VAJL', 'Jalgaon Airport - Jalgaon (VAJL)'),
('VAJM', 'Jamnagar Airport - Jamnagar (VAJM)'),
('VAKE', 'Kandla Airport - Kandla (VAKE)'),
('VAKJ', 'Khajuraho Airport - Khajuraho (VAKJ)'),
('VAKP', 'Kolhapur Airport - Kolhapur (VAKP)'),
('VAKS', 'Keshod Airport - Keshod (VAKS)'),
('VALT', 'Murod Kond Airport - Latur (VALT)'),
('VAND', 'Nanded Airport - Nanded (VAND)'),
('VANP', 'Dr. Babasaheb Ambedkar International Airport - Nagpur (VANP)'),
('VAOZ', 'Nashik Airport - Nasik (VAOZ)'),
('VAPO', 'Pune Airport / Lohagaon Air Force Station - Pune (VAPO)'),
('VAPR', 'Porbandar Airport - Porbandar (VAPR)'),
('VARK', 'Rajkot Airport - Rajkot (VARK)'),
('VERP', 'Swami Vivekananda Airport - Raipur (VERP)'),
('VASD', 'Shirdi Airport - Kakadi (VASD)'),
('VASU', 'Surat Airport - Surat (VASU)'),
('VAUD', 'Maharana Pratap Airport - Udaipur (VAUD)'),
('VEAT', 'Agartala - Maharaja Bir Bikram Airport - Agartala (VEAT)'),
('VEBD', 'Bagdogra Airport - Siliguri (VEBD)'),
('VEBI', 'Shillong Airport - Shillong (VEBI)'),
('VEBN', 'Lal Bahadur Shastri Airport - Varanasi (VEBN)'),
('VEBS', 'Biju Patnaik Airport - Bhubaneswar (VEBS)'),
('VEBU', 'Bilaspur Airport - Bilaspur (VEBU)'),
('VECC', 'Netaji Subhash Chandra Bose International Airport - Kolkata (VECC)'),
('VEDG', 'Kazi Nazrul Islam Airport - Durgapur (VEDG)'),
('VEDH', 'Darbhanga Airport - Darbhanga (VEDH)'),
('VEDO', 'Deoghar Airport - Deoghar (VEDO)'),
('VEGK', 'Gorakhpur Airport - Gorakhpur (VEGK)'),
('VEGT', 'Lokpriya Gopinath Bordoloi International Airport - Guwahati (VEGT)'),
('VEGY', 'Gaya Airport - Gaya (VEGY)'),
('VEIM', 'Imphal Airport - Imphal (VEIM)'),
('VEJH', 'Jharsuguda Airport - Jharsuguda (VEJH)'),
('VEJT', 'Jorhat Airport - Jorhat (VEJT)'),
('VEKU', 'Silchar Airport - Silchar (VEKU)'),
('VELP', 'Lengpui Airport - Aizawl (Lengpui) (VELP)'),
('VELR', 'Lilabari North Lakhimpur Airport - Lilabari (VELR)'),
('VEMN', 'Dibrugarh Airport - Dibrugarh (VEMN)'),
('VEMR', 'Dimapur Airport - Dimapur (VEMR)'),
('VEPT', 'Jay Prakash Narayan Airport - Patna (VEPT)'),
('VERC', 'Birsa Munda Airport - Ranchi (VERC)'),
('VETZ', 'Tezpur Airport - Tezpur (VETZ)'),
('VOVZ', 'Visakhapatnam Airport - Visakhapatnam (VOVZ)'),
('VIAG', 'Agra Airport / Agra Air Force Station - Agra (VIAG)'),
('VIAH', 'Aligarh Airport - Aligarh (VIAH)'),
('VEAB', 'Prayagraj Airport - Allahabad (VEAB)'),
('VIAR', 'Sri Guru Ram Dass Jee International Airport - Amritsar (VIAR)'),
('VIAX', 'Adampur Airport - Adampur (VIAX)'),
('VIBR', 'Kullu Manali Airport - Bhuntar (VIBR)'),
('VIBY', 'Bareilly Air Force Station - Bareilly (VIBY)'),
('VICG', 'Chandigarh International Airport - Chandigarh (VICG)'),
('VIKA', 'Kanpur Airport - Kanpur (VIKA)'),
('VIDN', 'Dehradun Jolly Grant Airport - Dehradun (Jauligrant) (VIDN)'),
('VIDP', 'Indira Gandhi International Airport - New Delhi (VIDP)'),
('VIDX', 'Hindon Airport / Hindon Air Force Station - Ghaziabad (VIDX)'),
('VIGG', 'Kangra Airport - Kangra (VIGG)'),
('LGKR', 'Corfu Ioannis Kapodistrias International Airport - Kerkyra (Corfu) (LGKR)'),
('LGKS', 'Kasos Airport - Kasos Island (LGKS)'),
('LGKV', 'Kavala Alexander the Great International Airport - Kavala (LGKV)'),
('LGKY', 'Kalymnos Airport - Kalymnos Island (LGKY)'),
('LGKZ', 'Kozani National Airport Filippos - Kozani (LGKZ)'),
('LGLE', 'Leros Airport - Leros Island (LGLE)'),
('LGLM', 'Limnos Airport - Limnos Island (LGLM)'),
('LGMK', 'Mykonos Island National Airport - Mykonos (LGMK)'),
('LGML', 'Milos Airport - Milos Island (LGML)'),
('LGMT', 'Mytilene International Airport - Mytilene (LGMT)'),
('LGNX', 'Naxos Island National Airport - Naxos (LGNX)'),
('LGPA', 'Paros National Airport - Paros (LGPA)'),
('LGPL', 'Astypalaia Airport - Astypalaia Island (LGPL)'),
('LGPZ', 'Aktion National Airport - Preveza (LGPZ)'),
('LGRP', 'Diagoras Airport - Rhodes (LGRP)'),
('LGRX', 'Patras Araxos Agamemnon Airport - Patras (LGRX)'),
('LGSA', 'Chania International Airport - Souda (LGSA)'),
('LGSK', 'Skiathos Island National Airport - Skiathos (LGSK)'),
('LGSM', 'Samos Airport - Samos Island (LGSM)'),
('LGSO', 'Syros Airport - Syros Island (LGSO)'),
('LGSR', 'Santorini Airport - Santorini Island (LGSR)'),
('LGST', 'Sitia Airport - Crete Island (LGST)'),
('LGSY', 'Skiros Airport - Skiros Island (LGSY)'),
('LGTS', 'Thessaloniki Macedonia International Airport - Thessaloniki (LGTS)'),
('LGZA', 'Zakynthos International Airport Dionysios Solomos - Zakynthos (LGZA)'),
('MGGT', 'La Aurora Airport - Guatemala City (MGGT)'),
('MGHT', 'Huehuetenango Airport - Huehuetenango (MGHT)'),
('MGPB', 'Puerto Barrios Airport - Puerto Barrios (MGPB)'),
('MGQZ', 'Quezaltenango Airport - Quezaltenango (MGQZ)'),
('MGRT', 'Retalhuleu Airport - Retalhuleu (MGRT)'),
('MGMM', 'Mundo Maya International Airport - San Benito (MGMM)'),
('PGUM', 'Antonio B. Won Pat International Airport - Hagatna (PGUM)'),
('GGOV', 'Osvaldo Vieira International Airport - Bissau (GGOV)'),
('SYCJ', 'Cheddi Jagan International Airport - Georgetown (SYCJ)'),
('SYEC', 'Eugene F. Correia International Airport - Ogle (SYEC)'),
('SYKA', 'Kaieteur International Airport - Kaieteur Falls (SYKA)'),
('SYLT', 'Lethem Airport - Lethem (SYLT)'),
('VHHH', 'Hong Kong International Airport - Hong Kong (VHHH)'),
('MHLC', 'Goloson International Airport - La Ceiba (MHLC)'),
('MHLM', 'Ramón Villeda Morales International Airport - San Pedro Sula (MHLM)'),
('MHNJ', 'La Laguna Airport - Guanaja (MHNJ)'),
('MHPL', 'Puerto Lempira Airport - Puerto Lempira (MHPL)'),
('MHRO', 'Juan Manuel Gálvez International Airport - Coxen Hole (MHRO)'),
('MHPR', 'Palmerola International Airport / José Enrique Soto Cano Air Base - Palmerola (MHPR)'),
('MHTG', 'Toncontín International Airport - Tegucigalpa (MHTG)'),
('MHUT', 'Utila Airport - Utila Island (MHUT)'),
('LDDU', 'Dubrovnik Ruđer Bošković Airport - Čilipi (LDDU)'),
('LDOS', 'Osijek Airport - Klisa (LDOS)'),
('LDPL', 'Pula Airport - Pula (LDPL)'),
('LDRI', 'Rijeka Airport - Omišalj (LDRI)'),
('LDSB', 'Brač Airport - Gornji Humac (LDSB)'),
('LDSP', 'Split Airport - Kaštel Štafilić (LDSP)'),
('LDZA', 'Zagreb Franjo Tuđman International Airport - Velika Gorica (LDZA)'),
('LDZD', 'Zadar Airport - Zemunik Donji (Zadar) (LDZD)'),
('MTCA', 'Antoine-Simon International Airport - Les Cayes (MTCA)'),
('MTCH', 'Cap Haitien International Airport - Cap Haitien (MTCH)'),
('MTJE', 'Jérémie Airport - Carrefour Sanon (MTJE)'),
('MTPP', 'Toussaint Louverture International Airport - Port-au-Prince (MTPP)'),
('LHBP', 'Budapest Liszt Ferenc International Airport - Budapest (LHBP)'),
('LHDC', 'Debrecen International Airport - Debrecen (LHDC)'),
('LHPP', 'Pécs-Pogány Airport - Pécs (LHPP)'),
('LHPR', 'Győr-Pér International Airport - Pér (LHPR)'),
('LHSM', 'Hévíz–Balaton Airport - Sármellék (LHSM)'),
('WAVD', 'Nop Goliat Dekai Airport - Dekai (WAVD)'),
('ID-0004', 'Okpahik Airstrip - Okpahik (ID-0004)'),
('WIMO', 'Lasondre Airport - Pulau-Pulau Batu (WIMO)'),
('ID-0031', 'Diphikin Airstrip - Binsari (ID-0031)'),
('KIWI', 'Kiwi Airstrip - Kiwi (KIWI)'),
('ID-0100', 'Oklip Airstrip - Oklip (ID-0100)'),
('WIMI', 'Syekh Hamzah Fansyuri Airport - Singkil (WIMI)'),
('ID-0178', 'Awimbon Airstrip - Awimbon ( ID-0178)'),
('SCTE', 'El Tepual Airport - Puerto Montt (SCTE)'),
('SCVD', 'Pichoy Airport - Valdivia (SCVD)'),
('SCVL', 'Las Marías Airport - Valdivia (SCVL)'),
('FKKD', 'Douala International Airport - Douala (FKKD)'),
('FKKL', 'Salak Airport - Maroua (FKKL)'),
('FKKN', 'N''Gaoundéré Airport - N''Gaoundéré (FKKN)'),
('FKKR', 'Garoua International Airport - Garoua (FKKR)'),
('FKYS', 'Yaoundé Nsimalen International Airport - Yaoundé (FKYS)'),
('ZBAL', 'Alxa Left Banner Bayanhot Airport - Bayanhot (ZBAL)'),
('ZBTS', 'Tangshan Sannühe Airport - Tangshan (Fengrun) (ZBTS)'),
('ZUBZ', 'Bazhong Enyang Airport - Bazhong (Enyang) (ZUBZ)'),
('ZGSG', 'Shaoguan Danxia Airport - Shaoguan (ZGSG)'),
('ZSJA', 'Jinggangshan Airport - Ji''an (ZSJA)'),
('ZUDR', 'Rikaze Dingri Airport - Xigaze (Dingri) (ZUDR)'),
('ZWTK', 'Tashikuergan Hongqilafu Airport - Tashikuergan (ZWTK)'),
('ZWZS', 'Zhaosu Tianma Airport - Zhaosu (ZWZS)'),
('ZWHJ', 'Hejing Bayinbuluke Airport - Hejing (ZWHJ)'),
('ZWQT', 'Qitai Jiangbulake Airport - Qitai (ZWQT)'),
('ZLJN', 'Jining Qufu Airport - Jining (ZLJN)'),
('ZSJH', 'Chizhou Jiuhuashan Airport - Chizhou (ZSJH)'),
('ZULA', 'Langzhong Gucheng Airport - Nanchong (Langzhong) (ZULA)'),
('ZPNL', 'Ninglang Luguhu Airport - Ninglang (ZPNL)'),
('ZBAR', 'Alxa Right Banner Badanjilin Airport - Badanjilin (ZBAR)'),
('ZWTS', 'Tumxuk Tangwangcheng Airport - Tumxuk (ZWTS)'),
('ZBAA', 'Beijing Capital International Airport - Beijing (ZBAA)'),
('ZBAD', 'Beijing Daxing International Airport - Beijing (ZBAD)'),
('ZBCD', 'Chengde Puning Airport - Chengde (ZBCD)'),
('ZBCF', 'Chifeng Yulong Airport - Chifeng (ZBCF)'),
('ZBCZ', 'Changzhi Wangcun Airport - Changzhi (ZBCZ)'),
('ZBDH', 'Qinhuangdao Beidaihe Airport - Qinhuangdao (Changli) (ZBDH)'),
('ZBDS', 'Ordos Ejin Horo Airport - Ordos (ZBDS)'),
('ZBDT', 'Datong Yungang Airport - Datong (ZBDT)'),
('ZBER', 'Erenhot Saiwusu International Airport - Erenhot (ZBER)'),
('ZBES', 'Arxan Yi''ershi Airport - Arxan (ZBES)'),
('ZBHD', 'Handan Airport - Handan (ZBHD)'),
('ZBHH', 'Hohhot Baita International Airport - Hohhot (ZBHH)'),
('ZBHZ', 'Holingol Huolinhe Airport - Holingol (ZBHZ)'),
('ZBLA', 'Hulunbuir Hailar Airport - Hailar (ZBLA)'),
('ZBLF', 'Linfen Yaodu Airport - Linfen (Yaodu) (ZBLF)'),
('ZBLL', 'Lüliang Dawu Airport - Lüliang (ZBLL)'),
('ZBMZ', 'Manzhouli Xijiao Airport - Manzhouli (ZBMZ)'),
('ZBOW', 'Baotou Donghe Airport - Baotou (ZBOW)'),
('ZBSJ', 'Shijiazhuang Zhengding International Airport - Shijiazhuang (ZBSJ)'),
('ZBTJ', 'Tianjin Binhai International Airport - Tianjin (ZBTJ)'),
('ZBTL', 'Tongliao Airport - Tongliao (ZBTL)'),
('ZBUC', 'Ulanqab Jining Airport - Ulanqab (ZBUC)'),
('ZBUH', 'Wuhai Airport - Wuhai (ZBUH)'),
('ZBUL', 'Ulanhot Yilelite Airport - Ulanhot (ZBUL)'),
('ZBUT', 'Ruad Zhongqi Hailiutu Airport - Ruad Zhongqi (Urad Middle Banner) (ZBUT)'),
('ZBXH', 'Xilinhot Airport - Xilinhot (ZBXH)'),
('ZBXZ', 'Xinzhou Wutaishan Airport - Xinzhou (ZBXZ)'),
('ZBYC', 'Yuncheng Zhangxiao Airport - Yuncheng (Yanhu) (ZBYC)'),
('ZBYN', 'Taiyuan Wusu International Airport - Taiyuan (ZBYN)'),
('ZBYZ', 'Bayannur Tianjitai Airport - Bavannur (ZBYZ)'),
('ZBZJ', 'Zhangjiakou Ningyuan Airport - Zhangjiakou (ZBZJ)'),
('ZBZL', 'Zhalantun Genghis Khan Airport - Zhalantun (ZBZL)'),
('ZGBH', 'Beihai Fucheng Airport - Beihai (Yinhai) (ZGBH)'),
('ZGBS', 'Baise (Bose) Bama Airport - Baise (Tianyang) (ZGBS)'),
('ZGCD', 'Changde Taohuayuan Airport - Changde (Dingcheng) (ZGCD)'),
('ZGCJ', 'Huaihua Zhijiang Airport - Huaihua (ZGCJ)'),
('ZGCZ', 'Chenzhou Beihu Airport - Chenzhou (ZGCZ)'),
('ZGDY', 'Zhangjiajie Hehua International Airport - Zhangjiajie (Yongding) (ZGDY)'),
('ZGFS', 'Foshan Shadi Airport - Foshan (Nanhai) (ZGFS)'),
('ZGGG', 'Guangzhou Baiyun International Airport - Guangzhou (Huadu) (ZGGG)'),
('ZGHA', 'Changsha Huanghua International Airport - Changsha (Changsha) (ZGHA)'),
('ZGHC', 'Hechi Jinchengjiang Airport - Hechi (Jinchengjiang) (ZGHC)'),
('ZGHY', 'Hengyang Nanyue Airport - Hengyang (ZGHY)'),
('ZGHZ', 'Huizhou Pingtan Airport - Huizhou (Pingtan) (ZGHZ)'),
('ZGKL', 'Guilin Liangjiang International Airport - Guilin (Lingui) (ZGKL)'),
('ZGLG', 'Yongzhou Lingling Airport - Yongzhou (ZGLG)'),
('ZGMX', 'Meizhou Meixian Changgangji International Airport - Meizhou (Meixian) (ZGMX)'),
('ZGNN', 'Nanning Wuxu Airport - Nanning (Jiangnan) (ZGNN)'),
('ZGOW', 'Jieyang Chaoshan International Airport - Jieyang (Rongcheng) (ZGOW)'),
('ZGSD', 'Zhuhai Jinwan Airport - Zhuhai (Jinwan) (ZGSD)'),
('ZGSY', 'Shaoyang Wugang Airport - Shaoyang (Wugang) (ZGSY)'),
('ZGSZ', 'Shenzhen Bao''an International Airport - Shenzhen (Bao''an) (ZGSZ)'),
('ZGWZ', 'Wuzhou Xijiang Airport - Tangbu (ZGWZ)'),
('ZGXX', 'Xiangxi Biancheng Airport - Xiangxi (ZGXX)'),
('ZGYL', 'Yulin Fumian Airport - Yulin (ZGYL)'),
('ZGYY', 'Yueyang Sanhe Airport - Yueyang (Yueyanglou) (ZGYY)'),
('ZGZH', 'Liuzhou Bailian Airport / Bailian Air Base - Liuzhou (Liujiang) (ZGZH)'),
('ZGZJ', 'Zhanjiang Wuchuan Airport - Zhanjiang (ZGZJ)'),
('ZHCC', 'Zhengzhou Xinzheng International Airport - Zhengzhou (ZHCC)'),
('ZHEC', 'Ezhou Huahu Airport - Ezhou (ZHEC)'),
('ZHES', 'Enshi Xujiaping Airport - Enshi (Enshi) (ZHES)'),
('ZHHH', 'Wuhan Tianhe International Airport - Wuhan (Huangpi) (ZHHH)'),
('ZHJZ', 'Jingzhou Shashi Airport - Jingzhou (Shashi) (ZHJZ)'),
('ZHLY', 'Luoyang Beijiao Airport - Luoyang (Laocheng) (ZHLY)'),
('ZHNY', 'Nanyang Jiangying Airport - Nanyang (Wancheng) (ZHNY)'),
('ZHQQ', 'Anyang Hongqiqu Airport - Anyang (ZHQQ)'),
('ZHSN', 'Shennongjia Hongping Airport - Shennongjia (Hongping) (ZHSN)'),
('ZHSY', 'Shiyan Wudangshan Airport - Shiyan (Maojian) (ZHSY)'),
('ZHXF', 'Xiangyang Liuji Airport - Xiangyang (Xiangzhou) (ZHXF)'),
('ZHXY', 'Xinyang Minggang Airport - Xinyang (ZHXY)'),
('ZHYC', 'Yichang Sanxia Airport - Yichang (Xiaoting) (ZHYC)'),
('ZJHK', 'Haikou Meilan International Airport - Haikou (Meilan) (ZJHK)'),
('ZJQH', 'Qionghai Bo''ao Airport - Qionghai (Basuo) (ZJQH)'),
('ZJSY', 'Sanya Phoenix International Airport - Sanya (Tianya) (ZJSY)'),
('ZLAK', 'Ankang Fuqiang Airport - Ankang (Hanbin) (ZLAK)'),
('ZLDH', 'Dunhuang Mogao International Airport - Dunhuang (ZLDH)'),
('ZLDL', 'Delingha Airport - Delingha (ZLDL)'),
('ZLGL', 'Golog Maqin Airport - Golog (Maqin) (ZLGL)'),
('ZLGM', 'Golmud Airport - Golmud (ZLGM)'),
('ZLGY', 'Guyuan Liupanshan Airport - Guyuan (Yuanzhou) (ZLGY)'),
('ZLHB', 'Haibei Qilian Airport - Haibei (Qilian) (ZLHB)'),
('ZLHX', 'Huatugou Airport - Mengnai (ZLHX)'),
('ZLHZ', 'Hanzhong Chenggu Airport - Hanzhong (Chenggu) (ZLHZ)'),
('ZLIC', 'Yinchuan Hedong International Airport - Yinchuan (ZLIC)'),
('ZLJC', 'Jinchang Jinchuan Airport - Jinchang (ZLJC)'),
('ZLJQ', 'Jiayuguan Airport - Jiayuguan (ZLJQ)'),
('ZLLL', 'Lanzhou Zhongchuan International Airport - Lanzhou (Yongdeng) (ZLLL)'),
('ZLLN', 'Longnan Chengzhou Airport - Longnan (Cheng) (ZLLN)'),
('ZLQY', 'Qingyang Xifeng Airport - Qingyang (Xifeng) (ZLQY)'),
('ZLTS', 'Tianshui Maijishan Airport - Tianshui (Maiji) (ZLTS)'),
('ZLXH', 'Gannan Xiahe Airport - Gannan (Xiahe) (ZLXH)'),
('ZLXN', 'Xining Caojiabao International Airport - Haidong (Huzhu Tu Autonomous County) (ZLXN)'),
('ZLXY', 'Xi''an Xianyang International Airport - Xianyang (Weicheng) (ZLXY)'),
('ZLYA', 'Yan''an Nanniwan Airport - Yan''an (Baota) (ZLYA)'),
('ZLYL', 'Yulin Yuyang Airport - Yulin (ZLYL)'),
('ZLYS', 'Yushu Batang Airport - Yushu (Batang) (ZLYS)'),
('ZLZW', 'Zhongwei Shapotou Airport - Zhongwei (Shapotou) (ZLZW)'),
('ZLZY', 'Zhangye Ganzhou Airport - Zhangye (Ganzhou) (ZLZY)'),
('ZPBS', 'Baoshan Yunrui Airport - Baoshan (Longyang) (ZPBS)'),
('ZPCW', 'Cangyuan Washan Airport - Lincang (Cangyuan) (ZPCW)'),
('ZPDL', 'Dali Fengyi Airport - Dali (Xiaguan) (ZPDL)'),
('ZPDQ', 'Diqing Shangri-La Airport - Diqing (Shangri-La) (ZPDQ)'),
('ZPJH', 'Xishuangbanna Gasa International Airport - Jinghong (Gasa) (ZPJH)'),
('ZPJM', 'Lancang Jingmai Airport - Pu''er (Lancang) (ZPJM)'),
('ZPLC', 'Lincang Boshang Airport - Lincang (ZPLC)'),
('ZPLJ', 'Lijiang Sanyi International Airport - Lijiang (Gucheng) (ZPLJ)'),
('ZPMS', 'Dehong Mangshi Airport - Dehong (Mangshi) (ZPMS)'),
('ZPPP', 'Kunming Changshui International Airport - Kunming (ZPPP)'),
('ZPSM', 'Pu''er Simao Airport - Pu''er (ZPSM)'),
('ZPWS', 'Wenshan Puzhehei Airport - Wenshan (ZPWS)'),
('ZPZT', 'Zhaotong Airport - Zhaotong (Zhaoyang) (ZPZT)'),
('ZSAM', 'Xiamen Gaoqi International Airport - Xiamen (ZSAM)'),
('ZSAQ', 'Anqing Tianzhushan Airport / Anqing North Air Base - Anqing (ZSAQ)'),
('ZSCG', 'Changzhou Benniu International Airport - Changzhou (ZSCG)'),
('ZSCN', 'Nanchang Changbei International Airport - Nanchang (ZSCN)'),
('ZSDY', 'Dongying Shengli Airport - Dongying (Kenli) (ZSDY)'),
('ZSFY', 'Fuyang Xiguan Airport - Yingzhou, Fuyang (ZSFY)'),
('ZSFZ', 'Fuzhou Changle International Airport - Fuzhou (Changle) (ZSFZ)'),
('ZSGZ', 'Ganzhou Huangjin Airport - Ganzhou (ZSGZ)'),
('ZSHC', 'Hangzhou Xiaoshan International Airport - Hangzhou (ZSHC)'),
('ZSHZ', 'Heze Mudan Airport - Heze (Dingtao) (ZSHZ)')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
