-- airports seed batch 5/11
INSERT INTO public.airports (code, name) VALUES
('VOMD', 'Madurai Airport - Madurai (VOMD)'),
('VOML', 'Mangalore International Airport - Mangalore (VOML)'),
('VOMM', 'Chennai International Airport - Chennai (VOMM)'),
('VOMY', 'Mysore Airport - Mysore (VOMY)'),
('VOPB', 'Veer Savarkar International Airport / INS Utkrosh - Port Blair (VOPB)'),
('VOPC', 'Pondicherry Airport - Puducherry (Pondicherry) (VOPC)'),
('VORY', 'Rajahmundry Airport - Madhurapudi (VORY)'),
('VOSR', 'Sindhudurg Airport - Sindhudurg (VOSR)'),
('VOTK', 'Tuticorin Airport - Vagaikulam (VOTK)'),
('VOTP', 'Tirupati Airport - Tirupati (VOTP)'),
('VOTR', 'Tiruchirappalli International Airport - Tiruchirappalli (VOTR)'),
('VOTV', 'Thiruvananthapuram International Airport - Thiruvananthapuram (VOTV)'),
('ORBI', 'Baghdad International Airport / New Al Muthana Air Base - Baghdad (ORBI)'),
('ORER', 'Erbil International Airport - Arbil (ORER)'),
('ORMM', 'Basra International Airport - Basra (ORMM)'),
('ORNI', 'Al Najaf International Airport - Najaf (ORNI)'),
('ORSU', 'Sulaymaniyah International Airport - Sulaymaniyah (ORSU)'),
('OIAA', 'Abadan Airport - Abadan (OIAA)'),
('OIAD', 'Dezful Airport - Dezful (OIAD)'),
('OIAH', 'Gachsaran Airport - Gachsaran (OIAH)'),
('OIAM', 'Mahshahr Airport - Mahshahr (OIAM)'),
('OIAW', 'Lieutenant General Qasem Soleimani International Airport - Ahvaz (OIAW)'),
('OIBA', 'Abu Musa Island Airport - Abu Musa (OIBA)'),
('OIBB', 'Bushehr Airport - Bushehr (OIBB)'),
('OIBK', 'Kish International Airport - Kish Island (OIBK)'),
('OIBL', 'Bandar Lengeh International Airport - Bandar Lengeh (OIBL)'),
('OIBP', 'Persian Gulf International Airport - Khiyaroo (OIBP)'),
('OIBQ', 'Khark Airport - Khark (OIBQ)'),
('OICC', 'Shahid Ashrafi Esfahani Airport - Kermanshah (OICC)'),
('OICK', 'Khoram Abad Airport - Chorramabad (OICK)'),
('OICS', 'Sanandaj Airport - Sanandadż (OICS)'),
('OIFK', 'Kashan Airport - Kashan (OIFK)'),
('OIFM', 'Isfahan Shahid Beheshti International Airport - Isfahan (OIFM)'),
('OIGG', 'Sardar-e-Jangal Airport - Rasht (OIGG)'),
('OIHH', 'Hamadan Airport - Hamadan (OIHH)'),
('OIIE', 'Imam Khomeini International Airport - Tehran (OIIE)'),
('OIII', 'Mehrabad International Airport - Tehran (OIII)'),
('OIIP', 'Payam Karaj International Airport - Karaj (OIIP)'),
('OIIS', 'Semnan Municipal Airport - Semnan (OIIS)'),
('OIKB', 'Bandar Abbas International Airport - Bandar Abbas (OIKB)'),
('OIKK', 'Ayatollah Hashemi Rafsanjani International Airport - Kerman (OIKK)'),
('OIKM', 'Bam Airport - Bam (OIKM)'),
('OIKQ', 'Qeshm Dayrestan International Airport - Dayrestan (OIKQ)'),
('OIKR', 'Rafsanjan Airport - Rafsanjan (OIKR)'),
('OIMB', 'Birjand International Airport - Birjand (OIMB)'),
('OIMM', 'Mashhad International Airport - Mashhad (OIMM)'),
('OIMN', 'Bojnord Airport - Bojnord (OIMN)'),
('OIMS', 'Sabzevar National Airport - Sabzevar (OIMS)'),
('OINN', 'Nowshahr Airport - Nowshahr (OINN)'),
('OINR', 'Ramsar Airport - Ramsar (OINR)'),
('OINZ', 'Sari Dasht-e Naz International Airport - Sari (OINZ)'),
('OISL', 'Lar Airport - Lar (OISL)'),
('OISR', 'Lamerd Airport - Lamerd (OISR)'),
('OISS', 'Shiraz Shahid Dastghaib International Airport - Shiraz (OISS)'),
('OITL', 'Ardabil Airport - Ardabil (OITL)'),
('OITP', 'Parsabad-Moghan Airport - Parsabad (OITP)'),
('OITR', 'Urmia Airport - Urmia (OITR)'),
('OITT', 'Tabriz International Airport - Tabriz (OITT)'),
('OIYY', 'Shahid Sadooghi Airport - Yazd (OIYY)'),
('OIZC', 'Chabahar Konarak International Airport - Konarak (OIZC)'),
('OIZH', 'Zahedan International Airport - Zahedan (OIZH)'),
('OIZJ', 'Jask Airport - Bandar-e-Jask (OIZJ)'),
('BIAR', 'Akureyri Airport - Akureyri (BIAR)'),
('BIEG', 'Egilsstaoir Airport - Egilsstaoir (BIEG)'),
('BIGR', 'Grímsey Airport - Grímsey (BIGR)'),
('BIHN', 'Hornafjörour Airport - Höfn (BIHN)'),
('BIHU', 'Húsavík Airport - Húsavík (BIHU)'),
('BIIS', 'Ísafjörour Airport - Ísafjörour (BIIS)'),
('BIKF', 'Keflavik International Airport - Reykjavík (BIKF)'),
('BIRK', 'Reykjavík Domestic Airport - Reykjavík (BIRK)'),
('BITN', 'Þórshöfn Airport - Þórshöfn (BITN)'),
('BIVO', 'Vopnafjörour Airport - Vopnafjörour (BIVO)'),
('LIBC', 'Crotone Sant''Anna Pythagoras Airport - Isola di Capo Rizzuto (KR) (LIBC)'),
('LIBD', 'Bari Karol Wojtyła International Airport - Bari (LIBD)'),
('LIBF', 'Foggia Gino Lisa Airport - Foggia (FG) (LIBF)'),
('LIBP', 'Abruzzo Airport - Pescara (LIBP)'),
('LIBR', 'Brindisi Airport - Brindisi (LIBR)'),
('LICA', 'Lamezia Terme Sant''Eufemia International Airport - Lamezia Terme (CZ) (LICA)'),
('LICB', 'Comiso Airport - Comiso (LICB)'),
('LICC', 'Catania-Fontanarossa Airport - Catania (LICC)'),
('LICD', 'Lampedusa Airport - Lampedusa (LICD)'),
('LICG', 'Pantelleria Airport - Pantelleria (TP) (LICG)'),
('LICJ', 'Falcone–Borsellino Airport - Palermo (LICJ)'),
('LICR', 'Reggio Calabria Airport - Reggio Calabria (LICR)'),
('LICT', 'Vincenzo Florio Airport Trapani-Birgi - Trapani (TP) (LICT)'),
('LIEA', 'Alghero-Fertilia Airport - Alghero (LIEA)'),
('LIEE', 'Cagliari Elmas Airport - Cagliari (LIEE)'),
('LIEO', 'Olbia Costa Smeralda Airport - Olbia (SS) (LIEO)'),
('LIMC', 'Milan Malpensa International Airport - Ferno (VA) (LIMC)'),
('LIME', 'Milan Bergamo Airport / Antonio Locatelli Air Base - Orio al Serio (BG) (LIME)'),
('LIMF', 'Turin Airport - Caselle Torinese (TO) (LIMF)'),
('LIMJ', 'Genoa Cristoforo Colombo Airport - Genova (GE) (LIMJ)'),
('LIML', 'Milano Linate Airport - Segrate (MI) (LIML)'),
('LIMP', 'Parma Airport - Parma (PR) (LIMP)'),
('LIMZ', 'Cuneo International Airport - Levaldigi (CN) (LIMZ)'),
('LIPB', 'Bolzano Airport - Bolzano (BZ) (LIPB)'),
('LIPE', 'Bologna Guglielmo Marconi Airport - Bologna (LIPE)'),
('LIPH', 'Treviso Antonio Canova Airport - Treviso (TV) (LIPH)'),
('LIPK', 'Forli Luigi Ridolfi Airport - Forli (FC) (LIPK)'),
('LIPO', 'Brescia Gabriele d''Annunzio Airport - Montichiari (BS) (LIPO)'),
('LIPQ', 'Trieste–Friuli Venezia Giulia Airport - Ronchi dei Legionari (GO) (LIPQ)'),
('LIPR', 'Federico Fellini International Airport - Rimini (RN) (LIPR)'),
('LIPX', 'Verona Villafranca Valerio Catullo Airport - Caselle (VR) (LIPX)'),
('LIPY', 'Marche Airport - Falconara Marittima (AN) (LIPY)'),
('LIPZ', 'Venice Marco Polo Airport - Venezia (VE) (LIPZ)'),
('LIRA', 'Ciampino–G. B. Pastine International Airport - Rome (LIRA)'),
('LIRF', 'Rome–Fiumicino Leonardo da Vinci International Airport - Rome (LIRF)'),
('LIRI', 'Salerno Costa d''Amalfi Airport - Salerno (LIRI)'),
('LIRJ', 'Marina di Campo Airport - Campo nell''Elba (LI) (LIRJ)'),
('LIRN', 'Naples International Airport - Napoli (LIRN)'),
('LIRP', 'Pisa International Airport - Pisa (PI) (LIRP)'),
('LIRQ', 'Florence Airport, Peretola - Firenze (FI) (LIRQ)'),
('LIRZ', 'Perugia San Francesco d''Assisi – Umbria International Airport - Perugia (PG) (LIRZ)'),
('EGJJ', 'Jersey Airport - Saint Helier (EGJJ)'),
('MKBS', 'Ian Fleming International Airport - Boscobel (MKBS)'),
('MKJP', 'Norman Manley International Airport - Kingston (MKJP)'),
('MKJS', 'Sangster International Airport - Montego Bay (MKJS)'),
('MKTP', 'Tinson Pen Airport - Tinson Pen (MKTP)'),
('OJAI', 'Queen Alia International Airport - Amman (OJAI)'),
('OJAM', 'Amman Civil (Marka International) Airport - Amman (OJAM)'),
('OJAQ', 'Aqaba King Hussein International Airport - Aqaba (OJAQ)'),
('RJAA', 'Narita International Airport - Narita (RJAA)'),
('RJAF', 'Shinshu-Matsumoto Airport - Matsumoto (RJAF)'),
('RJAH', 'Ibaraki Airport / JASDF Hyakuri Air Base - Omitama (RJAH)'),
('RJAN', 'Niijima Airport - Niijima Village (RJAN)'),
('RJBB', 'Kansai International Airport - Osaka (RJBB)'),
('RJBD', 'Nanki Shirahama Airport - Shirahama (RJBD)'),
('RJBE', 'Kobe Airport - Kobe (RJBE)'),
('RJBT', 'Konotori Tajima Airport - Toyooka (RJBT)'),
('RJCB', 'Tokachi-Obihiro Airport - Obihiro (RJCB)'),
('RJCC', 'New Chitose Airport - Sapporo (RJCC)'),
('RJCH', 'Hakodate Airport - Hakodate (RJCH)'),
('RJCK', 'Kushiro Airport - Kushiro (RJCK)'),
('RJCM', 'Memanbetsu Airport - Ozora (RJCM)'),
('RJCN', 'Nakashibetsu Airport - Nakashibetsu (RJCN)'),
('RJCO', 'Sapporo Okadama Airport - Sapporo (RJCO)'),
('RJCW', 'Wakkanai Airport - Wakkanai (RJCW)'),
('RJDA', 'Amakusa Airport - Amakusa (RJDA)'),
('RJDB', 'Iki Airport - Iki (RJDB)'),
('RJDC', 'Yamaguchi Ube Airport - Ube (RJDC)'),
('RJDT', 'Tsushima Airport - Tsushima (RJDT)'),
('RJEB', 'Monbetsu Airport - Monbetsu (RJEB)'),
('RJEC', 'Asahikawa Airport - Higashikagura (RJEC)'),
('RJEO', 'Okushiri Airport - Okushiri Island (RJEO)'),
('RJER', 'Rishiri Airport - Rishiri (RJER)'),
('RJFC', 'Yakushima Airport - Yakushima (RJFC)'),
('RJFE', 'Fukue Airport - Goto (RJFE)'),
('RJFF', 'Fukuoka Airport - Fukuoka (RJFF)'),
('RJFG', 'New Tanegashima Airport - Tanegashima (RJFG)'),
('RJFK', 'Kagoshima Airport - Kagoshima (RJFK)'),
('RJFM', 'Miyazaki Airport - Miyazaki (RJFM)'),
('RJFO', 'Oita Airport - Oita (RJFO)'),
('RJFR', 'Kitakyushu Airport - Kitakyushu (RJFR)'),
('RJFS', 'Saga Airport - Saga (RJFS)'),
('RJFT', 'Kumamoto Airport - Kumamoto (RJFT)'),
('RJFU', 'Nagasaki Airport - Nagasaki (RJFU)'),
('RJGG', 'Chubu Centrair International Airport - Tokoname (RJGG)'),
('RJKA', 'Amami Airport - Amami (RJKA)'),
('RJKB', 'Okinoerabu Airport - Wadomari (RJKB)'),
('RJKI', 'Kikai Airport - Kikai (RJKI)'),
('RJKN', 'Tokunoshima Airport - Amagi (RJKN)'),
('RJNA', 'Nagoya Airport / JASDF Komaki Air Base - Nagoya (RJNA)'),
('RJNK', 'Komatsu Airport / JASDF Komatsu Air Base - Kanazawa (RJNK)'),
('RJNO', 'Oki Global Geopark Airport - Okinoshima (RJNO)'),
('RJNS', 'Mount Fuji Shizuoka Airport - Makinohara / Shimada (RJNS)'),
('RJNT', 'Toyama Airport - Toyama (RJNT)'),
('RJNW', 'Noto Satoyama Airport - Wajima (RJNW)'),
('RJOA', 'Hiroshima Airport - Hiroshima (RJOA)'),
('RJOB', 'Okayama Momotaro Airport - Okayama (RJOB)'),
('RJOC', 'Izumo Enmusubi Airport - Izumo (RJOC)'),
('RJOH', 'Yonago Kitaro Airport / JASDF Miho Air Base - Yonago (RJOH)'),
('RJOI', 'Iwakuni Kintaikyo Airport / Marine Corps Air Station Iwakuni - Iwakuni (RJOI)'),
('RJOK', 'Kochi Ryoma Airport - Nankoku (RJOK)'),
('RJOM', 'Matsuyama Airport - Matsuyama (RJOM)'),
('RJOO', 'Osaka International Airport - Osaka (RJOO)'),
('RJOR', 'Tottori Sand Dunes Conan Airport - Tottori (RJOR)'),
('RJOS', 'Tokushima Awaodori Airport / JMSDF Tokushima Air Base - Tokushima (RJOS)'),
('RJOT', 'Takamatsu Airport - Takamatsu (RJOT)'),
('RJOW', 'Iwami Airport - Masuda (RJOW)'),
('RJSA', 'Aomori Airport - Aomori (RJSA)'),
('RJSC', 'Yamagata Airport - Higashine (RJSC)'),
('RJSD', 'Sado Airport - Sado (RJSD)'),
('RJSF', 'Fukushima Airport - Sukagawa (RJSF)'),
('RJSI', 'Iwate Hanamaki Airport - Hanamaki (RJSI)'),
('RJSK', 'Akita Airport - Akita (RJSK)'),
('RJSM', 'Misawa Airport / Misawa Air Base - Misawa (RJSM)'),
('RJSN', 'Niigata Airport - Niigata (RJSN)'),
('RJSR', 'Odate Noshiro Airport - Kitaakita (RJSR)'),
('RJSS', 'Sendai Airport - Natori (RJSS)'),
('RJSY', 'Shonai Airport - Shonai (RJSY)'),
('RJTF', 'Chofu Airport - Chofu (RJTF)'),
('RJTH', 'Hachijojima Airport - Hachijojima (RJTH)'),
('RJTO', 'Oshima Airport - Izu Oshima (RJTO)'),
('RJTQ', 'Miyakejima Airport - Miyakejima (RJTQ)'),
('RJTT', 'Tokyo Haneda International Airport - Tokyo (RJTT)'),
('ROAH', 'Naha Airport / JASDF Naha Air Base - Naha (ROAH)'),
('ROIG', 'New Ishigaki Airport - Ishigaki (ROIG)'),
('ROKJ', 'Kumejima Airport - Kumejima (ROKJ)'),
('ROMD', 'Minamidaito Airport - Minamidaito (ROMD)'),
('ROMY', 'Miyako Airport - Miyakojima (ROMY)'),
('RORA', 'Aguni Airport - Aguni (RORA)'),
('RORK', 'Kitadaito Airport - Kitadaitojima (RORK)'),
('RORS', 'Shimojishima Airport - Miyakojima (RORS)'),
('RORT', 'Tarama Airport - Tarama (RORT)'),
('RORY', 'Yoron Airport - Yoron (RORY)'),
('ROYN', 'Yonaguni Airport - Yonaguni (ROYN)'),
('HKAM', 'Amboseli Airport - Amboseli National Park (HKAM)'),
('HKEL', 'Eldoret International Airport - Eldoret (HKEL)'),
('HKJK', 'Jomo Kenyatta International Airport - Nairobi (HKJK)'),
('HKKI', 'Kisumu Airport - Kisumu (HKKI)'),
('HKLU', 'Manda Airport - Lamu (HKLU)'),
('HKMK', 'Mulika Lodge Airport - Meru-Kinna (HKMK)'),
('HKML', 'Malindi Airport - Malindi (HKML)'),
('HKMO', 'Moi International Airport - Mombasa (HKMO)'),
('HKMS', 'Mara Serena Lodge Airstrip - Masai Mara (HKMS)'),
('HKNY', 'Nanyuki Airport - Nanyuki (HKNY)'),
('HKNW', 'Nairobi Wilson Airport - Nairobi (HKNW)'),
('HKWJ', 'Wajir Airport - Wajir (HKWJ)'),
('UCFD', 'Jalal-Abad Airport - Jalal-Abad (UCFD)'),
('UAFN', 'Naryn Airport - Naryn (UAFN)'),
('UAFT', 'Talas Airport - Talas (UAFT)'),
('UAFA', 'Tamga Airport - Tamga (UAFA)'),
('UAFF', 'Tokmok Airport - Tokmok (UAFF)'),
('UAFE', 'Kerben Airport - Kerben (UAFE)'),
('UAFS', 'Kyzyl-Kiya Airport - Kyzyl-Kiya (UAFS)'),
('UCFB', 'Batken Airport - Batken (UCFB)'),
('UCFR', 'Razzakov Airport - Isfana (UCFR)'),
('UCFM', 'Manas International Airport - Bishkek (UCFM)'),
('UCFO', 'Osh Airport - Osh (UCFO)'),
('UCFK', 'Karakol Airport - Karakol (UCFK)'),
('UAFZ', 'Kazarman Airport - Kazarman (UAFZ)'),
('UCFL', 'Issyk-Kul International Airport - Tamchy (UCFL)'),
('VDBG', 'Battambang Airport - Battambang (VDBG)'),
('VDPP', 'Phnom Penh International Airport - Phnom Penh (Pou Senchey) (VDPP)'),
('VDSA', 'Siem Reap-Angkor International Airport - Siem Reap (VDSA)'),
('VDSV', 'Sihanoukville International Airport - Preah Sihanouk (VDSV)'),
('NGTA', 'Bonriki International Airport - Tarawa (NGTA)'),
('NGTU', 'Butaritari Airport - Butaritari (NGTU)'),
('NGUK', 'Aranuka Airport - Buariki (NGUK)'),
('PLCH', 'Cassidy International Airport - Kiritimati (PLCH)'),
('FMCH', 'Prince Said Ibrahim International Airport - Moroni (FMCH)'),
('FMCV', 'Ouani Airport - Ouani (FMCV)'),
('TKPK', 'Robert L. Bradshaw International Airport - Basseterre (TKPK)'),
('TKPN', 'Vance W. Amory International Airport - Charlestown (TKPN)'),
('ZKHM', 'Orang (Chongjin) Airport - Hoemun-ri (ZKHM)'),
('ZKPY', 'Pyongyang Sunan International Airport - Pyongyang (ZKPY)'),
('ZKSD', 'Sondok Airport - Sondong-ni (ZKSD)'),
('ZKWS', 'Wonsan Kalma International Airport - Wonsan (ZKWS)'),
('RKJB', 'Muan International Airport - Muan (Piseo-ri) (RKJB)'),
('RKJJ', 'Gwangju Airport - Gwangju (RKJJ)'),
('RKJK', 'Gunsan Airport / Gunsan Air Base - Gunsan (RKJK)'),
('RKJY', 'Yeosu Airport - Yeosu (RKJY)'),
('RKNW', 'Wonju Airport / Hoengseong Air Base (K-38/K-46) - Wonju (RKNW)'),
('RKNY', 'Yangyang International Airport - Gonghang-ro (RKNY)'),
('RKPC', 'Jeju International Airport - Jeju City (RKPC)'),
('RKPK', 'Gimhae International Airport - Busan (RKPK)'),
('RKPS', 'Sacheon Airport / Sacheon Air Base - Sacheon (RKPS)'),
('RKPU', 'Ulsan Airport - Ulsan (RKPU)'),
('RKSI', 'Incheon International Airport - Seoul (RKSI)'),
('RKSS', 'Gimpo International Airport - Seoul (RKSS)'),
('RKTH', 'Pohang Airport (G-815/K-3) - Pohang (RKTH)'),
('RKTN', 'Daegu Airport - Daegu (RKTN)'),
('RKTU', 'Cheongju International Airport/Cheongju Air Base (K-59/G-513) - Cheongju (RKTU)'),
('OKKK', 'Kuwait International Airport - Kuwait City (OKKK)'),
('MWCB', 'Charles Kirkconnell International Airport - West End (MWCB)'),
('MWCR', 'Owen Roberts International Airport - George Town (MWCR)'),
('UAAA', 'Almaty International Airport - Almaty (UAAA)'),
('UAAH', 'Balkhash Airport - Balkhash (UAAH)'),
('UAAL', 'Usharal Airport - Usharal (UAAL)'),
('UAAT', 'Taldykorgan Airport - Taldykorgan (UAAT)'),
('UACC', 'Nursultan Nazarbayev International Airport - Astana (UACC)'),
('UACK', 'Kokshetau Airport - Kokshetau (UACK)'),
('UACP', 'Petropavl Airport - Petropavl (UACP)'),
('UADD', 'Taraz Airport - Taraz (UADD)'),
('UAII', 'Shymkent Airport - Shymkent (UAII)'),
('UAIT', 'Hazrat Sultan International Airport - Turkistan (UAIT)'),
('UAKD', 'Zhezkazgan National Airport - Zhezkazgan (UAKD)'),
('UAKK', 'Sary-Arka Airport - Karaganda (UAKK)'),
('UAOO', 'Kyzylorda Airport - Kyzylorda (UAOO)'),
('UARR', 'Uralsk Airport - Uralsk (UARR)'),
('UASK', 'Ust-Kamenogorsk Airport - Ust-Kamenogorsk (Oskemen) (UASK)'),
('UASP', 'Pavlodar Airport - Pavlodar (UASP)'),
('UASS', 'Semey Airport - Semey (UASS)'),
('UASZ', 'Zaysan Airport - Zaysan (UASZ)'),
('UATE', 'Aktau Airport - Aktau (UATE)'),
('UATG', 'Atyrau International Airport - Atyrau (UATG)'),
('UATT', 'Aktobe Airport - Aktobe (UATT)'),
('UAUU', 'Kostanay West Airport - Kostanay (UAUU)'),
('UASU', 'Urzhar Airport - Urzhar (UASU)'),
('VLBK', 'Bokeo International Airport - Ton Phueng (VLBK)'),
('VLLB', 'Luang Phabang International Airport - Luang Phabang (VLLB)'),
('VLLN', 'Luang Namtha Airport - Luang Namtha (VLLN)'),
('VLOS', 'Oudomsay Airport - Oudomsay (VLOS)'),
('VLPS', 'Pakse International Airport - Pakse (VLPS)'),
('VLVT', 'Wattay International Airport - Vientiane (VLVT)'),
('VLXK', 'Xieng Khouang Airport - Xieng Khouang (VLXK)'),
('OLBA', 'Beirut Rafic Hariri International Airport - Beirut (OLBA)'),
('TLPC', 'George F. L. Charles Airport - Castries (TLPC)'),
('TLPL', 'Hewanorra International Airport - Vieux Fort (TLPL)'),
('VCCI', 'Iranamadu Airport - Kilinochchi (VCCI)'),
('VCBI', 'Bandaranaike International Colombo Airport - Colombo (VCBI)'),
('VCCB', 'Batticaloa Airport - Batticaloa (VCCB)'),
('VCCC', 'Colombo Ratmalana Airport - Colombo (VCCC)'),
('VCCJ', 'Jaffna International Airport - Jaffna (VCCJ)'),
('VCCK', 'Koggala Airport - Galle (VCCK)'),
('VCCT', 'China Bay Airport - Trincomalee (VCCT)'),
('VCRI', 'Mattala Rajapaksa International Airport - Mattala (VCRI)'),
('GLMR', 'Spriggs Payne Airport - Monrovia (GLMR)'),
('GLRB', 'Roberts International Airport - Monrovia (GLRB)'),
('FXMM', 'Moshoeshoe I International Airport - Mazenod (FXMM)'),
('EYKA', 'Kaunas International Airport - Kaunas (EYKA)'),
('EYPA', 'Palanga International Airport - Palanga (EYPA)'),
('EYVI', 'Vilnius International Airport - Vilnius (EYVI)'),
('ELLX', 'Luxembourg-Findel International Airport - Luxembourg (ELLX)'),
('EVRA', 'Riga International Airport - Riga (EVRA)'),
('HLGT', 'Ghat Airport - Ghat (HLGT)'),
('HLKF', 'Kufra Airport - Kufra (HLKF)'),
('HLLB', 'Benina International Airport - Benina (HLLB)'),
('HLLM', 'Mitiga International Airport - Tripoli (HLLM)'),
('HLLQ', 'Al Abraq International Airport - Al Albraq (HLLQ)'),
('HLLS', 'Sabha Airport - Sabha (HLLS)'),
('HLMS', 'Misrata International Airport - Misrata (HLMS)'),
('HLTQ', 'Tobruk International Airport - Adam (HLTQ)'),
('GMAD', 'Al Massira Airport - Agadir (Temsia) (GMAD)'),
('GMAT', 'Tan Tan Airport - Tan Tan (GMAT)'),
('GMFF', 'Fez-Saiss International Airport - Saiss (GMFF)'),
('GMFK', 'Moulay Ali Cherif Airport - Errachidia (GMFK)'),
('GMFO', 'Oujda Angads Airport - Ahl Angad (GMFO)'),
('GMME', 'Rabat-Salé Airport - Rabat (GMME)'),
('GMMI', 'Essaouira-Mogador Airport - Essaouira (GMMI)'),
('GMMN', 'Mohammed V International Airport - Casablanca (GMMN)'),
('GMMW', 'Nador Al Aaroui International Airport - Al Aaroui (GMMW)'),
('GMMX', 'Menara Airport - Marrakech (GMMX)'),
('GMMZ', 'Ouarzazate Airport - Ouarzazate (GMMZ)'),
('GMTN', 'Sania Ramel Airport - Tétouan (GMTN)'),
('GMTT', 'Tangier Ibn Battuta Airport - Tangier (GMTT)'),
('LUKK', 'Chişinău International Airport - Chişinău (LUKK)'),
('LYPG', 'Podgorica Airport / Podgorica Golubovci Airbase - Podgorica (LYPG)'),
('LYTV', 'Tivat Airport - Tivat (LYTV)'),
('TFFG', 'Grand Case-l''Espérance Airport - Grand Case (TFFG)'),
('FMMI', 'Ivato Airport - Antananarivo (FMMI)'),
('FMMS', 'Sainte Marie Airport - Vohilava (FMMS)'),
('FMMT', 'Toamasina Ambalamanasy Airport - Toamasina (FMMT)'),
('FMMU', 'Tambohorano Airport - Tambohorano (FMMU)'),
('FMMV', 'Morondava Airport - Morondava (FMMV)'),
('FMNA', 'Arrachart Airport - Antisiranana (FMNA)'),
('FMNM', 'Amborovy Airport - Mahajanga (FMNM)'),
('FMNN', 'Fascene Airport - Nosy Be (FMNN)'),
('FMNO', 'Soalala Airport - Soalala (FMNO)'),
('FMNQ', 'Besalampy Airport - Besalampy (FMNQ)'),
('FMNR', 'Maroantsetra Airport - Maroantsetra (FMNR)'),
('FMNS', 'Sambava Airport - Sambava (FMNS)'),
('FMNT', 'Tsaratanana Airport - Tsaratanana (FMNT)'),
('FMSD', 'Tôlanaro Airport - Tôlanaro (FMSD)'),
('FMSM', 'Mananjary Airport - Mananjary (FMSM)'),
('FMST', 'Toliara Airport - Toliara (FMST)'),
('UJAP', 'Ujae Atoll Airport - Ujae Atoll (UJAP)'),
('MH-MJE', 'Majkin Airport - Majkin (MH-MJE)'),
('N55', 'Jaluit Airport - Jabor Jaluit Atoll (N55)'),
('MLIP', 'Mili Island Airport - Mili Island (MLIP)'),
('PKMA', 'Eniwetok Airport - Eniwetok Atoll (PKMA)'),
('PKMJ', 'Marshall Islands International Airport - Majuro Atoll (PKMJ)'),
('PKWA', 'Bucholz Army Air Field - Kwajalein (PKWA)'),
('LWOH', 'Ohrid St. Paul the Apostle Airport - Ohrid (LWOH)'),
('LWSK', 'Skopje International Airport - Ilinden (LWSK)'),
('GABS', 'Modibo Keita International Airport - Bamako (GABS)'),
('GAGO', 'Gao Airport - Gao (GAGO)'),
('GAMB', 'Mopti Ambodédjo International Airport - Sévaré (GAMB)'),
('GATB', 'Timbuktu Airport - Timbuktu (GATB)'),
('VYBG', 'Bagan Airport - Nyaung U (VYBG)'),
('VYBM', 'Banmaw Airport - Banmaw (VYBM)'),
('VYDW', 'Dawei Airport - Dawei (VYDW)'),
('VYHH', 'Heho Airport - Kalaw Township (VYHH)'),
('VYKG', 'Kengtung Airport - Kengtung (VYKG)'),
('VYKI', 'Kanti Airport - Kanti (VYKI)'),
('VYKP', 'Kyaukpyu Airport - Kyaukpyu (VYKP)'),
('VYKT', 'Kawthoung Airport - Kawthoung (VYKT)'),
('VYLK', 'Loikaw Airport - Loikaw (VYLK)'),
('VYLS', 'Lashio Airport - Lashio (VYLS)'),
('VYMD', 'Mandalay International Airport - Mandalay (VYMD)'),
('VYME', 'Myeik Airport - Mkeik (VYME)'),
('VYMK', 'Myitkyina Airport - Myitkyina (VYMK)'),
('VYMM', 'Mawlamyine Airport - Mawlamyine (VYMM)'),
('VYMS', 'Mong Hsat Airport - Mong Hsat (VYMS)'),
('VYMW', 'Magway Airport - Magway (VYMW)'),
('VYNT', 'Nay Pyi Taw International Airport - Pyinmana (VYNT)'),
('VYPN', 'Pathein Airport - Pathein (VYPN)'),
('VYPT', 'Putao Airport - Putao (VYPT)'),
('VYSW', 'Sittwe Airport - Sittwe (VYSW)'),
('VYTD', 'Thandwe Airport - Thandwe (VYTD)'),
('VYTL', 'Tachileik Airport - Tachileik (VYTL)'),
('VYYY', 'Yangon International Airport - Yangon (VYYY)'),
('ZMAH', 'Arvaikheer Airport - Arvaikheer (ZMAH)'),
('ZMAT', 'Altai Airport - Altai (ZMAT)'),
('ZMBH', 'Bayankhongor Airport - Bayankhongor (ZMBH)'),
('ZMBN', 'Bulgan Airport - Bulgan (ZMBN)'),
('ZMCK', 'Ulaanbaatar Chinggis Khaan International Airport - Ulaanbaatar (Sergelen) (ZMCK)'),
('ZMDN', 'Donoi Airport - Uliastai (ZMDN)'),
('ZMDZ', 'Dalanzadgad Airport - Dalanzadgad (ZMDZ)'),
('ZMKD', 'Khovd Airport - Khovd (ZMKD)')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
