-- airports seed batch 8/11
INSERT INTO public.airports (code, name) VALUES
('YGEL', 'Geraldton Airport - Moonyoonooka (YGEL)'),
('YGLA', 'Gladstone Airport - Gladstone (YGLA)'),
('YGTE', 'Groote Eylandt Airport - Groote Eylandt (YGTE)'),
('YGTH', 'Griffith Airport - Griffith (YGTH)'),
('YHBA', 'Hervey Bay Airport - Hervey Bay (YHBA)'),
('YHID', 'Horn Island Airport - Horn (YHID)'),
('YHOO', 'Hooker Creek Airport - Lajamanu (YHOO)'),
('YHOT', 'Mount Hotham Airport - Mount Hotham (YHOT)'),
('YHUG', 'Hughenden Airport - Hughenden (YHUG)'),
('YJLC', 'Julia Creek Airport - Julia Creek  (YJLC)'),
('YKAR', 'Karara Airport - Karara (YKAR)'),
('YKBR', 'Kalbarri Airport - Kalbarri (YKBR)'),
('YKII', 'King Island Airport - Currie (YKII)'),
('YKKG', 'Kalkgurung Airport - Daguragu (YKKG)'),
('YKMB', 'Karumba Airport - Karumba (YKMB)'),
('YKOW', 'Kowanyama Airport - Kowanyama (YKOW)'),
('YKSC', 'Kingscote Airport - Kingscote (YKSC)'),
('YKUB', 'Kubin Island Airport - Kubin Island (YKUB)'),
('YLEO', 'Leonora Airport - Leonora (YLEO)'),
('YLEV', 'Lake Evella Airport - Gapuwiyak (YLEV)'),
('YLHI', 'Lord Howe Island Airport - Lord Howe Island (YLHI)'),
('YLHR', 'Lockhart River Airport - Lockhart River (YLHR)'),
('YLIS', 'Lismore Airport - Lismore (YLIS)'),
('YLRD', 'Lightning Ridge Airport - Lightning Ridge (YLRD)'),
('YLRE', 'Longreach Airport - Longreach (YLRE)'),
('YLST', 'Leinster Airport - Leinster (YLST)'),
('YLTN', 'Laverton Airport - Laverton (YLTN)'),
('YMAA', 'Mabuiag Island Airport - Mabuiag Island (YMAA)'),
('YMAE', 'Murray Island Airport - Murray Island (YMAE)'),
('YMAV', 'Avalon Airport - Lara (YMAV)'),
('YMAY', 'Albury Airport - East Albury (YMAY)'),
('YMEK', 'Meekatharra Airport - Meekatharra (YMEK)'),
('YMEN', 'Melbourne Essendon Airport - Essendon Fields (YMEN)'),
('YMER', 'Merimbula Airport - Merimbula (YMER)'),
('YMGB', 'Milingimbi Airport - Milingimbi Island (YMGB)'),
('YMGD', 'Maningrida Airport - Maningrida (YMGD)'),
('YMHB', 'Hobart International Airport - Hobart (Cambridge) (YMHB)'),
('YMHU', 'McArthur River Mine Airport - McArthur River Mine (YMHU)'),
('YMIA', 'Mildura Airport - Mildura (YMIA)'),
('YMLT', 'Launceston Airport - Launceston (Western Junction) (YMLT)'),
('YMMB', 'Melbourne Moorabbin Airport - Melbourne (YMMB)'),
('YMML', 'Melbourne Airport - Melbourne (YMML)'),
('YMOG', 'Mount Magnet Airport - Mount Magnet (YMOG)'),
('YMOR', 'Moree Airport - Moree (YMOR)'),
('YMRB', 'Moranbah Airport - Moranbah (YMRB)'),
('YMRY', 'Moruya Airport - Moruya (YMRY)'),
('YMTG', 'Mount Gambier Airport - Mount Gambier (YMTG)'),
('YMTI', 'Mornington Island Airport - Mornington (YMTI)'),
('YNAR', 'Narrandera Airport - Narrandera (YNAR)'),
('YNBR', 'Narrabri Airport - Narrabri (YNBR)'),
('YNPE', 'Northern Peninsula Airport - Bamaga (YNPE)'),
('YNTN', 'Normanton Airport - Normanton (YNTN)'),
('YNWN', 'Newman Airport - Newman (YNWN)'),
('YOLD', 'Olympic Dam Airport - Olympic Dam (YOLD)'),
('YPAD', 'Adelaide International Airport - Adelaide (YPAD)'),
('YPAG', 'Port Augusta Airport - Port Augusta  (YPAG)'),
('YPAM', 'Palm Island Airport - Palm Island (YPAM)'),
('YPBO', 'Paraburdoo Airport - Paraburdoo (YPBO)'),
('YPDN', 'Darwin International Airport / RAAF Darwin - Darwin (YPDN)'),
('YPGV', 'Gove Airport - Nhulunbuy (YPGV)'),
('YPKA', 'Karratha Airport - Karratha (YPKA)'),
('YPKG', 'Kalgoorlie Boulder Airport - Broadwood (YPKG)'),
('YPKS', 'Parkes Airport - Parkes (YPKS)'),
('YPKU', 'East Kimberley Regional (Kununurra) Airport - Kununurra (YPKU)'),
('YPLC', 'Port Lincoln Airport - Port Lincoln (YPLC)'),
('YPLM', 'Learmonth Airport - Exmouth (YPLM)'),
('YPMH', 'Prominent Hill Airport - Mount Eba (YPMH)'),
('YPMP', 'Pormpuraaw Airport - Pormpuraaw (YPMP)'),
('YPMQ', 'Port Macquarie Airport - Port Macquarie (YPMQ)'),
('YPOD', 'Portland Airport - Portland (YPOD)'),
('YPPD', 'Port Hedland International Airport - Port Hedland (YPPD)'),
('YPPH', 'Perth International Airport - Perth (YPPH)'),
('YQLP', 'Quilpie Airport - Quilpie (YQLP)'),
('YRMD', 'Richmond Airport - Richmond (YRMD)'),
('YRNG', 'Ramingining Airport - Ramingining (YRNG)'),
('YROM', 'Roma Airport - Roma (YROM)'),
('YSCB', 'Canberra Airport - Canberra (YSCB)'),
('YSDU', 'Dubbo City Regional Airport - Dubbo (YSDU)'),
('YSGE', 'St George Airport - St. George (YSGE)'),
('YSHK', 'Shark Bay Airport - Denham (YSHK)'),
('YSHL', 'Shellharbour Airport - Albion Park Rail (YSHL)'),
('YSII', 'Saibai Island Airport - Saibai Island (YSII)'),
('YSNB', 'Snake Bay Airport - Milikapiti (YSNB)'),
('YSSY', 'Sydney Kingsford Smith International Airport - Sydney (Mascot) (YSSY)'),
('YSTW', 'Tamworth Airport - Tamworth (YSTW)'),
('YSWG', 'Wagga Wagga Airport - Forest Hill (YSWG)'),
('YTGM', 'Thargomindah Airport - Thargomindah (YTGM)'),
('YTNG', 'Thangool Airport - Biloela (YTNG)'),
('YTNK', 'Tennant Creek Airport - Tennant Creek (YTNK)'),
('YWBS', 'Warraber Island Airport - Sue Islet (YWBS)'),
('YWDH', 'Windorah Airport - Windorah (YWDH)'),
('YWHA', 'Whyalla Airport - Whyalla (YWHA)'),
('YWLG', 'Walgett Airport - Walgett (YWLG)'),
('YWLM', 'Newcastle Airport - Williamtown (YWLM)'),
('YWLU', 'Wiluna Airport - Wiluna  (YWLU)'),
('YWTN', 'Winton Airport - Winton (YWTN)'),
('YWYY', 'Wynyard Airport - Burnie (YWYY)'),
('YYKI', 'Yorke Island Airport - Yorke Island (YYKI)'),
('YYMI', 'Yam Island Airport - Yam Island (YYMI)'),
('TNCA', 'Queen Beatrix International Airport - Oranjestad (TNCA)'),
('UBBB', 'Heydar Aliyev International Airport - Baku (UBBB)'),
('UBBG', 'Ganja International Airport - Ganja (UBBG)'),
('UBBL', 'Lankaran International Airport - Lankaran (UBBL)'),
('UBBN', 'Nakhchivan Airport - Nakhchivan (UBBN)'),
('UBBQ', 'Gabala International Airport - Gabala (UBBQ)'),
('LQBK', 'Banja Luka International Airport - Mahovljani (LQBK)'),
('LQMO', 'Mostar International Airport - Mostar (LQMO)'),
('LQSA', 'Sarajevo International Airport - Sarajevo (LQSA)'),
('LQTZ', 'Tuzla International Airport - Dubrave Gornje (LQTZ)'),
('TBPB', 'Grantley Adams International Airport - Bridgetown (TBPB)'),
('VGBR', 'Barisal Airport - Barisal (VGBR)'),
('VGCB', 'Cox''s Bazar Airport - Cox''s Bazar (VGCB)'),
('VGEG', 'Shah Amanat International Airport - Chattogram (Chittagong) (VGEG)'),
('VGHS', 'Hazrat Shahjalal International Airport - Dhaka (VGHS)'),
('VGJR', 'Jessore Airport - Jashore (Jessore) (VGJR)'),
('VGRJ', 'Shah Mokhdum Airport - Rajshahi (VGRJ)'),
('VGSD', 'Saidpur Airport - Saidpur (VGSD)'),
('VGSY', 'Osmany International Airport - Sylhet (VGSY)'),
('EBAW', 'Antwerp International Airport (Deurne) - Antwerp (EBAW)'),
('EBBR', 'Brussels Airport - Zaventem (EBBR)'),
('EBCI', 'Brussels South Charleroi Airport - Charleroi (EBCI)'),
('EBLG', 'Liege Airport - Grâce-Hollogne (EBLG)'),
('EBOS', 'Oostende-Brugge International Airport - Oostende (EBOS)'),
('DFFD', 'Ouagadougou Airport - Ouagadougou (DFFD)'),
('DFOO', 'Bobo Dioulasso Airport - Bobo Dioulasso (DFOO)'),
('LBBG', 'Burgas Airport - Burgas (LBBG)'),
('LBPD', 'Plovdiv International Airport - Plovdiv (LBPD)'),
('LBSF', 'Sofia Airport - Sofia (LBSF)'),
('LBWN', 'Varna Airport - Varna (LBWN)'),
('OBBI', 'Bahrain International Airport - Manama (OBBI)'),
('HBBA', 'Bujumbura Melchior Ndadaye International Airport - Bujumbura (HBBA)'),
('HBBO', 'Kirundo Airport - Kirundo (HBBO)'),
('DBBB', 'Cadjehoun Airport - Cotonou (DBBB)'),
('TFFJ', 'Saint Barthélemy - Gustaf III Airport - Gustavia (TFFJ)'),
('TXKF', 'L.F. Wade International Airport - Hamilton (TXKF)'),
('WBAK', 'Anduki Airport - Seria (WBAK)'),
('WBSB', 'Brunei International Airport - Bandar Seri Begawan (WBSB)'),
('SLAL', 'Alcantarí Airport - Yamparaez (SLAL)'),
('SLCB', 'Jorge Wilsterman International Airport - Cochabamba (SLCB)'),
('SLCO', 'Capitán Aníbal Arab Airport - Cobija (SLCO)'),
('SLET', 'El Trompillo Airport - Santa Cruz (SLET)'),
('SLGY', 'Guayaramerín Airport - Guayaramerín (SLGY)'),
('SLHI', 'Chimore Airport - Chimore (SLHI)'),
('SLLP', 'El Alto International Airport - La Paz / El Alto (SLLP)'),
('SLPR', 'Puerto Rico Airport - Puerto Rico/Manuripi (SLPR)'),
('SLPS', 'Capitán Av. Salvador Ogaya G. airport - Puerto Suárez (SLPS)'),
('SLRI', 'Capitán Av. Selin Zeitun Lopez Airport - Riberalta (SLRI)'),
('SLRQ', 'Rurrenabaque Airport - Rurrenabaque (SLRQ)'),
('SLTJ', 'Capitan Oriel Lea Plaza Airport - Tarija (SLTJ)'),
('SLVR', 'Viru Viru International Airport - Santa Cruz (SLVR)'),
('TNCB', 'Flamingo International Airport - Kralendijk (TNCB)'),
('TNCE', 'F. D. Roosevelt Airport - Oranjestad (TNCE)'),
('TNCS', 'Juancho E. Yrausquin Airport - Zion''s Hill (TNCS)'),
('SJZA', 'Pedro Vieira Moreira Airport - Cajazeiras (SJZA )'),
('SBVC', 'Glauber de Andrade Rocha Airport - Vitória da Conquista (SBVC)'),
('SDYG', 'Fazenda Rosa do Deserto Airstrip - Ubaíra (SDYG)'),
('SBAE', 'Bauru/Arealva–Moussa Nakhal Tobias State Airport - Bauru (SBAE)'),
('SBAQ', 'Araraquara Airport - Araraquara (SBAQ)'),
('SBAR', 'Aracaju - Santa Maria International Airport - Aracaju (SBAR)'),
('SBAT', 'Piloto Osvaldo Marques Dias Airport - Alta Floresta (SBAT)'),
('SBAU', 'Araçatuba Airport - Araçatuba (SBAU)'),
('SBAX', 'Romeu Zema Airport - Araxá (SBAX)'),
('SBBE', 'Val de Cans/Júlio Cezar Ribeiro International Airport - Belém (SBBE)'),
('SBBR', 'Presidente Juscelino Kubitschek International Airport - Brasília (SBBR)'),
('SBBV', 'Atlas Brasil Cantanhede Airport - Boa Vista (SBBV)'),
('SBCA', 'Coronel Adalberto Mendes da Silva Airport - Cascavel (SBCA)'),
('SBCB', 'Cabo Frio Airport - Cabo Frio (SBCB)'),
('SBCF', 'Tancredo Neves International Airport - Belo Horizonte (SBCF)'),
('SBCG', 'Campo Grande Airport - Campo Grande (SBCG)'),
('SBCH', 'Serafin Enoss Bertaso Airport - Chapecó (SBCH)'),
('SBCJ', 'Carajás Airport - Parauapebas (SBCJ)'),
('SBCM', 'Forquilhinha - Criciúma  Airport - Criciúma (SBCM)'),
('SBCN', 'Nelson Ribeiro Guimaraes Airport - Caldas Novas (SBCN)'),
('SBCP', 'Bartolomeu Lisandro Airport - Campos Dos Goytacazes (SBCP)'),
('SBCR', 'Corumbá International Airport - Corumbá (SBCR)'),
('SBCT', 'Afonso Pena Airport - Curitiba (SBCT)'),
('SBCX', 'Hugo Cantergiani Regional Airport - Caxias Do Sul (SBCX)'),
('SBCY', 'Marechal Rondon Airport - Cuiabá (SBCY)'),
('SBCZ', 'Cruzeiro do Sul Airport - Cruzeiro Do Sul (SBCZ)'),
('SBDB', 'Bonito Airport - Bonito (SBDB)'),
('SBDN', 'Presidente Prudente Airport - Presidente Prudente (SBDN)'),
('SBEG', 'Eduardo Gomes International Airport - Manaus (SBEG)'),
('SBFI', 'Cataratas International Airport - Foz do Iguaçu (SBFI)'),
('SBFL', 'Hercílio Luz International Airport - Florianópolis (SBFL)'),
('SBFN', 'Fernando de Noronha Airport - Fernando de Noronha (SBFN)'),
('SBFZ', 'Pinto Martins International Airport - Fortaleza (SBFZ)'),
('SBGL', 'Rio Galeao – Tom Jobim International Airport - Rio De Janeiro (SBGL)'),
('SBGO', 'Santa Genoveva Airport - Goiânia (SBGO)'),
('SBGR', 'Guarulhos - Governador André Franco Montoro International Airport - Sao Paulo (SBGR)'),
('SBGU', 'Tancredo Thomas de Faria Airport - Guarapuava (SBGU)'),
('SBGV', 'Coronel Altino Machado Airport - Governador Valadares (SBGV)'),
('SBHT', 'Altamira Interstate Airport - Altamira (SBHT)'),
('SBIH', 'Itaituba Airport - Itaituba (SBIH)'),
('SBIL', 'Bahia - Jorge Amado Airport - Ilhéus (SBIL)'),
('SBIP', 'Usiminas Airport - Ipatinga (SBIP)'),
('SBIZ', 'Prefeito Renato Moreira Airport - Imperatriz (SBIZ)'),
('SBJA', 'Humberto Ghizzo Bortoluzzi Regional Airport - Jaguaruna (SBJA)'),
('SBJE', 'Comandante Ariston Pessoa Airport - Cruz (SBJE)'),
('SBJF', 'Francisco de Assis Airport - Juiz de Fora (SBJF)'),
('SBJI', 'Ji-Paraná Airport - Ji-Paraná (SBJI)'),
('SBJP', 'Presidente Castro Pinto International Airport - Joao Pessoa (SBJP)'),
('SBJU', 'Orlando Bezerra de Menezes Airport - Juazeiro do Norte (SBJU)'),
('SBJV', 'Lauro Carneiro de Loyola Airport - Joinville (SBJV)'),
('SBKG', 'Presidente Joao Suassuna Airport - Campina Grande (SBKG)'),
('SBKP', 'Viracopos International Airport - Campinas (SBKP)'),
('SBLE', 'Coronel Horácio de Mattos Airport - Lençóis (SBLE)'),
('SBLJ', 'Lages Airport - Lages (SBLJ)'),
('SBLO', 'Governor José Richa Airport - Londrina (SBLO)'),
('SBMA', 'Joao Correa da Rocha Airport - Marabá (SBMA)'),
('SBMG', 'Regional de Maringá - Sílvio Name Júnior Airport - Maringá (SBMG)'),
('SBMK', 'Mário Ribeiro Airport - Montes Claros (SBMK)'),
('SBML', 'Frank Miloye Milenkowichi–Marília State Airport - Marília (SBML)'),
('SBMO', 'Zumbi dos Palmares Airport - Maceió (SBMO)'),
('SBMQ', 'Macapá - Alberto Alcolumbre International Airport - Macapá (SBMQ)'),
('SBMS', 'Dix-Sept Rosado Airport - Mossoró (SBMS)'),
('SBMY', 'Manicoré Airport - Manicoré (SBMY)'),
('SBNF', 'Ministro Victor Konder International Airport - Navegantes (SBNF)'),
('SBNM', 'Santo Ângelo Airport - Santo Ângelo (SBNM)'),
('SBPA', 'Salgado Filho International Airport - Porto Alegre (SBPA)'),
('SBPB', 'Parnaíba - Prefeito Doutor Joao Silva Filho International Airport - Parnaíba (SBPB)'),
('SBPF', 'Lauro Kurtz Airport - Passo Fundo (SBPF)'),
('SBPG', 'Ponta Grossa Airport - Comandante Antonio Amilton Beraldo - Ponta Grossa (SBPG)'),
('SBPJ', 'Brigadeiro Lysias Rodrigues Airport - Palmas (SBPJ)'),
('SBPK', 'Joao Simoes Lopes Neto International Airport - Pelotas (SBPK)'),
('SBPL', 'Senador Nilo Coelho Airport - Petrolina (SBPL)'),
('SBPO', 'Juvenal Loureiro Cardoso Airport - Pato Branco (SBPO)'),
('SBPP', 'Ponta Pora Airport - Ponta Pora (SBPP)'),
('SBPS', 'Porto Seguro Airport - Porto Seguro (SBPS)'),
('SBPV', 'Governador Jorge Teixeira de Oliveira Airport - Porto Velho (SBPV)'),
('LFMT', 'Montpellier-Méditerranée Airport - Montpellier/Méditerranée (LFMT)'),
('LFMU', 'Béziers-Vias Airport - Béziers/Vias (LFMU)'),
('LFMV', 'Avignon-Caumont Airport - Avignon, Vaucluse (LFMV)'),
('LFOB', 'Paris-Beauvais Airport - Tillé (LFOB)'),
('LFOK', 'Châlons-Vatry Airport - Bussy-Lettrée (LFOK)'),
('LFOT', 'Tours Val de Loire Airport - Tours, Indre-et-Loire (LFOT)'),
('LFPG', 'Charles de Gaulle International Airport - Paris (Roissy-en-France, Val-d''Oise) (LFPG)'),
('LFPO', 'Paris-Orly Airport - Paris (Orly, Val-de-Marne) (LFPO)'),
('LFQQ', 'Lille Airport - Lesquin (LFQQ)'),
('LFRB', 'Brest Bretagne Airport - Brest/Guipavas (LFRB)'),
('LFRD', 'Dinard-Pleurtuit-Saint-Malo Airport - Pleurtuit, Ille-et-Vilaine (LFRD)'),
('LFRG', 'Deauville-Normandie Airport - Deauville, Calvados (LFRG)'),
('LFRH', 'Lorient South Brittany (Bretagne Sud) Airport - Lorient/Lann/Bihoué (LFRH)'),
('LFRK', 'Caen-Carpiquet Airport - Carpiquet, Calvados (LFRK)'),
('LFRM', 'Le Mans-Arnage Airport - Le Mans, Sarthe (LFRM)'),
('LFRN', 'Rennes-Saint-Jacques Airport - Saint-Jacques-de-la-Lande, Ille-et-Vilaine (LFRN)'),
('LFRS', 'Nantes Atlantique Airport - Nantes (LFRS)'),
('LFRZ', 'Saint-Nazaire-Montoir Airport - Saint-Nazaire/Montoir (LFRZ)'),
('LFSB', 'EuroAirport Basel-Mulhouse-Freiburg - Saint-Louis (LFSB)'),
('LFSD', 'Dijon-Bourgogne Airport - Ouges, Côte-d''Or (LFSD)'),
('LFSL', 'Brive-Souillac - Brive la Gaillarde (LFSL)'),
('LFST', 'Strasbourg Airport - Strasbourg (LFST)'),
('LFTH', 'Toulon-Hyeres Airport - Hyeres, Var (LFTH)'),
('LFTW', 'Nîmes-Arles-Camargue Airport - Nîmes/Garons (LFTW)'),
('LFTZ', 'La Môle-Saint-Tropez Airport - La Môle, Var (LFTZ)'),
('FOGO', 'Oyem Airport - Oyem (FOGO)'),
('FOOG', 'Port Gentil Airport - Port Gentil (FOOG)'),
('FOOK', 'Makokou Airport - Makokou (FOOK)'),
('FOOL', 'Libreville Leon M''ba International Airport - Libreville (FOOL)'),
('FOON', 'M''Vengue El Hadj Omar Bongo Ondimba International Airport - Franceville (FOON)'),
('FOGX', 'Gamba Airport - Gamba (FOGX)'),
('EGAA', 'Belfast International Airport - Belfast (EGAA)'),
('EGAC', 'George Best Belfast City Airport - Belfast (EGAC)'),
('EGAE', 'City of Derry Airport - Derry (EGAE)'),
('EGBB', 'Birmingham Airport - Birmingham, West Midlands (EGBB)'),
('EGCC', 'Manchester Airport - Manchester, Greater Manchester (EGCC)'),
('EGEC', 'Campbeltown Airport - Campbeltown (EGEC)'),
('EGED', 'Eday Airport - Eday (EGED)'),
('EGEF', 'Fair Isle Airport - Fair Isle (EGEF)'),
('EGEL', 'Coll Airport - Coll Island (EGEL)'),
('EGEN', 'North Ronaldsay Airport - North Ronaldsay (EGEN)'),
('EGEO', 'Oban Airport - North Connel (EGEO)'),
('EGEP', 'Papa Westray Airport - Papa Westray (EGEP)'),
('EGER', 'Stronsay Airport - Stronsay (EGER)'),
('EGES', 'Sanday Airport - Sanday (EGES)'),
('EGET', 'Lerwick / Tingwall Airport - Lerwick, Shetland Islands (EGET)'),
('EGEW', 'Westray Airport - Westray (EGEW)'),
('EGEY', 'Colonsay Airstrip - Colonsay (EGEY)'),
('EGFF', 'Cardiff International Airport - Cardiff (EGFF)'),
('EGGD', 'Bristol Airport - Bristol (EGGD)'),
('EGGP', 'Liverpool John Lennon Airport - Liverpool (EGGP)'),
('EGGW', 'London Luton Airport - Luton, Bedfordshire (EGGW)'),
('EGHC', 'Land''s End Airport - Land''s End, Cornwall (EGHC)'),
('EGHE', 'St. Mary''s Airport - St. Mary''s, Isles of Scilly (EGHE)'),
('EGHH', 'Bournemouth Airport - Bournemouth (EGHH)'),
('EGHI', 'Southampton Airport - Southampton (EGHI)'),
('EGHQ', 'Cornwall Airport Newquay - Newquay (EGHQ)'),
('EGKK', 'London Gatwick Airport - London (EGKK)'),
('EGLC', 'London City Airport - London (EGLC)'),
('EGLL', 'London Heathrow Airport - London (EGLL)'),
('EGMC', 'London Southend Airport - Southend-on-Sea, Essex (EGMC)'),
('EGNJ', 'Humberside Airport - Grimsby, Lincolnshire (EGNJ)'),
('EGNM', 'Leeds Bradford Airport - Leeds, West Yorkshire (EGNM)'),
('EGNT', 'Newcastle International Airport - Newcastle upon Tyne, Tyne and Wear (EGNT)'),
('EGNV', 'Teesside International Airport - Darlington, Durham (EGNV)'),
('EGNX', 'East Midlands Airport - Nottingham (EGNX)'),
('EGPA', 'Kirkwall Airport - Orkney Islands (EGPA)'),
('EGPB', 'Sumburgh Airport - Lerwick, Shetland (EGPB)'),
('EGPC', 'Wick John O''Groats Airport - Wick (EGPC)'),
('EGPD', 'Aberdeen International Airport - Aberdeen (EGPD)'),
('EGPE', 'Inverness Airport - Inverness (EGPE)'),
('EGPF', 'Glasgow Airport - Glasgow (EGPF)'),
('EGPH', 'Edinburgh Airport - Edinburgh (EGPH)'),
('EGPI', 'Islay Airport - Isle of Islay, Argyll and Bute (EGPI)'),
('EGPK', 'Glasgow Prestwick Airport - Prestwick, South Ayrshire (EGPK)'),
('EGPL', 'Benbecula Airport - Balivanich (EGPL)'),
('EGPN', 'Dundee Airport - Dundee (EGPN)'),
('EGPO', 'Stornoway Airport - Stornoway, Western Isles (EGPO)'),
('EGPR', 'Barra Airport - Eoligarry (EGPR)'),
('EGPU', 'Tiree Airport - Balemartine (EGPU)'),
('EGSH', 'Norwich Airport - Norwich, Norfolk (EGSH)'),
('EGSS', 'London Stansted Airport - London (EGSS)'),
('EGTE', 'Exeter International Airport - Exeter, Devon (EGTE)'),
('EGFO', 'Foula Airfield - Foula (EGFO )'),
('TGPY', 'Maurice Bishop International Airport - Saint George''s (TGPY)'),
('TGPZ', 'Lauriston Airport - Carriacou Island (TGPZ)'),
('UGAM', 'Ambrolauri Airport - Ambrolauri (UGAM)'),
('UGKO', 'David the Builder Kutaisi International Airport - Kopitnari (UGKO)'),
('UGMS', 'Mestia Queen Tamar Airport - Mestia (UGMS)'),
('UGSA', 'Natakhtari Airfield - Natakhtari (UGSA)'),
('UGSB', 'Batumi International Airport - Batumi (UGSB)'),
('UGSS', 'Sukhumi Babushara /  Vladislav Ardzinba International Airport - Sukhumi (UGSS)'),
('UGTB', 'Tbilisi International Airport - Tbilisi (UGTB)'),
('SOCA', 'Cayenne – Félix Eboué Airport - Matoury (SOCA)'),
('SOOM', 'Saint-Laurent-du-Maroni Airport - Saint-Laurent-du-Maroni (SOOM)'),
('EGJA', 'Alderney Airport - Saint Anne (EGJA)'),
('EGJB', 'Guernsey Airport - Saint Peter Port (EGJB)'),
('DGAA', 'Kotoka International Airport - Accra (DGAA)'),
('DGAH', 'Ho Airport - Ho (DGAH)'),
('DGLE', 'Tamale Airport - Tamale (DGLE)'),
('DGSI', 'Kumasi Airport - Kumasi (DGSI)'),
('DGSN', 'Sunyani Airport - Sunyani (DGSN)'),
('DGTK', 'Takoradi Airport - Sekondi-Takoradi (DGTK)'),
('LXGB', 'Gibraltar Airport - Gibraltar (LXGB)'),
('BGAA', 'Aasiaat Airport - Aasiaat (BGAA)'),
('BGBW', 'Narsarsuaq Airport - Narsarsuaq (BGBW)'),
('BGCO', 'Neerlerit Inaat Airport - Neerlerit Inaat (BGCO)'),
('BGGH', 'Nuuk Airport - Nuuk (BGGH)'),
('BGJN', 'Ilulissat Airport - Ilulissat (BGJN)'),
('BGKK', 'Kulusuk Airport - Kulusuk (BGKK)'),
('BGMQ', 'Maniitsoq Airport - Maniitsoq (BGMQ)'),
('BGPT', 'Paamiut Airport - Paamiut (BGPT)'),
('BGQQ', 'Qaanaaq Airport - Qaanaaq (BGQQ)'),
('BGSF', 'Kangerlussuaq Airport - Kangerlussuaq (BGSF)'),
('BGSS', 'Sisimiut Airport - Sisimiut (BGSS)'),
('BGTL', 'Pituffik Space Base - Pituffik (BGTL)'),
('BGUK', 'Upernavik Airport - Upernavik (BGUK)'),
('BGUQ', 'Qaarsut Airport - Uummannaq (BGUQ)'),
('GBYD', 'Banjul International Airport - Yundum (GBYD)'),
('GUCY', 'Conakry International Airport - Conakry (GUCY)'),
('TFFA', 'La Désirade Airport - Grande Anse (TFFA)'),
('TFFB', 'Basse-Terre Baillif Airport - Basse-Terre (TFFB)'),
('TFFC', 'St-François Airport - St-François (TFFC)'),
('TFFM', 'Marie-Galante Airport - Grand-Bourg (TFFM)'),
('TFFR', 'Guadeloupe - Maryse Condé International Airport - Pointe-a-Pitre (TFFR)'),
('FGAB', 'Annobón Airport - San Antonio de Palé (FGAB)'),
('FGBT', 'Bata Airport - Bata (FGBT)'),
('FGSL', 'Malabo Airport - Malabo (FGSL)'),
('LGAL', 'Alexandroupoli Democritus Airport - Alexandroupolis (LGAL)'),
('LGAV', 'Athens Eleftherios Venizelos International Airport - Spata-Artemida (LGAV)'),
('LGBL', 'Nea Anchialos National Airport - Nea Anchialos (LGBL)'),
('LGHI', 'Chios Island National Airport - Chios Island (LGHI)'),
('LGIK', 'Ikaria Airport - Ikaria Island (LGIK)'),
('LGIO', 'Ioannina King Pyrrhus National Airport - Ioannina (LGIO)'),
('LGIR', 'Heraklion International Nikos Kazantzakis Airport - Heraklion (LGIR)'),
('LGKA', 'Kastoria National Airport Aristotle - Argos Orestiko (LGKA)'),
('LGKC', 'Kithira Airport - Kithira Island (LGKC)'),
('LGKF', 'Kefallinia Airport - Kefallinia Island (LGKF)'),
('LGKJ', 'Kastelorizo Airport - Kastelorizo Island (LGKJ)'),
('LGKL', 'Kalamata Airport - Kalamata (LGKL)'),
('LGKO', 'Kos Airport - Kos Island (LGKO)'),
('LGKP', 'Karpathos Airport - Karpathos Island (LGKP)'),
('ID-0202', 'Mipol Airstrip - Pegunungan Bintang Regency (ID-0202)'),
('ID-0210', 'Kirimu Airstrip - Pegunungan Bintang Regency (ID-0210)'),
('WABI', 'Old Nabire Airport - Nabire (WABI)'),
('WIMG', 'Tabing Airport - Padang (WIMG)'),
('WIJI', 'Departi Parbo Airport - Sungai Penuh (WIJI)'),
('WIBR', 'Mentawai Airport - Sipura Island (WIBR)'),
('WABV', 'Bilogai-Sugapa Airport - Sugapa (WABV)'),
('WAPM', 'Jos Orno Imsula Airport - Tiakur (WAPM)'),
('WAFO', 'Maleo Airport - Morowali (WAFO)'),
('WAAA', 'Hasanuddin International Airport - Ujung Pandang (WAAA)'),
('WABB', 'Frans Kaisiepo Airport - Biak (WABB)'),
('WAYY', 'Mozes Kilangin Airport - Timika (WAYY)'),
('WADB', 'Sultan Muhammad Salahuddin Airport - Palibelo, Bima (WADB)'),
('WADD', 'Denpasar I Gusti Ngurah Rai International Airport - Kuta, Badung (WADD)'),
('WADE', 'Lieutenant Colonel Wisnu Airfield - Gerokgak, Buleleng (WADE)'),
('WADL', 'Lombok International Airport - Mataram (Pujut, Lombok Tengah) (WADL)'),
('WADS', 'Sultan Muhammad Kaharuddin III Airport - Sumbawa Besar (WADS)'),
('WADT', 'Tambolaka Airport - Radamata (WADT)'),
('WATU', 'Umbu Mehang Kunda Airport - Waingapu-Sumba Island (WATU)'),
('WADY', 'Banyuwangi Airport - Rogojampi, Banyuwangi (WADY)'),
('WAEE', 'Sultan Babullah Airport - Sango (WAEE)'),
('WAFB', 'Toraja Airport - Toraja (WAFB)'),
('WAFD', 'Bua - Palopo Lagaligo Airport - Palopo (WAFD)'),
('WAFF', 'Mutiara - SIS Al-Jufrie Airport - Palu (WAFF)'),
('WAMI', 'Sultan Bantilan Airport - Toli Toli-Celebes Island (WAMI)'),
('WAFU', 'Tanjung Api Airport - Tojo Una-Una (WAFU)'),
('WAGB', 'Haji Muhammad Sidik Airport - Muara Teweh (WAGB)'),
('WAGF', 'Seruyan Kuala Pembuang Airport - Seruyan (WAGF)'),
('WAGG', 'Tjilik Riwut Airport - Palangkaraya (WAGG)')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
